// Generated by delombok at Wed May 13 12:27:37 IST 2026
package io.sclera.models;

import io.sclera.dto.ClientBarCodeDTO;
import javax.persistence.*;
import java.math.BigInteger;

@SqlResultSetMapping(name = "clientbarcodedetails", classes = {@ConstructorResult(targetClass = ClientBarCodeDTO.class, columns = {@ColumnResult(name = "id", type = String.class), @ColumnResult(name = "device_id", type = String.class), @ColumnResult(name = "location_id", type = String.class)})})
@NamedNativeQueries({
    @NamedNativeQuery(name = "ClientBarCode.updateIsDeletedForAllClientBarCode", query = "UPDATE client_bar_code SET is_deleted = true", resultClass = ClientBarCode.class),
    @NamedNativeQuery(name = "ClientBarCode.deleteOldClientBarCode", query = "DELETE FROM client_bar_code WHERE is_deleted = true", resultClass = ClientBarCode.class),
    @NamedNativeQuery(name = "ClientBarCode.getClientBarCodeCountByDeviceId", query = "SELECT COUNT(cbc.device_id) FROM client_bar_code cbc LEFT JOIN device d ON d.id = cbc.device_id WHERE d.id = ?1", resultClass = ClientBarCode.class),
    @NamedNativeQuery(name = "ClientBarCode.getLocationIdsTaggedToClientBarCode", query = "SELECT location_id FROM client_bar_code WHERE location_id IS NOT NULL AND device_id IS NULL", resultClass = ClientBarCode.class),
    @NamedNativeQuery(name = "ClientBarCode.getDeviceIdsTaggedToClientBarCode", query = "SELECT device_id FROM client_bar_code WHERE device_id IS NOT NULL AND location_id IS NULL", resultClass = ClientBarCode.class),
    @NamedNativeQuery(name = "ClientBarCode.getBarCodesByLocationIds", query = "SELECT cbc.id, cbc.device_id, cbc.location_id FROM client_bar_code cbc WHERE cbc.location_id IN ?1", resultSetMapping = "clientbarcodedetails"),
    @NamedNativeQuery(name = "ClientBarCode.getBarCodesByDeviceIds", query = "SELECT cbc.id, cbc.device_id, cbc.location_id FROM client_bar_code cbc WHERE cbc.device_id IN ?1", resultSetMapping = "clientbarcodedetails")
})
@Entity
public class ClientBarCode {
    @Id
    private String id;
    private String addedAt;
    private String addedBy;
    private String clientBarCodeId;
    private BigInteger updatedAt;
    private String updatedBy;
    private String vdmsId;
    private String batchId;
    @ManyToOne
    private Device device;
    @ManyToOne
    private Location location;
    private Boolean isDeleted;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAddedAt() {
        return this.addedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAddedBy() {
        return this.addedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getClientBarCodeId() {
        return this.clientBarCodeId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigInteger getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVdmsId() {
        return this.vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBatchId() {
        return this.batchId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Device getDevice() {
        return this.device;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Location getLocation() {
        return this.location;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAddedAt(final String addedAt) {
        this.addedAt = addedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAddedBy(final String addedBy) {
        this.addedBy = addedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setClientBarCodeId(final String clientBarCodeId) {
        this.clientBarCodeId = clientBarCodeId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final BigInteger updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedBy(final String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVdmsId(final String vdmsId) {
        this.vdmsId = vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBatchId(final String batchId) {
        this.batchId = batchId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDevice(final Device device) {
        this.device = device;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLocation(final Location location) {
        this.location = location;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsDeleted(final Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ClientBarCode)) return false;
        final ClientBarCode other = (ClientBarCode) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$isDeleted = this.getIsDeleted();
        final java.lang.Object other$isDeleted = other.getIsDeleted();
        if (this$isDeleted == null ? other$isDeleted != null : !this$isDeleted.equals(other$isDeleted)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$addedAt = this.getAddedAt();
        final java.lang.Object other$addedAt = other.getAddedAt();
        if (this$addedAt == null ? other$addedAt != null : !this$addedAt.equals(other$addedAt)) return false;
        final java.lang.Object this$addedBy = this.getAddedBy();
        final java.lang.Object other$addedBy = other.getAddedBy();
        if (this$addedBy == null ? other$addedBy != null : !this$addedBy.equals(other$addedBy)) return false;
        final java.lang.Object this$clientBarCodeId = this.getClientBarCodeId();
        final java.lang.Object other$clientBarCodeId = other.getClientBarCodeId();
        if (this$clientBarCodeId == null ? other$clientBarCodeId != null : !this$clientBarCodeId.equals(other$clientBarCodeId)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        final java.lang.Object this$updatedBy = this.getUpdatedBy();
        final java.lang.Object other$updatedBy = other.getUpdatedBy();
        if (this$updatedBy == null ? other$updatedBy != null : !this$updatedBy.equals(other$updatedBy)) return false;
        final java.lang.Object this$vdmsId = this.getVdmsId();
        final java.lang.Object other$vdmsId = other.getVdmsId();
        if (this$vdmsId == null ? other$vdmsId != null : !this$vdmsId.equals(other$vdmsId)) return false;
        final java.lang.Object this$batchId = this.getBatchId();
        final java.lang.Object other$batchId = other.getBatchId();
        if (this$batchId == null ? other$batchId != null : !this$batchId.equals(other$batchId)) return false;
        final java.lang.Object this$device = this.getDevice();
        final java.lang.Object other$device = other.getDevice();
        if (this$device == null ? other$device != null : !this$device.equals(other$device)) return false;
        final java.lang.Object this$location = this.getLocation();
        final java.lang.Object other$location = other.getLocation();
        if (this$location == null ? other$location != null : !this$location.equals(other$location)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ClientBarCode;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $isDeleted = this.getIsDeleted();
        result = result * PRIME + ($isDeleted == null ? 43 : $isDeleted.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $addedAt = this.getAddedAt();
        result = result * PRIME + ($addedAt == null ? 43 : $addedAt.hashCode());
        final java.lang.Object $addedBy = this.getAddedBy();
        result = result * PRIME + ($addedBy == null ? 43 : $addedBy.hashCode());
        final java.lang.Object $clientBarCodeId = this.getClientBarCodeId();
        result = result * PRIME + ($clientBarCodeId == null ? 43 : $clientBarCodeId.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        final java.lang.Object $updatedBy = this.getUpdatedBy();
        result = result * PRIME + ($updatedBy == null ? 43 : $updatedBy.hashCode());
        final java.lang.Object $vdmsId = this.getVdmsId();
        result = result * PRIME + ($vdmsId == null ? 43 : $vdmsId.hashCode());
        final java.lang.Object $batchId = this.getBatchId();
        result = result * PRIME + ($batchId == null ? 43 : $batchId.hashCode());
        final java.lang.Object $device = this.getDevice();
        result = result * PRIME + ($device == null ? 43 : $device.hashCode());
        final java.lang.Object $location = this.getLocation();
        result = result * PRIME + ($location == null ? 43 : $location.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ClientBarCode(id=" + this.getId() + ", addedAt=" + this.getAddedAt() + ", addedBy=" + this.getAddedBy() + ", clientBarCodeId=" + this.getClientBarCodeId() + ", updatedAt=" + this.getUpdatedAt() + ", updatedBy=" + this.getUpdatedBy() + ", vdmsId=" + this.getVdmsId() + ", batchId=" + this.getBatchId() + ", device=" + this.getDevice() + ", location=" + this.getLocation() + ", isDeleted=" + this.getIsDeleted() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ClientBarCode(final String id, final String addedAt, final String addedBy, final String clientBarCodeId, final BigInteger updatedAt, final String updatedBy, final String vdmsId, final String batchId, final Device device, final Location location, final Boolean isDeleted) {
        this.id = id;
        this.addedAt = addedAt;
        this.addedBy = addedBy;
        this.clientBarCodeId = clientBarCodeId;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
        this.vdmsId = vdmsId;
        this.batchId = batchId;
        this.device = device;
        this.location = location;
        this.isDeleted = isDeleted;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ClientBarCode() {
    }
}
