// Generated by delombok at Wed May 13 12:28:12 IST 2026
package io.sclera.models;

import io.sclera.dto.DeviceTechnicianAISuggestionDTO;
import javax.persistence.*;

@SqlResultSetMapping(name = "deviceTechnicianAISuggestionMapping", classes = {@ConstructorResult(targetClass = DeviceTechnicianAISuggestionDTO.class, columns = {@ColumnResult(name = "id", type = String.class), @ColumnResult(name = "deviceType", type = String.class), @ColumnResult(name = "technicians", type = String.class), @ColumnResult(name = "vdmsId", type = String.class)})})
@NamedNativeQuery(name = "DeviceTechnicianAISuggestion.getAlldevicetechnician", query = "SELECT id, device_type AS deviceType, technicians, vdms_id AS vdmsId FROM device_technician_ai_suggestion", resultSetMapping = "deviceTechnicianAISuggestionMapping")
@NamedNativeQuery(name = "DeviceTechnicianAISuggestion.getdevicetechnicianbyid", query = "SELECT id, device_type AS deviceType, technicians, vdms_id AS vdmsId FROM device_technician_ai_suggestion WHERE id = ?1", resultSetMapping = "deviceTechnicianAISuggestionMapping")
@Entity
@Table(name = "device_technician_ai_suggestion")
public class DeviceTechnicianAISuggestion {
    @Id
    private String id;
    @Column(nullable = false)
    private String deviceType;
    @Column(columnDefinition = "json")
    private String technicians;
    @ManyToOne
    @JoinColumn(name = "vdms_id")
    private Vdms vdms;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeviceType() {
        return this.deviceType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTechnicians() {
        return this.technicians;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Vdms getVdms() {
        return this.vdms;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeviceType(final String deviceType) {
        this.deviceType = deviceType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTechnicians(final String technicians) {
        this.technicians = technicians;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVdms(final Vdms vdms) {
        this.vdms = vdms;
    }
}
