// Generated by delombok at Wed May 13 12:28:07 IST 2026
package io.sclera.models;

import javax.persistence.*;
import java.util.Objects;
import java.util.Set;

@Entity
public class DeviceSpecification {
    //mac-address is stored as ID
    @Id
    private String id;
    @Column(name = "created_at")
    private Long createdAt;
    @Column(name = "updated_at")
    private Long updatedAt;
    @Column(name = "username", length = 255)
    private String username;
    @Column(name = "email", length = 255)
    private String email;
    @Column(name = "account_type", length = 255)
    private String accountType;
    @Column(name = "user_uuid", length = 255)
    private String userUUID;
    @Column(name = "device_name", length = 255)
    private String deviceName;
    @Column(name = "model", length = 255)
    private String model;
    @Column(name = "os_type", length = 255)
    private String osType;
    @Column(name = "location_info", length = 1024)
    private String locationInfo;
    @Column(name = "os_info", length = 1024)
    private String osInfo;
    @Column(name = "cpu_info", length = 512)
    private String cpuInfo;
    @Lob
    @Column(name = "disk_drives", columnDefinition = "LONGTEXT")
    private String diskDrives;
    @Lob
    @Column(name = "physical_disks", columnDefinition = "LONGTEXT")
    private String physicalDisks;
    @Column(name = "bios", length = 512)
    private String bios;
    @Column(name = "ram_info", length = 512)
    private String ramInfo;
    @Column(name = "video_cards", length = 1024)
    private String videoCards;
    @Column(name = "sound_devices", length = 1024)
    private String soundDevices;
    @Column(name = "battery_info", length = 255)
    private String batteryInfo;
    @Lob
    @Column(name = "processes", columnDefinition = "LONGTEXT")
    private String processes;
    @Lob
    @Column(name = "system_updates", columnDefinition = "LONGTEXT")
    private String systemUpdates;
    // Relationship mapping (lazy fetch, optional)
    @OneToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "device_id", referencedColumnName = "id", insertable = false, updatable = false)
    private Device device;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "deviceSpecification")
    private Set<DeviceInstalledApps> deviceInstalledApps;
    @Lob
    @Column(name = "child_devices", columnDefinition = "LONGTEXT")
    private String childDevices;

    @Override
    public int hashCode() {
        return Objects.hash(id); // Use only basic fields like id
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class DeviceSpecificationBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long createdAt;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long updatedAt;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String username;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String email;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String accountType;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String userUUID;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String deviceName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String model;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String osType;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String locationInfo;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String osInfo;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String cpuInfo;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String diskDrives;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String physicalDisks;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String bios;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String ramInfo;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String videoCards;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String soundDevices;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String batteryInfo;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String processes;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String systemUpdates;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Device device;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Set<DeviceInstalledApps> deviceInstalledApps;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String childDevices;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        DeviceSpecificationBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder id(final String id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder createdAt(final Long createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder updatedAt(final Long updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder username(final String username) {
            this.username = username;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder accountType(final String accountType) {
            this.accountType = accountType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder userUUID(final String userUUID) {
            this.userUUID = userUUID;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder deviceName(final String deviceName) {
            this.deviceName = deviceName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder model(final String model) {
            this.model = model;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder osType(final String osType) {
            this.osType = osType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder locationInfo(final String locationInfo) {
            this.locationInfo = locationInfo;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder osInfo(final String osInfo) {
            this.osInfo = osInfo;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder cpuInfo(final String cpuInfo) {
            this.cpuInfo = cpuInfo;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder diskDrives(final String diskDrives) {
            this.diskDrives = diskDrives;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder physicalDisks(final String physicalDisks) {
            this.physicalDisks = physicalDisks;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder bios(final String bios) {
            this.bios = bios;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder ramInfo(final String ramInfo) {
            this.ramInfo = ramInfo;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder videoCards(final String videoCards) {
            this.videoCards = videoCards;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder soundDevices(final String soundDevices) {
            this.soundDevices = soundDevices;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder batteryInfo(final String batteryInfo) {
            this.batteryInfo = batteryInfo;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder processes(final String processes) {
            this.processes = processes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder systemUpdates(final String systemUpdates) {
            this.systemUpdates = systemUpdates;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder device(final Device device) {
            this.device = device;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder deviceInstalledApps(final Set<DeviceInstalledApps> deviceInstalledApps) {
            this.deviceInstalledApps = deviceInstalledApps;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification.DeviceSpecificationBuilder childDevices(final String childDevices) {
            this.childDevices = childDevices;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DeviceSpecification build() {
            return new DeviceSpecification(this.id, this.createdAt, this.updatedAt, this.username, this.email, this.accountType, this.userUUID, this.deviceName, this.model, this.osType, this.locationInfo, this.osInfo, this.cpuInfo, this.diskDrives, this.physicalDisks, this.bios, this.ramInfo, this.videoCards, this.soundDevices, this.batteryInfo, this.processes, this.systemUpdates, this.device, this.deviceInstalledApps, this.childDevices);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "DeviceSpecification.DeviceSpecificationBuilder(id=" + this.id + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ", username=" + this.username + ", email=" + this.email + ", accountType=" + this.accountType + ", userUUID=" + this.userUUID + ", deviceName=" + this.deviceName + ", model=" + this.model + ", osType=" + this.osType + ", locationInfo=" + this.locationInfo + ", osInfo=" + this.osInfo + ", cpuInfo=" + this.cpuInfo + ", diskDrives=" + this.diskDrives + ", physicalDisks=" + this.physicalDisks + ", bios=" + this.bios + ", ramInfo=" + this.ramInfo + ", videoCards=" + this.videoCards + ", soundDevices=" + this.soundDevices + ", batteryInfo=" + this.batteryInfo + ", processes=" + this.processes + ", systemUpdates=" + this.systemUpdates + ", device=" + this.device + ", deviceInstalledApps=" + this.deviceInstalledApps + ", childDevices=" + this.childDevices + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static DeviceSpecification.DeviceSpecificationBuilder builder() {
        return new DeviceSpecification.DeviceSpecificationBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUsername() {
        return this.username;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAccountType() {
        return this.accountType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUserUUID() {
        return this.userUUID;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeviceName() {
        return this.deviceName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getModel() {
        return this.model;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getOsType() {
        return this.osType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLocationInfo() {
        return this.locationInfo;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getOsInfo() {
        return this.osInfo;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCpuInfo() {
        return this.cpuInfo;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDiskDrives() {
        return this.diskDrives;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhysicalDisks() {
        return this.physicalDisks;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBios() {
        return this.bios;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRamInfo() {
        return this.ramInfo;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVideoCards() {
        return this.videoCards;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSoundDevices() {
        return this.soundDevices;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBatteryInfo() {
        return this.batteryInfo;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getProcesses() {
        return this.processes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSystemUpdates() {
        return this.systemUpdates;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Device getDevice() {
        return this.device;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Set<DeviceInstalledApps> getDeviceInstalledApps() {
        return this.deviceInstalledApps;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getChildDevices() {
        return this.childDevices;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final Long createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUsername(final String username) {
        this.username = username;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAccountType(final String accountType) {
        this.accountType = accountType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUserUUID(final String userUUID) {
        this.userUUID = userUUID;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeviceName(final String deviceName) {
        this.deviceName = deviceName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setModel(final String model) {
        this.model = model;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOsType(final String osType) {
        this.osType = osType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLocationInfo(final String locationInfo) {
        this.locationInfo = locationInfo;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOsInfo(final String osInfo) {
        this.osInfo = osInfo;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCpuInfo(final String cpuInfo) {
        this.cpuInfo = cpuInfo;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDiskDrives(final String diskDrives) {
        this.diskDrives = diskDrives;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhysicalDisks(final String physicalDisks) {
        this.physicalDisks = physicalDisks;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBios(final String bios) {
        this.bios = bios;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRamInfo(final String ramInfo) {
        this.ramInfo = ramInfo;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVideoCards(final String videoCards) {
        this.videoCards = videoCards;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSoundDevices(final String soundDevices) {
        this.soundDevices = soundDevices;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBatteryInfo(final String batteryInfo) {
        this.batteryInfo = batteryInfo;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProcesses(final String processes) {
        this.processes = processes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSystemUpdates(final String systemUpdates) {
        this.systemUpdates = systemUpdates;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDevice(final Device device) {
        this.device = device;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeviceInstalledApps(final Set<DeviceInstalledApps> deviceInstalledApps) {
        this.deviceInstalledApps = deviceInstalledApps;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setChildDevices(final String childDevices) {
        this.childDevices = childDevices;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "DeviceSpecification(id=" + this.getId() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ", username=" + this.getUsername() + ", email=" + this.getEmail() + ", accountType=" + this.getAccountType() + ", userUUID=" + this.getUserUUID() + ", deviceName=" + this.getDeviceName() + ", model=" + this.getModel() + ", osType=" + this.getOsType() + ", locationInfo=" + this.getLocationInfo() + ", osInfo=" + this.getOsInfo() + ", cpuInfo=" + this.getCpuInfo() + ", diskDrives=" + this.getDiskDrives() + ", physicalDisks=" + this.getPhysicalDisks() + ", bios=" + this.getBios() + ", ramInfo=" + this.getRamInfo() + ", videoCards=" + this.getVideoCards() + ", soundDevices=" + this.getSoundDevices() + ", batteryInfo=" + this.getBatteryInfo() + ", processes=" + this.getProcesses() + ", systemUpdates=" + this.getSystemUpdates() + ", device=" + this.getDevice() + ", deviceInstalledApps=" + this.getDeviceInstalledApps() + ", childDevices=" + this.getChildDevices() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DeviceSpecification() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DeviceSpecification(final String id, final Long createdAt, final Long updatedAt, final String username, final String email, final String accountType, final String userUUID, final String deviceName, final String model, final String osType, final String locationInfo, final String osInfo, final String cpuInfo, final String diskDrives, final String physicalDisks, final String bios, final String ramInfo, final String videoCards, final String soundDevices, final String batteryInfo, final String processes, final String systemUpdates, final Device device, final Set<DeviceInstalledApps> deviceInstalledApps, final String childDevices) {
        this.id = id;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.username = username;
        this.email = email;
        this.accountType = accountType;
        this.userUUID = userUUID;
        this.deviceName = deviceName;
        this.model = model;
        this.osType = osType;
        this.locationInfo = locationInfo;
        this.osInfo = osInfo;
        this.cpuInfo = cpuInfo;
        this.diskDrives = diskDrives;
        this.physicalDisks = physicalDisks;
        this.bios = bios;
        this.ramInfo = ramInfo;
        this.videoCards = videoCards;
        this.soundDevices = soundDevices;
        this.batteryInfo = batteryInfo;
        this.processes = processes;
        this.systemUpdates = systemUpdates;
        this.device = device;
        this.deviceInstalledApps = deviceInstalledApps;
        this.childDevices = childDevices;
    }
}
