// Generated by delombok at Wed May 13 12:28:12 IST 2026
package io.sclera.models;

import jakarta.persistence.*;

/**
 * Represents an AI-generated suggestion of suitable technicians for a given device type within a VDMS.
 * Used to recommend technicians when assigning device maintenance or onboarding tasks.
 */
@Entity
@Table(name = "device_technician_ai_suggestion")
public class DeviceTechnicianAISuggestion {
    @Id
    private String id;
    @Column(nullable = false)
    private String deviceType;
    @Column(columnDefinition = "jsonb")
    private String technicians;
    @ManyToOne
    @JoinColumn(name = "vdms_id")
    private Vdms vdms;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeviceType() {
        return this.deviceType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTechnicians() {
        return this.technicians;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Vdms getVdms() {
        return this.vdms;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeviceType(final String deviceType) {
        this.deviceType = deviceType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTechnicians(final String technicians) {
        this.technicians = technicians;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVdms(final Vdms vdms) {
        this.vdms = vdms;
    }
}
