// Generated by delombok at Wed May 13 12:28:02 IST 2026
package io.sclera.models;

import io.sclera.dto.DeviceOnboardStatusAssigneeDTO;
import javax.persistence.*;

@SqlResultSetMapping(name = "deviceonboardassigneemapping", classes = {@ConstructorResult(targetClass = DeviceOnboardStatusAssigneeDTO.class, columns = {@ColumnResult(name = "id", type = String.class), @ColumnResult(name = "type", type = String.class), @ColumnResult(name = "email", type = String.class), @ColumnResult(name = "device_onboard_status_id", type = String.class)})})
@NamedNativeQuery(name = "DeviceOnboardStatusAssignee.getDeviceOnboardStatusAssignees", query = "SELECT dosa.id, dosa.type, dosa.email, dosa.device_onboard_status_id FROM device_onboard_status_assignee dosa" + " WHERE dosa.device_onboard_status_id = ?1 ", resultSetMapping = "deviceonboardassigneemapping")
@Entity
public class DeviceOnboardStatusAssignee {
    @Id
    private String id;
    private String type;
    private String email;
    @ManyToOne
    DeviceOnboardStatus device_onboard_status;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DeviceOnboardStatusAssignee() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DeviceOnboardStatusAssignee(final String id, final String type, final String email, final DeviceOnboardStatus device_onboard_status) {
        this.id = id;
        this.type = type;
        this.email = email;
        this.device_onboard_status = device_onboard_status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DeviceOnboardStatus getDevice_onboard_status() {
        return this.device_onboard_status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDevice_onboard_status(final DeviceOnboardStatus device_onboard_status) {
        this.device_onboard_status = device_onboard_status;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DeviceOnboardStatusAssignee)) return false;
        final DeviceOnboardStatusAssignee other = (DeviceOnboardStatusAssignee) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$device_onboard_status = this.getDevice_onboard_status();
        final java.lang.Object other$device_onboard_status = other.getDevice_onboard_status();
        if (this$device_onboard_status == null ? other$device_onboard_status != null : !this$device_onboard_status.equals(other$device_onboard_status)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DeviceOnboardStatusAssignee;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $device_onboard_status = this.getDevice_onboard_status();
        result = result * PRIME + ($device_onboard_status == null ? 43 : $device_onboard_status.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "DeviceOnboardStatusAssignee(id=" + this.getId() + ", type=" + this.getType() + ", email=" + this.getEmail() + ", device_onboard_status=" + this.getDevice_onboard_status() + ")";
    }
}
