// Generated by delombok at Wed May 13 12:28:17 IST 2026
package io.sclera.models;

import io.sclera.dto.ManagedSoftwareDTO;
import io.sclera.dto.ManagedSoftwareUsersDTO;
import javax.persistence.*;
import java.math.BigInteger;

@SqlResultSetMapping(name = "ManagedSoftwareMapping", classes = {@ConstructorResult(targetClass = ManagedSoftwareDTO.class, columns = {@ColumnResult(name = "id", type = String.class), @ColumnResult(name = "name", type = String.class), @ColumnResult(name = "applicationName", type = String.class), @ColumnResult(name = "applicationType", type = String.class), @ColumnResult(name = "url", type = String.class), @ColumnResult(name = "vendor", type = String.class), @ColumnResult(name = "subscriptionId", type = String.class), @ColumnResult(name = "subscriptionType", type = String.class), @ColumnResult(name = "unitPrice", type = Double.class), @ColumnResult(name = "currency", type = String.class), @ColumnResult(name = "subscriptionStartDate", type = BigInteger.class), @ColumnResult(name = "subscriptionEndDate", type = BigInteger.class), @ColumnResult(name = "status", type = String.class), @ColumnResult(name = "applicationId", type = String.class)})})
@NamedNativeQuery(name = "ManagedSoftware.getAllManagedSoftwares", query = "SELECT " + "ms.id, ms.name, ms.application_name as applicationName, ms.application_type as applicationType, ms.url, " + "ms.vendor, ms.subscription_id as subscriptionId, ms.subscription_type as subscriptionType, ms.unit_price as unitPrice, ms.currency, " + "ms.subscription_start_date as subscriptionStartDate, ms.subscription_end_date as subscriptionEndDate, ms.status,  ms.application_id as applicationId " + "FROM managed_software ms " + "WHERE ( " + "  (?1 = \'all\') " + "  OR (?1 = \'active\' AND ms.status = \'active\') " + "  OR (?1 = \'expired\' AND ms.status = \'expired\') " + "  OR (?1 = \'others\' AND ms.status NOT IN (\'active\',\'expired\')) " + ") " + "AND (?2 = \'null\' OR CONCAT_WS(\'\', ms.name, ms.application_name, ms.vendor, ms.subscription_type) LIKE CONCAT(\'%\', ?2, \'%\')) " + "LIMIT ?4 OFFSET ?3 ", resultSetMapping = "ManagedSoftwareMapping")
@NamedNativeQuery(name = "ManagedSoftware.getManagedSoftwareById", query = "SELECT " + "ms.id, ms.name, ms.application_name as applicationName, ms.application_type as applicationType, ms.url, " + "ms.vendor, ms.subscription_id as subscriptionId, ms.subscription_type as subscriptionType, ms.unit_price as unitPrice, ms.currency, " + "ms.subscription_start_date as subscriptionStartDate, ms.subscription_end_date as subscriptionEndDate, ms.status, ms.application_id as applicationId " + "FROM managed_software ms " + "WHERE ms.id = ?1", resultSetMapping = "ManagedSoftwareMapping")
@NamedNativeQuery(name = "ManagedSoftware.getManagedSoftwareByIdList", query = "SELECT " + "ms.id, ms.name, ms.application_name as applicationName, ms.application_type as applicationType, ms.url, " + "ms.vendor, ms.subscription_id as subscriptionId, ms.subscription_type as subscriptionType, ms.unit_price as unitPrice, ms.currency, " + "ms.subscription_start_date as subscriptionStartDate, ms.subscription_end_date as subscriptionEndDate, ms.status, ms.application_id as applicationId " + "FROM managed_software ms " + "WHERE ms.id IN ?1 " + "ORDER BY FIELD(ms.id, ?1)", resultSetMapping = "ManagedSoftwareMapping")
@SqlResultSetMapping(name = "ManagedSoftwareUsersMapping", classes = {@ConstructorResult(targetClass = ManagedSoftwareUsersDTO.class, columns = {@ColumnResult(name = "username", type = String.class), @ColumnResult(name = "userUUID", type = String.class), @ColumnResult(name = "accountType", type = String.class), @ColumnResult(name = "email", type = String.class), @ColumnResult(name = "riskStatus", type = Integer.class), @ColumnResult(name = "deviceName", type = String.class), @ColumnResult(name = "model", type = String.class), @ColumnResult(name = "osType", type = String.class)})})
@NamedNativeQuery(name = "ManagedSoftware.getManagedSoftwareUsers", query = "SELECT ds.username, ds.user_uuid as userUUID, ds.account_type as accountType, ds.email, dia.risk_status as riskStatus, ds.device_name as deviceName, ds.model, ds.os_type as osType " + "FROM managed_software ms " + "JOIN device_installed_apps dia ON ms.id = dia.managed_software_id " + "JOIN device_specification ds ON dia.device_specification_id = ds.id " + "WHERE ms.id = ?1", resultSetMapping = "ManagedSoftwareUsersMapping")
@Entity
@Table(name = "managed_software")
public class ManagedSoftware {
    @Id
    private String id;
    private String name;
    private String applicationName;
    private String applicationType;
    private String url;
    private String vendor;
    private String subscriptionId;
    @Column(name = "subscription_type")
    private String subscriptionType;
    @Column(name = "unit_price")
    private double unitPrice;
    private String currency;
    @Column(name = "subscription_start_date")
    private BigInteger subscriptionStartDate;
    @Column(name = "subscription_end_date")
    private BigInteger subscriptionEndDate;
    private String status;
    @Column(name = "application_id")
    private String applicationId;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ManagedSoftwareBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String name;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String applicationName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String applicationType;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String url;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String vendor;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String subscriptionId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String subscriptionType;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private double unitPrice;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String currency;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigInteger subscriptionStartDate;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigInteger subscriptionEndDate;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String applicationId;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ManagedSoftwareBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware.ManagedSoftwareBuilder id(final String id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware.ManagedSoftwareBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware.ManagedSoftwareBuilder applicationName(final String applicationName) {
            this.applicationName = applicationName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware.ManagedSoftwareBuilder applicationType(final String applicationType) {
            this.applicationType = applicationType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware.ManagedSoftwareBuilder url(final String url) {
            this.url = url;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware.ManagedSoftwareBuilder vendor(final String vendor) {
            this.vendor = vendor;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware.ManagedSoftwareBuilder subscriptionId(final String subscriptionId) {
            this.subscriptionId = subscriptionId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware.ManagedSoftwareBuilder subscriptionType(final String subscriptionType) {
            this.subscriptionType = subscriptionType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware.ManagedSoftwareBuilder unitPrice(final double unitPrice) {
            this.unitPrice = unitPrice;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware.ManagedSoftwareBuilder currency(final String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware.ManagedSoftwareBuilder subscriptionStartDate(final BigInteger subscriptionStartDate) {
            this.subscriptionStartDate = subscriptionStartDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware.ManagedSoftwareBuilder subscriptionEndDate(final BigInteger subscriptionEndDate) {
            this.subscriptionEndDate = subscriptionEndDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware.ManagedSoftwareBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware.ManagedSoftwareBuilder applicationId(final String applicationId) {
            this.applicationId = applicationId;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ManagedSoftware build() {
            return new ManagedSoftware(this.id, this.name, this.applicationName, this.applicationType, this.url, this.vendor, this.subscriptionId, this.subscriptionType, this.unitPrice, this.currency, this.subscriptionStartDate, this.subscriptionEndDate, this.status, this.applicationId);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ManagedSoftware.ManagedSoftwareBuilder(id=" + this.id + ", name=" + this.name + ", applicationName=" + this.applicationName + ", applicationType=" + this.applicationType + ", url=" + this.url + ", vendor=" + this.vendor + ", subscriptionId=" + this.subscriptionId + ", subscriptionType=" + this.subscriptionType + ", unitPrice=" + this.unitPrice + ", currency=" + this.currency + ", subscriptionStartDate=" + this.subscriptionStartDate + ", subscriptionEndDate=" + this.subscriptionEndDate + ", status=" + this.status + ", applicationId=" + this.applicationId + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static ManagedSoftware.ManagedSoftwareBuilder builder() {
        return new ManagedSoftware.ManagedSoftwareBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getApplicationName() {
        return this.applicationName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getApplicationType() {
        return this.applicationType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUrl() {
        return this.url;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVendor() {
        return this.vendor;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSubscriptionId() {
        return this.subscriptionId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSubscriptionType() {
        return this.subscriptionType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public double getUnitPrice() {
        return this.unitPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCurrency() {
        return this.currency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigInteger getSubscriptionStartDate() {
        return this.subscriptionStartDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigInteger getSubscriptionEndDate() {
        return this.subscriptionEndDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getApplicationId() {
        return this.applicationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setApplicationName(final String applicationName) {
        this.applicationName = applicationName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setApplicationType(final String applicationType) {
        this.applicationType = applicationType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUrl(final String url) {
        this.url = url;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVendor(final String vendor) {
        this.vendor = vendor;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSubscriptionId(final String subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSubscriptionType(final String subscriptionType) {
        this.subscriptionType = subscriptionType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUnitPrice(final double unitPrice) {
        this.unitPrice = unitPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCurrency(final String currency) {
        this.currency = currency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSubscriptionStartDate(final BigInteger subscriptionStartDate) {
        this.subscriptionStartDate = subscriptionStartDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSubscriptionEndDate(final BigInteger subscriptionEndDate) {
        this.subscriptionEndDate = subscriptionEndDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setApplicationId(final String applicationId) {
        this.applicationId = applicationId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ManagedSoftware)) return false;
        final ManagedSoftware other = (ManagedSoftware) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (java.lang.Double.compare(this.getUnitPrice(), other.getUnitPrice()) != 0) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$applicationName = this.getApplicationName();
        final java.lang.Object other$applicationName = other.getApplicationName();
        if (this$applicationName == null ? other$applicationName != null : !this$applicationName.equals(other$applicationName)) return false;
        final java.lang.Object this$applicationType = this.getApplicationType();
        final java.lang.Object other$applicationType = other.getApplicationType();
        if (this$applicationType == null ? other$applicationType != null : !this$applicationType.equals(other$applicationType)) return false;
        final java.lang.Object this$url = this.getUrl();
        final java.lang.Object other$url = other.getUrl();
        if (this$url == null ? other$url != null : !this$url.equals(other$url)) return false;
        final java.lang.Object this$vendor = this.getVendor();
        final java.lang.Object other$vendor = other.getVendor();
        if (this$vendor == null ? other$vendor != null : !this$vendor.equals(other$vendor)) return false;
        final java.lang.Object this$subscriptionId = this.getSubscriptionId();
        final java.lang.Object other$subscriptionId = other.getSubscriptionId();
        if (this$subscriptionId == null ? other$subscriptionId != null : !this$subscriptionId.equals(other$subscriptionId)) return false;
        final java.lang.Object this$subscriptionType = this.getSubscriptionType();
        final java.lang.Object other$subscriptionType = other.getSubscriptionType();
        if (this$subscriptionType == null ? other$subscriptionType != null : !this$subscriptionType.equals(other$subscriptionType)) return false;
        final java.lang.Object this$currency = this.getCurrency();
        final java.lang.Object other$currency = other.getCurrency();
        if (this$currency == null ? other$currency != null : !this$currency.equals(other$currency)) return false;
        final java.lang.Object this$subscriptionStartDate = this.getSubscriptionStartDate();
        final java.lang.Object other$subscriptionStartDate = other.getSubscriptionStartDate();
        if (this$subscriptionStartDate == null ? other$subscriptionStartDate != null : !this$subscriptionStartDate.equals(other$subscriptionStartDate)) return false;
        final java.lang.Object this$subscriptionEndDate = this.getSubscriptionEndDate();
        final java.lang.Object other$subscriptionEndDate = other.getSubscriptionEndDate();
        if (this$subscriptionEndDate == null ? other$subscriptionEndDate != null : !this$subscriptionEndDate.equals(other$subscriptionEndDate)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$applicationId = this.getApplicationId();
        final java.lang.Object other$applicationId = other.getApplicationId();
        if (this$applicationId == null ? other$applicationId != null : !this$applicationId.equals(other$applicationId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ManagedSoftware;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $unitPrice = java.lang.Double.doubleToLongBits(this.getUnitPrice());
        result = result * PRIME + (int) ($unitPrice >>> 32 ^ $unitPrice);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $applicationName = this.getApplicationName();
        result = result * PRIME + ($applicationName == null ? 43 : $applicationName.hashCode());
        final java.lang.Object $applicationType = this.getApplicationType();
        result = result * PRIME + ($applicationType == null ? 43 : $applicationType.hashCode());
        final java.lang.Object $url = this.getUrl();
        result = result * PRIME + ($url == null ? 43 : $url.hashCode());
        final java.lang.Object $vendor = this.getVendor();
        result = result * PRIME + ($vendor == null ? 43 : $vendor.hashCode());
        final java.lang.Object $subscriptionId = this.getSubscriptionId();
        result = result * PRIME + ($subscriptionId == null ? 43 : $subscriptionId.hashCode());
        final java.lang.Object $subscriptionType = this.getSubscriptionType();
        result = result * PRIME + ($subscriptionType == null ? 43 : $subscriptionType.hashCode());
        final java.lang.Object $currency = this.getCurrency();
        result = result * PRIME + ($currency == null ? 43 : $currency.hashCode());
        final java.lang.Object $subscriptionStartDate = this.getSubscriptionStartDate();
        result = result * PRIME + ($subscriptionStartDate == null ? 43 : $subscriptionStartDate.hashCode());
        final java.lang.Object $subscriptionEndDate = this.getSubscriptionEndDate();
        result = result * PRIME + ($subscriptionEndDate == null ? 43 : $subscriptionEndDate.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $applicationId = this.getApplicationId();
        result = result * PRIME + ($applicationId == null ? 43 : $applicationId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ManagedSoftware(id=" + this.getId() + ", name=" + this.getName() + ", applicationName=" + this.getApplicationName() + ", applicationType=" + this.getApplicationType() + ", url=" + this.getUrl() + ", vendor=" + this.getVendor() + ", subscriptionId=" + this.getSubscriptionId() + ", subscriptionType=" + this.getSubscriptionType() + ", unitPrice=" + this.getUnitPrice() + ", currency=" + this.getCurrency() + ", subscriptionStartDate=" + this.getSubscriptionStartDate() + ", subscriptionEndDate=" + this.getSubscriptionEndDate() + ", status=" + this.getStatus() + ", applicationId=" + this.getApplicationId() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ManagedSoftware() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ManagedSoftware(final String id, final String name, final String applicationName, final String applicationType, final String url, final String vendor, final String subscriptionId, final String subscriptionType, final double unitPrice, final String currency, final BigInteger subscriptionStartDate, final BigInteger subscriptionEndDate, final String status, final String applicationId) {
        this.id = id;
        this.name = name;
        this.applicationName = applicationName;
        this.applicationType = applicationType;
        this.url = url;
        this.vendor = vendor;
        this.subscriptionId = subscriptionId;
        this.subscriptionType = subscriptionType;
        this.unitPrice = unitPrice;
        this.currency = currency;
        this.subscriptionStartDate = subscriptionStartDate;
        this.subscriptionEndDate = subscriptionEndDate;
        this.status = status;
        this.applicationId = applicationId;
    }
}
