// Generated by delombok at Wed May 13 12:28:22 IST 2026
package io.sclera.models;

import io.sclera.dto.NfcDTO;
import javax.persistence.*;
import java.math.BigInteger;

@SqlResultSetMapping(name = "nfcdetails", classes = {@ConstructorResult(targetClass = NfcDTO.class, columns = {@ColumnResult(name = "id", type = String.class), @ColumnResult(name = "device_id", type = String.class), @ColumnResult(name = "location_id", type = String.class)})})
@NamedNativeQuery(name = "Nfc.getNfcsByDeviceIds", query = "(SELECT nfc.id, nfc.device_id, nfc.location_id FROM nfc WHERE nfc.device_id IN (?1))\n" + "UNION ALL \n" + "(SELECT cnfc.id, cnfc.device_id, cnfc.location_id FROM client_nfc cnfc WHERE cnfc.device_id IN (?1))\n", resultSetMapping = "nfcdetails")
@NamedNativeQuery(name = "Nfc.getNfcsByLocationIds", query = "(SELECT nfc.id, nfc.device_id, nfc.location_id FROM nfc WHERE nfc.location_id IN ?1)\n" + "UNION ALL \n" + "(SELECT cnfc.id, cnfc.device_id, cnfc.location_id FROM client_nfc cnfc WHERE cnfc.location_id IN ?1)\n", resultSetMapping = "nfcdetails")
@Entity
public class Nfc {
    @Id
    private String id;
    private String createdBy;
    private BigInteger creationTime;
    private String uuid;
    private String vdmsId;
    @ManyToOne
    private Device device;
    @ManyToOne
    private Location location;
    private Boolean isDeleted;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Nfc(final String id, final String createdBy, final BigInteger creationTime, final String uuid, final String vdmsId, final Device device, final Location location, final Boolean isDeleted) {
        this.id = id;
        this.createdBy = createdBy;
        this.creationTime = creationTime;
        this.uuid = uuid;
        this.vdmsId = vdmsId;
        this.device = device;
        this.location = location;
        this.isDeleted = isDeleted;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Nfc() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigInteger getCreationTime() {
        return this.creationTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUuid() {
        return this.uuid;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVdmsId() {
        return this.vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Device getDevice() {
        return this.device;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Location getLocation() {
        return this.location;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedBy(final String createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreationTime(final BigInteger creationTime) {
        this.creationTime = creationTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUuid(final String uuid) {
        this.uuid = uuid;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVdmsId(final String vdmsId) {
        this.vdmsId = vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDevice(final Device device) {
        this.device = device;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLocation(final Location location) {
        this.location = location;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsDeleted(final Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Nfc)) return false;
        final Nfc other = (Nfc) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$isDeleted = this.getIsDeleted();
        final java.lang.Object other$isDeleted = other.getIsDeleted();
        if (this$isDeleted == null ? other$isDeleted != null : !this$isDeleted.equals(other$isDeleted)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$createdBy = this.getCreatedBy();
        final java.lang.Object other$createdBy = other.getCreatedBy();
        if (this$createdBy == null ? other$createdBy != null : !this$createdBy.equals(other$createdBy)) return false;
        final java.lang.Object this$creationTime = this.getCreationTime();
        final java.lang.Object other$creationTime = other.getCreationTime();
        if (this$creationTime == null ? other$creationTime != null : !this$creationTime.equals(other$creationTime)) return false;
        final java.lang.Object this$uuid = this.getUuid();
        final java.lang.Object other$uuid = other.getUuid();
        if (this$uuid == null ? other$uuid != null : !this$uuid.equals(other$uuid)) return false;
        final java.lang.Object this$vdmsId = this.getVdmsId();
        final java.lang.Object other$vdmsId = other.getVdmsId();
        if (this$vdmsId == null ? other$vdmsId != null : !this$vdmsId.equals(other$vdmsId)) return false;
        final java.lang.Object this$device = this.getDevice();
        final java.lang.Object other$device = other.getDevice();
        if (this$device == null ? other$device != null : !this$device.equals(other$device)) return false;
        final java.lang.Object this$location = this.getLocation();
        final java.lang.Object other$location = other.getLocation();
        if (this$location == null ? other$location != null : !this$location.equals(other$location)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Nfc;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $isDeleted = this.getIsDeleted();
        result = result * PRIME + ($isDeleted == null ? 43 : $isDeleted.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $createdBy = this.getCreatedBy();
        result = result * PRIME + ($createdBy == null ? 43 : $createdBy.hashCode());
        final java.lang.Object $creationTime = this.getCreationTime();
        result = result * PRIME + ($creationTime == null ? 43 : $creationTime.hashCode());
        final java.lang.Object $uuid = this.getUuid();
        result = result * PRIME + ($uuid == null ? 43 : $uuid.hashCode());
        final java.lang.Object $vdmsId = this.getVdmsId();
        result = result * PRIME + ($vdmsId == null ? 43 : $vdmsId.hashCode());
        final java.lang.Object $device = this.getDevice();
        result = result * PRIME + ($device == null ? 43 : $device.hashCode());
        final java.lang.Object $location = this.getLocation();
        result = result * PRIME + ($location == null ? 43 : $location.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Nfc(id=" + this.getId() + ", createdBy=" + this.getCreatedBy() + ", creationTime=" + this.getCreationTime() + ", uuid=" + this.getUuid() + ", vdmsId=" + this.getVdmsId() + ", device=" + this.getDevice() + ", location=" + this.getLocation() + ", isDeleted=" + this.getIsDeleted() + ")";
    }
}
