// Generated by delombok at Wed May 13 12:28:28 IST 2026
package io.sclera.models;

import io.sclera.dto.QrCodeDTO;
import javax.persistence.*;
import java.math.BigInteger;

@SqlResultSetMapping(name = "qrcodedetails", classes = {@ConstructorResult(targetClass = QrCodeDTO.class, columns = {@ColumnResult(name = "id", type = String.class), @ColumnResult(name = "device_id", type = String.class), @ColumnResult(name = "location_id", type = String.class), @ColumnResult(name = "updated_by", type = String.class), @ColumnResult(name = "updated_time", type = String.class)})})
@NamedNativeQuery(name = "QrCode.getQrCodesByDeviceIds", query = "(SELECT qc.id, qc.device_id, qc.location_id, qc.updated_by, qc.updated_time FROM qr_code qc WHERE qc.device_id IN (?1))\n" + "UNION ALL \n" + "(SELECT cqc.id, cqc.device_id, cqc.location_id, cqc.updated_by, cqc.updated_at as updated_time FROM client_qr_code cqc WHERE cqc.device_id IN (?1))\n", resultSetMapping = "qrcodedetails")
@NamedNativeQuery(name = "QrCode.getQrCodesByLocationIds", query = "(SELECT qc.id, qc.device_id, qc.location_id, qc.updated_by, qc.updated_time FROM qr_code qc WHERE qc.location_id IN ?1)\n" + "UNION ALL \n" + "(SELECT cqc.id, cqc.device_id, cqc.location_id, cqc.updated_by, cqc.updated_at as updated_time FROM client_qr_code cqc WHERE cqc.location_id IN ?1)\n", resultSetMapping = "qrcodedetails")
@NamedNativeQuery(name = "QrCode.getQrCodeDetailsByIds", query = "(SELECT qc.id, qc.device_id, qc.location_id, qc.updated_by, qc.updated_time FROM qr_code qc WHERE qc.id IN ?1)\n", resultSetMapping = "qrcodedetails")
@NamedNativeQuery(name = "QrCode.getClientQrCodeDetailsByIds", query = "(SELECT cqc.id, cqc.device_id, cqc.location_id, cqc.updated_by, cqc.updated_at as updated_time FROM client_qr_code cqc WHERE cqc.id IN ?1)", resultSetMapping = "qrcodedetails")
@Entity
public class QrCode {
    @Id
    private String id;
    private String imageUrl;
    private String vdmsId;
    private String createdBy;
    private BigInteger creationTime;
    private String batchId;
    private String qrCodeLink;
    private String updatedTime;
    private String updatedBy;
    @ManyToOne
    private Device device;
    @ManyToOne
    private Location location;
    private Boolean isDeleted;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVdmsId() {
        return this.vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigInteger getCreationTime() {
        return this.creationTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBatchId() {
        return this.batchId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getQrCodeLink() {
        return this.qrCodeLink;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUpdatedTime() {
        return this.updatedTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Device getDevice() {
        return this.device;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Location getLocation() {
        return this.location;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVdmsId(final String vdmsId) {
        this.vdmsId = vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedBy(final String createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreationTime(final BigInteger creationTime) {
        this.creationTime = creationTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBatchId(final String batchId) {
        this.batchId = batchId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setQrCodeLink(final String qrCodeLink) {
        this.qrCodeLink = qrCodeLink;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedTime(final String updatedTime) {
        this.updatedTime = updatedTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedBy(final String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDevice(final Device device) {
        this.device = device;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLocation(final Location location) {
        this.location = location;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsDeleted(final Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof QrCode)) return false;
        final QrCode other = (QrCode) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$isDeleted = this.getIsDeleted();
        final java.lang.Object other$isDeleted = other.getIsDeleted();
        if (this$isDeleted == null ? other$isDeleted != null : !this$isDeleted.equals(other$isDeleted)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$imageUrl = this.getImageUrl();
        final java.lang.Object other$imageUrl = other.getImageUrl();
        if (this$imageUrl == null ? other$imageUrl != null : !this$imageUrl.equals(other$imageUrl)) return false;
        final java.lang.Object this$vdmsId = this.getVdmsId();
        final java.lang.Object other$vdmsId = other.getVdmsId();
        if (this$vdmsId == null ? other$vdmsId != null : !this$vdmsId.equals(other$vdmsId)) return false;
        final java.lang.Object this$createdBy = this.getCreatedBy();
        final java.lang.Object other$createdBy = other.getCreatedBy();
        if (this$createdBy == null ? other$createdBy != null : !this$createdBy.equals(other$createdBy)) return false;
        final java.lang.Object this$creationTime = this.getCreationTime();
        final java.lang.Object other$creationTime = other.getCreationTime();
        if (this$creationTime == null ? other$creationTime != null : !this$creationTime.equals(other$creationTime)) return false;
        final java.lang.Object this$batchId = this.getBatchId();
        final java.lang.Object other$batchId = other.getBatchId();
        if (this$batchId == null ? other$batchId != null : !this$batchId.equals(other$batchId)) return false;
        final java.lang.Object this$qrCodeLink = this.getQrCodeLink();
        final java.lang.Object other$qrCodeLink = other.getQrCodeLink();
        if (this$qrCodeLink == null ? other$qrCodeLink != null : !this$qrCodeLink.equals(other$qrCodeLink)) return false;
        final java.lang.Object this$updatedTime = this.getUpdatedTime();
        final java.lang.Object other$updatedTime = other.getUpdatedTime();
        if (this$updatedTime == null ? other$updatedTime != null : !this$updatedTime.equals(other$updatedTime)) return false;
        final java.lang.Object this$updatedBy = this.getUpdatedBy();
        final java.lang.Object other$updatedBy = other.getUpdatedBy();
        if (this$updatedBy == null ? other$updatedBy != null : !this$updatedBy.equals(other$updatedBy)) return false;
        final java.lang.Object this$device = this.getDevice();
        final java.lang.Object other$device = other.getDevice();
        if (this$device == null ? other$device != null : !this$device.equals(other$device)) return false;
        final java.lang.Object this$location = this.getLocation();
        final java.lang.Object other$location = other.getLocation();
        if (this$location == null ? other$location != null : !this$location.equals(other$location)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof QrCode;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $isDeleted = this.getIsDeleted();
        result = result * PRIME + ($isDeleted == null ? 43 : $isDeleted.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $imageUrl = this.getImageUrl();
        result = result * PRIME + ($imageUrl == null ? 43 : $imageUrl.hashCode());
        final java.lang.Object $vdmsId = this.getVdmsId();
        result = result * PRIME + ($vdmsId == null ? 43 : $vdmsId.hashCode());
        final java.lang.Object $createdBy = this.getCreatedBy();
        result = result * PRIME + ($createdBy == null ? 43 : $createdBy.hashCode());
        final java.lang.Object $creationTime = this.getCreationTime();
        result = result * PRIME + ($creationTime == null ? 43 : $creationTime.hashCode());
        final java.lang.Object $batchId = this.getBatchId();
        result = result * PRIME + ($batchId == null ? 43 : $batchId.hashCode());
        final java.lang.Object $qrCodeLink = this.getQrCodeLink();
        result = result * PRIME + ($qrCodeLink == null ? 43 : $qrCodeLink.hashCode());
        final java.lang.Object $updatedTime = this.getUpdatedTime();
        result = result * PRIME + ($updatedTime == null ? 43 : $updatedTime.hashCode());
        final java.lang.Object $updatedBy = this.getUpdatedBy();
        result = result * PRIME + ($updatedBy == null ? 43 : $updatedBy.hashCode());
        final java.lang.Object $device = this.getDevice();
        result = result * PRIME + ($device == null ? 43 : $device.hashCode());
        final java.lang.Object $location = this.getLocation();
        result = result * PRIME + ($location == null ? 43 : $location.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "QrCode(id=" + this.getId() + ", imageUrl=" + this.getImageUrl() + ", vdmsId=" + this.getVdmsId() + ", createdBy=" + this.getCreatedBy() + ", creationTime=" + this.getCreationTime() + ", batchId=" + this.getBatchId() + ", qrCodeLink=" + this.getQrCodeLink() + ", updatedTime=" + this.getUpdatedTime() + ", updatedBy=" + this.getUpdatedBy() + ", device=" + this.getDevice() + ", location=" + this.getLocation() + ", isDeleted=" + this.getIsDeleted() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public QrCode() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public QrCode(final String id, final String imageUrl, final String vdmsId, final String createdBy, final BigInteger creationTime, final String batchId, final String qrCodeLink, final String updatedTime, final String updatedBy, final Device device, final Location location, final Boolean isDeleted) {
        this.id = id;
        this.imageUrl = imageUrl;
        this.vdmsId = vdmsId;
        this.createdBy = createdBy;
        this.creationTime = creationTime;
        this.batchId = batchId;
        this.qrCodeLink = qrCodeLink;
        this.updatedTime = updatedTime;
        this.updatedBy = updatedBy;
        this.device = device;
        this.location = location;
        this.isDeleted = isDeleted;
    }
}
