// Generated by delombok-style port from sclera-cloud-vdms QrCodeTemplate.
// Changes vs. reference:
//   - package: io.sclera.models (plural)
//   - Customer_Organisation @ManyToOne replaced with plain String customerOrgId column
//   - All named-native SQL converted to PostgreSQL (LIMIT/OFFSET; no backticks)
//   - jakarta.persistence.* (Jakarta EE 10, Spring Boot 3+)
package io.sclera.models;

import io.sclera.dto.QrCodeTemplateDTO;
import jakarta.persistence.*;
import java.math.BigInteger;

@Entity
@Table(name = "qr_code_template")

@SqlResultSetMapping(
        name = "QrCodeTemplateMapping",
        classes = {
                @ConstructorResult(
                        targetClass = QrCodeTemplateDTO.class,
                        columns = {
                                @ColumnResult(name = "id",                type = String.class),
                                @ColumnResult(name = "name",              type = String.class),
                                @ColumnResult(name = "qrCodeTemplateUrl", type = String.class),
                                @ColumnResult(name = "qrCodeLogoUrl",     type = String.class),
                                @ColumnResult(name = "customerOrgId",     type = String.class),
                                @ColumnResult(name = "qrTemplateJson",    type = String.class),
                                @ColumnResult(name = "inUse",             type = Integer.class),
                                @ColumnResult(name = "isDefault",         type = Integer.class)
                        }
                )
        }
)

// getAllQrCodeTemplateByOrgId — paginated, filtered by name and org; Postgres LIMIT/OFFSET.
// Name MUST equal the repository method (QrCodeTemplate.getAllQrCodeTemplateByOrgId) so Spring
// Data binds it as a named native query instead of trying to derive it from the method name.
@NamedNativeQuery(
        name = "QrCodeTemplate.getAllQrCodeTemplateByOrgId",
        query = "SELECT id, name, qr_code_template_url AS qrCodeTemplateUrl, qr_code_logo_url AS qrCodeLogoUrl, " +
                "customer_org_id AS customerOrgId, qr_template_json AS qrTemplateJson, in_use AS inUse, is_default AS isDefault " +
                "FROM qr_code_template " +
                "WHERE (?1 = 'all' OR CONCAT_WS('', name) LIKE CONCAT('%', ?1, '%')) " +
                "AND customer_org_id IS NOT NULL AND customer_org_id = ?2 " +
                "LIMIT ?4 OFFSET ?3",
        resultSetMapping = "QrCodeTemplateMapping"
)

// getInUseUrlByOrgId — templates currently in use for an org
@NamedNativeQuery(
        name = "QrCodeTemplate.getInUseUrlByOrgId",
        query = "SELECT id, name, qr_code_template_url AS qrCodeTemplateUrl, qr_code_logo_url AS qrCodeLogoUrl, " +
                "customer_org_id AS customerOrgId, qr_template_json AS qrTemplateJson, in_use AS inUse, is_default AS isDefault " +
                "FROM qr_code_template " +
                "WHERE in_use = ?1 AND customer_org_id = ?2",
        resultSetMapping = "QrCodeTemplateMapping"
)

// getDefaultTemplate — single default template (is_default = 1)
@NamedNativeQuery(
        name = "QrCodeTemplate.getDefaultTemplate",
        query = "SELECT id, name, qr_code_template_url AS qrCodeTemplateUrl, qr_code_logo_url AS qrCodeLogoUrl, " +
                "customer_org_id AS customerOrgId, qr_template_json AS qrTemplateJson, in_use AS inUse, is_default AS isDefault " +
                "FROM qr_code_template " +
                "WHERE is_default = 1",
        resultSetMapping = "QrCodeTemplateMapping"
)

// getDataByIds — fetch a batch by PK list
@NamedNativeQuery(
        name = "QrCodeTemplate.getDataByIds",
        query = "SELECT id, name, qr_code_template_url AS qrCodeTemplateUrl, qr_code_logo_url AS qrCodeLogoUrl, " +
                "customer_org_id AS customerOrgId, qr_template_json AS qrTemplateJson, in_use AS inUse, is_default AS isDefault " +
                "FROM qr_code_template " +
                "WHERE id IN ?1",
        resultSetMapping = "QrCodeTemplateMapping"
)

public class QrCodeTemplate {

    @Id
    private String id;

    private String name;

    @Column(columnDefinition = "TEXT")
    private String qrTemplateJson;

    private String qrCodeTemplateUrl;

    private String qrCodeLogoUrl;

    /** Replaces @ManyToOne Customer_Organisation — device-asset has no Customer_Organisation entity. */
    private String customerOrgId;

    private BigInteger creationTimestamp;

    private String addedBy;

    private BigInteger updatedTimestamp;

    private String updatedBy;

    @Column(columnDefinition = "integer default 0")
    private Integer inUse;

    @Column(columnDefinition = "integer default 0")
    private Integer isDefault;

    // ── Getters ──────────────────────────────────────────────────────────────

    public String getId() { return id; }

    public String getName() { return name; }

    public String getQrTemplateJson() { return qrTemplateJson; }

    public String getQrCodeTemplateUrl() { return qrCodeTemplateUrl; }

    public String getQrCodeLogoUrl() { return qrCodeLogoUrl; }

    public String getCustomerOrgId() { return customerOrgId; }

    public BigInteger getCreationTimestamp() { return creationTimestamp; }

    public String getAddedBy() { return addedBy; }

    public BigInteger getUpdatedTimestamp() { return updatedTimestamp; }

    public String getUpdatedBy() { return updatedBy; }

    public Integer getInUse() { return inUse; }

    public Integer getIsDefault() { return isDefault; }

    // ── Setters ──────────────────────────────────────────────────────────────

    public void setId(String id) { this.id = id; }

    public void setName(String name) { this.name = name; }

    public void setQrTemplateJson(String qrTemplateJson) { this.qrTemplateJson = qrTemplateJson; }

    public void setQrCodeTemplateUrl(String qrCodeTemplateUrl) { this.qrCodeTemplateUrl = qrCodeTemplateUrl; }

    public void setQrCodeLogoUrl(String qrCodeLogoUrl) { this.qrCodeLogoUrl = qrCodeLogoUrl; }

    public void setCustomerOrgId(String customerOrgId) { this.customerOrgId = customerOrgId; }

    public void setCreationTimestamp(BigInteger creationTimestamp) { this.creationTimestamp = creationTimestamp; }

    public void setAddedBy(String addedBy) { this.addedBy = addedBy; }

    public void setUpdatedTimestamp(BigInteger updatedTimestamp) { this.updatedTimestamp = updatedTimestamp; }

    public void setUpdatedBy(String updatedBy) { this.updatedBy = updatedBy; }

    public void setInUse(Integer inUse) { this.inUse = inUse; }

    public void setIsDefault(Integer isDefault) { this.isDefault = isDefault; }
}
