// Generated by delombok at Wed May 13 12:28:50 IST 2026
package io.sclera.models;

import io.sclera.dto.TechnicianSkillDTO;
import javax.persistence.*;
import java.math.BigDecimal;

@SqlResultSetMapping(name = "technicianSkillMapping", classes = @ConstructorResult(targetClass = TechnicianSkillDTO.class, columns = {@ColumnResult(name = "id", type = String.class), @ColumnResult(name = "name", type = String.class), @ColumnResult(name = "type", type = String.class), @ColumnResult(name = "rating", type = BigDecimal.class), @ColumnResult(name = "ranking", type = Integer.class), @ColumnResult(name = "created_by", type = String.class), @ColumnResult(name = "created_at", type = Long.class), @ColumnResult(name = "technician_id", type = String.class)}))
@NamedNativeQuery(name = "TechnicianSkill.getAll", query = "SELECT id, name, type, rating, ranking, created_by, created_at, technician_id FROM technician_skill", resultSetMapping = "technicianSkillMapping")
@NamedNativeQuery(name = "TechnicianSkill.getById", query = "SELECT id, name, type, rating, ranking, created_by, created_at, technician_id FROM technician_skill WHERE id = ?1", resultSetMapping = "technicianSkillMapping")
@NamedNativeQuery(name = "TechnicianSkill.getByTechnicianId", query = "SELECT id, name, type, rating, ranking, created_by, created_at, technician_id FROM technician_skill WHERE technician_id = ?1", resultSetMapping = "technicianSkillMapping")
@Entity
public class TechnicianSkill {
    @Id
    private String id;
    private String name;
    private String type;
    @Column(precision = 2, scale = 1)
    private BigDecimal rating = BigDecimal.ZERO;
    private Integer ranking;
    @Column(name = "created_by")
    private String createdBy;
    @Column(name = "created_at")
    private Long createdAt;
    @ManyToOne
    @JoinColumn(name = "technician_id")
    private Technician technician;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRating(final BigDecimal rating) {
        this.rating = rating;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRanking(final Integer ranking) {
        this.ranking = ranking;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedBy(final String createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final Long createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTechnician(final Technician technician) {
        this.technician = technician;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getRating() {
        return this.rating;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getRanking() {
        return this.ranking;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Technician getTechnician() {
        return this.technician;
    }
}
