// Generated by delombok at Wed May 13 12:28:39 IST 2026
package io.sclera.models;

import io.sclera.dto.TechnicianAvailabilityDTO;
import javax.persistence.*;

@SqlResultSetMapping(name = "technicianAvailabilityMapping", classes = @ConstructorResult(targetClass = TechnicianAvailabilityDTO.class, columns = {@ColumnResult(name = "id", type = String.class), @ColumnResult(name = "start_date", type = Long.class), @ColumnResult(name = "end_date", type = Long.class), @ColumnResult(name = "start_time", type = String.class), @ColumnResult(name = "end_time", type = String.class), @ColumnResult(name = "is_all_day", type = Boolean.class), @ColumnResult(name = "frequency", type = String.class), @ColumnResult(name = "`condition`", type = String.class), @ColumnResult(name = "technician_id", type = String.class)}))
@NamedNativeQueries({
    @NamedNativeQuery(name = "TechnicianAvailability.getAllTechnicianAvailability", query = "SELECT id, start_date, end_date, start_time, end_time, is_all_day, frequency, `condition`, technician_id FROM technician_availability", resultSetMapping = "technicianAvailabilityMapping"),
    @NamedNativeQuery(name = "TechnicianAvailability.getTechnicianAvailabilityById", query = "SELECT id, start_date, end_date, start_time, end_time, is_all_day, frequency, `condition`, technician_id FROM technician_availability WHERE id = ?1", resultSetMapping = "technicianAvailabilityMapping"),
    @NamedNativeQuery(name = "TechnicianAvailability.getTechnicianAvailabilityInRange", query = "SELECT id, start_date, end_date, start_time, end_time, is_all_day, frequency, `condition`, technician_id FROM technician_availability WHERE technician_id = ?1 AND ((start_time >= ?2 AND start_time <= ?3) OR (end_time >= ?2 AND end_time <= ?3))", resultSetMapping = "technicianAvailabilityMapping"),
    @NamedNativeQuery(name = "TechnicianAvailability.createTechnicianAvailability", query = "INSERT INTO technician_availability (id, start_date, end_date, start_time, end_time, is_all_day, frequency, `condition`, technician_id) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)", resultClass = TechnicianAvailability.class),
    @NamedNativeQuery(name = "TechnicianAvailability.updateTechnicianAvailability", query = "UPDATE technician_availability SET start_date = ?2, end_date = ?3, start_time = ?4, end_time = ?5, is_all_day = ?6, frequency = ?7, `condition` = ?8, technician_id = ?9 WHERE id = ?1", resultClass = TechnicianAvailability.class),
    @NamedNativeQuery(name = "TechnicianAvailability.findExistingTechnicianAvailabilityByIds", query = "SELECT id FROM technician_availability WHERE id IN ?1", resultClass = TechnicianAvailability.class),
    @NamedNativeQuery(name = "TechnicianAvailability.deleteTechnicianAvailabilityByIds", query = "DELETE FROM technician_availability WHERE id IN ?1", resultClass = TechnicianAvailability.class),
    @NamedNativeQuery(name = "TechnicianAvailability.deleteTechnicianAvailabilityByTechnicianIds", query = "DELETE FROM technician_availability WHERE technician_id IN ?1", resultClass = TechnicianAvailability.class),
    @NamedNativeQuery(name = "TechnicianAvailability.deleteTechnicianAvailabilityById", query = "DELETE FROM technician_availability WHERE id = ?1", resultClass = TechnicianAvailability.class),
    @NamedNativeQuery(name = "TechnicianAvailability.upsertTechnicianAvailability", query = "INSERT INTO technician_availability (id, start_date, end_date, start_time, end_time, is_all_day, frequency, `condition`, technician_id) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9) ON DUPLICATE KEY UPDATE start_date = ?2, end_date = ?3, start_time = ?4, end_time = ?5, is_all_day = ?6, frequency = ?7, `condition` = ?8", resultClass = TechnicianAvailability.class)
})
@Entity
public class TechnicianAvailability {
    @Id
    private String id;
    private Long startDate;
    private Long endDate;
    @Column(columnDefinition = "varchar(16) default \'09:00\'")
    private String startTime = "09:00";
    @Column(columnDefinition = "varchar(16) default \'17:00\'")
    private String endTime = "17:00";
    @Column(columnDefinition = "boolean default false")
    private Boolean isAllDay = false;
    private String frequency;
    @Column(name = "`condition`")
    private String condition;
    @ManyToOne
    @JoinColumn(name = "technician_id")
    private Technician technician;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStartDate(final Long startDate) {
        this.startDate = startDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEndDate(final Long endDate) {
        this.endDate = endDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStartTime(final String startTime) {
        this.startTime = startTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEndTime(final String endTime) {
        this.endTime = endTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsAllDay(final Boolean isAllDay) {
        this.isAllDay = isAllDay;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFrequency(final String frequency) {
        this.frequency = frequency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCondition(final String condition) {
        this.condition = condition;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTechnician(final Technician technician) {
        this.technician = technician;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getStartDate() {
        return this.startDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getEndDate() {
        return this.endDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStartTime() {
        return this.startTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEndTime() {
        return this.endTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsAllDay() {
        return this.isAllDay;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFrequency() {
        return this.frequency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCondition() {
        return this.condition;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Technician getTechnician() {
        return this.technician;
    }
}
