// Generated by delombok at Wed May 13 12:27:09 IST 2026
package io.sclera.exception;

public class MaximoException extends RuntimeException {
    private String message;
    private Integer errorCode;
    private String path;

    public MaximoException(String message, Integer errorCode, String path) {
        super(message);
        this.message = message;
        this.errorCode = errorCode;
        this.path = path;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getErrorCode() {
        return this.errorCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPath() {
        return this.path;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setErrorCode(final Integer errorCode) {
        this.errorCode = errorCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPath(final String path) {
        this.path = path;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "MaximoException(message=" + this.getMessage() + ", errorCode=" + this.getErrorCode() + ", path=" + this.getPath() + ")";
    }
}
