server:
  port: 8089

spring:
  application:
    name: sclera-vdms-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/vdms}
    username: ${DB_USER:root}
    password: ${DB_PASS:mypass123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
