// Generated by delombok at Wed May 13 12:28:58 IST 2026
package io.sclera.service;

import com.fasterxml.uuid.Generators;
import io.sclera.Repository.AiCallLogHistoryRepository;
import io.sclera.Repository.AiCallLogRepository;
import io.sclera.Repository.CallFlowRuleConditionRepository;
import io.sclera.Repository.CallFlowRuleRepository;
import io.sclera.dto.*;
import io.sclera.dto.touchscreen.settings.VdmsDTO;
import io.sclera.integration.dto.ResponseDTO;
//import io.sclera.service.touchscreen.VdmsService;
import io.sclera.sockets.SocketService;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Schedulers;
import javax.servlet.http.HttpServletRequest;
import javax.transaction.Transactional;
import java.math.BigInteger;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

@Service
public class AiCallService {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(AiCallService.class);
    @Autowired
    AiCallLogRepository aiCallLogRepository;
    @Autowired
    DeviceService deviceService;
    @Autowired
    CallFlowRuleRepository callFlowRuleRepository;
    @Autowired
    CallFlowRuleConditionRepository callFlowRuleConditionRepository;
    @Autowired
    AiCallLogHistoryRepository aiCallLogHistoryRepository;
    @Autowired
    DockerService dockerService;
    @Autowired
    APICallService apiCallService;
//    @Autowired
//    VdmsService vdmsService;
    @Autowired
    TechnicianService technicianService;
    @Autowired
    SocketService socketService;
    @Autowired
    DeviceConditionsService deviceConditionsService;

    public String createCallLog(String deviceId, String issueType) {
        //TODO if deviceID is called multiple times
        BigInteger timestamp = BigInteger.valueOf(System.currentTimeMillis());
        String id = Generators.timeBasedGenerator().generate().toString();
        aiCallLogRepository.insertAiCallLog(id, timestamp, null, issueType, "Device is offline", "High", "ongoing", Boolean.FALSE, deviceId, null);
        String assigneeResult = this.getAssignee(deviceId);
        if (assigneeResult == null) {
            ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(5);
            scheduler.schedule(() -> {
                String aiCalllogid = aiCallLogRepository.getAiCallLogIdByDeviceId(deviceId);
                if (aiCalllogid != null) {
                    System.out.println("id:" + id);
                    aiCallLogRepository.upsertStatus(id, null, true, null, "no-response");
                    aiCallLogHistoryRepository.insertAiCallLogHistoryState(Generators.timeBasedGenerator().generate().toString(), BigInteger.valueOf(System.currentTimeMillis()), "Technician not available", null, id, "no-response");
                    deviceService.updateDeviceDndAndSystemDndStatus(deviceId, false);
                    log.info("Auto-completed call {} as no-response", id);
                }
            }, 30, TimeUnit.SECONDS);
        }
        log.info(assigneeResult);
        return "Call log created with ID: " + id + ". " + assigneeResult;
    }

    public List<AiCallLogDTO> getallcallstatus(String username, String vdmsid, Integer pageNo, Integer pageSize, String searchKey, Boolean isCompleted) {
        Integer offset = (Integer) (pageSize * (pageNo - 1));
        log.info("Inside getallcallstatus with pageNo: {}, pageSize: {}, searchKey: {}", pageNo, pageSize, searchKey);
        String isCompletedString = isCompleted ? "1" : "0";
        List<AiCallLogDTO> callLogsDTOS = aiCallLogRepository.getAllAiCallLog(pageSize, offset, searchKey, isCompletedString);
        log.info("Retrieved {} call logs", callLogsDTOS.size());
        for (AiCallLogDTO callLogDTO : callLogsDTOS) {
            if (callLogDTO != null) {
                List<AiCallLogHistoryDTO> aiCallLogHistoryDTOS = aiCallLogHistoryRepository.getAiCallLogHistoryByAiCallLogId(callLogDTO.getId());
                log.info("Retrieved {} history records for call log ID: {}", aiCallLogHistoryDTOS.size(), callLogDTO.getId());
                callLogDTO.setAiCallLogHistory(aiCallLogHistoryDTOS);
                CallStatusDTO callStatusDTO = aiCallLogRepository.getStatusInformation(callLogDTO.getDeviceId());
                log.info("Retrieved CallStatusDTO for device ID: {}", callLogDTO.getDeviceId());
                callLogDTO.setCallStatus(callStatusDTO);
                log.info("Setting CallStatusDT0 status {}", callLogDTO.getCallStatus());
                log.info("Generated CallStatusDTO: {} ", callStatusDTO.getDeviceName());
            }
        }
        return callLogsDTOS;
    }

    public Map<String, Integer> getCallStatusCount(String username, String vdmsid) {
        Integer countCompleted = aiCallLogRepository.getCallStatusCount(Boolean.TRUE);
        Integer countOngoing = aiCallLogRepository.getCallStatusCount(Boolean.FALSE);
        Map<String, Integer> callStatusCountMap = Map.of("completed", countCompleted, "ongoing", countOngoing);
        return callStatusCountMap;
    }

    public DeviceDTO getDeviceInfoFromDb(String deviceId) {
        DeviceDTO deviceDTO = deviceService.getDeviceInfoFromDb(deviceId);
        System.out.println("Device info is " + deviceDTO);
        return deviceDTO;
    }

    private JSONObject createDeviceRequestBody(DeviceDTO deviceDTO, String issueType) throws JSONException {
        if (issueType == null || issueType.isEmpty()) {
            issueType = aiCallLogRepository.getAiCallLogIssueTypeByDeviceId(deviceDTO.getId());
        }
        JSONObject deviceJson = new JSONObject();
        deviceJson.put("alarm", deviceDTO.getAlarm());
        deviceJson.put("user_data_name", deviceDTO.getUser_data_name());
        deviceJson.put("display_name", deviceDTO.getDisplay_name());
        deviceJson.put("ip_address", deviceDTO.getIp_address());
        deviceJson.put("mac_address", deviceDTO.getMac_address());
        deviceJson.put("last_seen_on", deviceDTO.getLast_seen_on());
        deviceJson.put("model", deviceDTO.getModel());
        deviceJson.put("user_data_model", deviceDTO.getUser_data_model());
        deviceJson.put("user_data_vendor", deviceDTO.getUser_data_vendor());
        deviceJson.put("vendor", deviceDTO.getVendor());
        deviceJson.put("warranty", deviceDTO.getWarranty());
        deviceJson.put("serial_number", deviceDTO.getSerial_number());
        deviceJson.put("docker_name", deviceDTO.getDocker_name());
        deviceJson.put("parent", deviceDTO.getParent());
        deviceJson.put("description", deviceDTO.getDescription());
        deviceJson.put("category", deviceDTO.getCategory());
        deviceJson.put("issue", issueType);
        JSONObject vdmsJson = new JSONObject();
        vdmsJson.put("vdms_id", deviceDTO.getDocker_vdms_id());
        vdmsJson.put("building_name", deviceDTO.getBuilding());
        vdmsJson.put("floor_name", deviceDTO.getFloor());
        vdmsJson.put("location_name", deviceDTO.getLocation());
        JSONObject requestBody = new JSONObject();
        requestBody.put("device", deviceJson);
        requestBody.put("vdms", vdmsJson);
        log.info(requestBody.toString(2));
        return requestBody;
    }

    public String getAssignee(String deviceId) {
        WebClient webClient = WebClient.create();
        List<TechnicianDTO> technicians = technicianService.getAvailableTechnicianCountryCodePhoneByDeviceId(deviceId);
        System.out.println("Technicians: " + technicians.size());
        String vdmsId = "VDMS400";
        String aiCallLogId = aiCallLogRepository.getAiCallLogIdByDeviceId(deviceId);
        List<JSONObject> requestBodies = new ArrayList<>();
        if (technicians == null || technicians.isEmpty()) {
            log.info("Technician list is empty for device: {}", deviceId);
            return null;
        }
        DeviceDTO deviceDTO = this.getDeviceInfoFromDb(deviceId);
        try {
            JSONObject requestBody = createDeviceRequestBody(deviceDTO, "");
            // Add the same request body for each technician
            for (int i = 0; i < technicians.size(); i++) {
                requestBodies.add(requestBody);
            }
        } catch (JSONException e) {
            throw new RuntimeException("Failed to create request body", e);
        }
        // Process technicians sequentially
        processTechniciansSequentially(requestBodies, webClient, vdmsId, aiCallLogId, technicians, deviceDTO, 0);
        return "Assigned " + technicians.size() + " technician(s) to device " + deviceId;
        // }
    }

    private void processTechniciansSequentially(List<JSONObject> requestBodies, WebClient webClient, String vdmsId, String aiCallLogId, List<TechnicianDTO> technicians, DeviceDTO deviceDTO, int index) {
        if (index >= technicians.size()) {
            log.info("All technician calls complete.");
            return;
        }
        JSONObject requestBody = requestBodies.get(index);
        TechnicianDTO technician = technicians.get(index);
        String technicianName = technician.getName();
        String countryCode = technician.getCountryCode();
        String phone = technician.getPhone();
        String technicianId = technician.getId();
        String timezone = technician.getTimeZone();
        System.out.println("Timezone: " + timezone);
        System.out.println("Device Last Seen: " + deviceDTO.getLast_seen_on());
        System.out.println("Device ID: " + deviceDTO.getId());
        if (countryCode == null || phone == null || countryCode.isBlank() || phone.isBlank()) {
            log.error("Invalid country code or phone for technician: {}", technicianName);
            processTechniciansSequentially(requestBodies, webClient, vdmsId, aiCallLogId, technicians, deviceDTO, index + 1);
            return;
        }
        String contactNumber = countryCode + phone;
        log.info("Sending request for technician: {}", technicianName);
        log.info("Request Body:{} ", requestBody.toString());
        log.info("Parameters: vdmsId: {}, technicianId: {},technicianName:{}, contactNumber: {}, aiCallLogId: {}", vdmsId, technicianId, technicianName, contactNumber, aiCallLogId);
        String formattedDateTime = formatLastSeen(deviceDTO.getLast_seen_on(), timezone);
        log.info("Formatted last seen time: {}", formattedDateTime);
        // Call the API for the current technician
        Flux<JSONObject> responseFlux = apiCallService.sendDescription(requestBody, vdmsId, technicianId, technicianName, contactNumber, formattedDateTime, aiCallLogId);
        responseFlux.subscribe(json -> {
            log.info("Received response: {} ", json.toString());
            String result = insertCallResponse(json);
            log.info(result);
            // Check status to determine whether to stop or proceed
            boolean shouldStop = false;
            boolean isLastTechnician = index == technicians.size() - 1;
            if (json.has("events")) {
                try {
                    JSONArray events = json.getJSONArray("events");
                    long latestCreatedAt = Long.MIN_VALUE;
                    String latestStatus = null;
                    BigInteger latestTimestamp = null;
                    // Find the latest event and check for "accepted"
                    for (int i = 0; i < events.length(); i++) {
                        JSONObject event = events.getJSONObject(i);
                        String status = event.optString("status");
                        long createdAtMillis = event.optLong("created_at");
                        if (createdAtMillis > latestCreatedAt) {
                            latestCreatedAt = createdAtMillis;
                            latestStatus = status;
                            latestTimestamp = BigInteger.valueOf(createdAtMillis);
                        }
                        if (status.equalsIgnoreCase("accepted")) {
                            shouldStop = true;
                        }
                    }
                    // Map "incomplete" to "rejected" for last technician
                    String statusForUpsert = latestStatus;
                    if (latestStatus != null) {
                        if (latestStatus.equalsIgnoreCase("incomplete")) {
                            statusForUpsert = "rejected";
                            log.info("Mapping status \'incomplete\' to \'rejected\' for last technician, aiCallLogId={}", aiCallLogId);
                        } else if (latestStatus.equalsIgnoreCase("failed") || latestStatus.equalsIgnoreCase("busy")) {
                            statusForUpsert = "busy";
                            log.info("Mapping status \'busy\' for last technician, aiCallLogId={}", aiCallLogId);
                        } else if (latestStatus.equalsIgnoreCase("failed") || latestStatus.equalsIgnoreCase("no-answer")) {
                            statusForUpsert = "no-answer";
                            log.info("Mapping status \'no-answer\' for last technician, aiCallLogId={}", aiCallLogId);
                        }
                        // For the last technician, update with the latest event's status
                        if (isLastTechnician && latestStatus != null) {
                            log.info("Last technician, updating status to: {} for aiCallLogId={} with technicianId={}", statusForUpsert, aiCallLogId, technicianId);
                            String callFlowByDeviceid = callFlowRuleRepository.checkCallFlowByDeviceid(deviceDTO.getId());
                            Integer triggerCount = deviceConditionsService.getAlertCount(deviceDTO.getId());
                            if (callFlowByDeviceid != null) {
                                aiCallLogRepository.upsertStatus(aiCallLogId, latestTimestamp, Boolean.TRUE, technicianId, statusForUpsert);
                                if ((triggerCount == null || triggerCount <= 3) && statusForUpsert.equalsIgnoreCase("rejected") || statusForUpsert.equalsIgnoreCase("no-answer") || statusForUpsert.equalsIgnoreCase("busy")) {
                                    log.info("Triggering call flow for deviceId={} with status={} and aiCallLogId={}", deviceDTO.getId(), statusForUpsert, aiCallLogId);
                                    Set<DeviceConditionsDTO> deleteDeviceConditions = deviceConditionsService.getDeviceConditionsForAiCall("", "", "", deviceDTO.getId());
                                    deviceConditionsService.deleteDeviceConditions("", "", deleteDeviceConditions);
                                    this.triggerCallFlow(deviceDTO.getId(), statusForUpsert, aiCallLogId);
                                } else if (statusForUpsert.equalsIgnoreCase("accepted") && triggerCount <= 3) {
                                    Set<DeviceConditionsDTO> deleteDeviceConditions = deviceConditionsService.getDeviceConditionsForAiCall("", "", "", deviceDTO.getId());
                                    deviceConditionsService.deleteDeviceConditions("", "", deleteDeviceConditions); // Delete existing conditions
                                }
                            } else {
                                if (statusForUpsert.equalsIgnoreCase("accepted") && triggerCount <= 3) {
                                    aiCallLogRepository.upsertStatus(aiCallLogId, latestTimestamp, Boolean.TRUE, technicianId, "accepted");
                                    Set<DeviceConditionsDTO> deleteDeviceConditions = deviceConditionsService.getDeviceConditionsForAiCall("", "", "", deviceDTO.getId());
                                    deviceConditionsService.deleteDeviceConditions("", "", deleteDeviceConditions);
                                } else if ((triggerCount == null || triggerCount < 3) && (statusForUpsert.equalsIgnoreCase("rejected") || statusForUpsert.equalsIgnoreCase("no-answer") || statusForUpsert.equalsIgnoreCase("busy"))) {
                                    log.info("No call flow found for deviceId={} and status={}, keeping status as ongoing, aiCallLogId={}", deviceDTO.getId(), latestStatus, aiCallLogId);
                                    String status = aiCallLogRepository.getStatusRemovedByAiCallLogId(aiCallLogId);
                                    if (status.equalsIgnoreCase("Scheduler terminated")) {
                                        aiCallLogRepository.upsertStatus(aiCallLogId, latestTimestamp, Boolean.TRUE, technicianId, statusForUpsert);
                                    } else {
                                        Set<DeviceConditionsDTO> deviceConditions = createDeviceConditionsDTO(deviceDTO);
                                        deviceConditionsService.upsertDeviceConditionsForAiCall("", vdmsId, "", deviceConditions);
                                        log.info("Device is offline, updating status to ongoing for aiCallLogId={}", aiCallLogId);
                                    }
                                } else if (triggerCount == 3 && (statusForUpsert.equalsIgnoreCase("rejected") || statusForUpsert.equalsIgnoreCase("no-answer") || statusForUpsert.equalsIgnoreCase("busy"))) {
                                    log.info("No call flow found for deviceId={} and status={}, aiCallLogId={}", deviceDTO.getId(), latestStatus, aiCallLogId);
                                    aiCallLogRepository.upsertStatus(aiCallLogId, latestTimestamp, Boolean.TRUE, technicianId, statusForUpsert);
                                    Set<DeviceConditionsDTO> deleteDeviceConditions = deviceConditionsService.getDeviceConditionsForAiCall("", "", "", deviceDTO.getId());
                                    deviceConditionsService.deleteDeviceConditions("", "", deleteDeviceConditions);
                                }
                            }
                        }
                    }
                } catch (JSONException e) {
                    log.error("Error parsing events: {} ", e.getMessage());
                }
            }
            // Proceed to the next technician if not stopping
            if (!shouldStop) {
                Integer status = deviceService.getDeviceStatus(deviceDTO.getId());
                if (status != null && status == 0) {
                    processTechniciansSequentially(requestBodies, webClient, vdmsId, aiCallLogId, technicians, deviceDTO, index + 1);
                } else {
                    log.info("Device {} is online, skipping further technician calls.", deviceDTO.getId());
                    // Update device online status
                }
            }
        }, 
//                error -> {
//                    log.error("Error:{}", error.getMessage());
//                    // Proceed to the next technician
//                    processTechniciansSequentially(
//                            requestBodies, webClient, vdmsId, aiCallLogId, technicians, deviceDTO, index + 1
//                    );
//                }
        error -> {
            log.warn("Call to technician failed or timed out: {}", error.getMessage());
            Mono.delay(Duration.ofSeconds(90)).subscribeOn(Schedulers.boundedElastic()).subscribe(ignored -> {
                try {
                    String latestStatus = aiCallLogHistoryRepository.getLatestCallStatus(aiCallLogId, technicianId);
                    System.out.println("Latest status after 90 seconds: " + latestStatus);
                    Integer deviceStatus = deviceService.getDeviceStatus(deviceDTO.getId());
                    // stop escalation
                    if ("accepted".equalsIgnoreCase(latestStatus)) {
                        log.info("Technician accepted. Stopping escalation.");
                        return;
                    }
                    // do not escalate
                    if ("in-progress".equalsIgnoreCase(latestStatus)) {
                        log.info("Call still looks in-progress, waiting for final Twilio event...");
                        return;
                    }
                    // escalate
                    boolean shouldEscalate = latestStatus == null || "rejected".equalsIgnoreCase(latestStatus) || "no-answer".equalsIgnoreCase(latestStatus) || "busy".equalsIgnoreCase(latestStatus) || "failed".equalsIgnoreCase(latestStatus);
                    if (shouldEscalate && deviceStatus != null && deviceStatus == 0) {
                        log.info("Technician did not accept (status={}). Escalating to next technician.", latestStatus);
                        processTechniciansSequentially(requestBodies, webClient, vdmsId, aiCallLogId, technicians, deviceDTO, index + 1);
                    } else {
                        log.info("Device online or call accepted. Stopping escalation.");
                    }
                } catch (Exception ex) {
                    log.error("Error in 90-second handler: {}", ex.getMessage());
                }
            });
        });
    }

    //Socket insert method
    @Transactional
    public String insertCallResponse(org.json.JSONObject json) {
        try {
            List<String> historyIds = new ArrayList<>();
            String aiCallLogId = json.optString("ai_call_log_id");
            String technicianId = json.optString("technician_id", null);
            String technicianName = json.optString("technician_name");
            if (technicianId == null || technicianId.trim().isEmpty()) {
                technicianId = null;
            }
            boolean isWebSocketResponse = json.has("events") && json.getJSONArray("events").length() == 1;
            Set<String> insertedStatuses = new HashSet<>();
            if (json.has("events")) {
                org.json.JSONArray events = json.getJSONArray("events");
                for (int i = 0; i < events.length(); i++) {
                    org.json.JSONObject event = events.getJSONObject(i);
                    String id = event.optString("id");
                    String status = event.optString("status");
                    String description = event.optString("description");
                    long createdAtMillis = event.optLong("created_at");
                    BigInteger timestamp = BigInteger.valueOf(createdAtMillis);
                    // Check if the id already exists
                    if (!aiCallLogHistoryRepository.existsById(id)) {
                        if (isWebSocketResponse) {
                            if (!insertedStatuses.contains(status)) {
                                try {
                                    aiCallLogHistoryRepository.insertAiCallLogHistoryState(id, timestamp, description, technicianId, aiCallLogId, status);
                                    historyIds.add(id);
                                    insertedStatuses.add(status);
                                } catch (Exception e) {
                                    log.error("Error inserting history state for id={} : {}", id, e.getMessage(), e);
                                }
                            }
                        } else {
                            Set<String> existingStatuses = aiCallLogHistoryRepository.findStatusesByAiCallLogId(aiCallLogId);
                            if (existingStatuses == null) {
                                existingStatuses = new HashSet<>();
                            }
                            if (!existingStatuses.contains(status) && !insertedStatuses.contains(status)) {
                                try {
                                    aiCallLogHistoryRepository.insertAiCallLogHistoryState(id, timestamp, description, technicianId, aiCallLogId, status);
                                    historyIds.add(id);
                                    insertedStatuses.add(status);
                                } catch (Exception e) {
                                    log.error("Error upserting history state for id={} : {}", id, e.getMessage(), e);
                                }
                            }
                        }
                    }
                    if (technicianName != null && !technicianName.equalsIgnoreCase("manager")) {
                        String device_id = aiCallLogRepository.getDeviceIdByAiCallLogId(aiCallLogId);
                        if (status.equalsIgnoreCase("accepted")) {
                            log.info("Updating status to: {} for aiCallLogId={} with technicianId={}", status, aiCallLogId, technicianId);
                            aiCallLogRepository.upsertStatus(aiCallLogId, timestamp, Boolean.TRUE, technicianId, status);
                            Set<DeviceConditionsDTO> deleteDeviceConditions = deviceConditionsService.getDeviceConditionsForAiCall("", "", "", device_id);
                            if (deleteDeviceConditions != null && !deleteDeviceConditions.isEmpty()) {
                                log.info("Deleting device conditions for device_id={} and aiCallLogId={}", device_id, aiCallLogId);
                                // Delete existing conditions
                                deviceConditionsService.deleteDeviceConditions("", "", deleteDeviceConditions);
                            }
                        }
                        String completedAiCallLogId = aiCallLogRepository.getAiCallLogIdByIsCompleted(aiCallLogId, Boolean.TRUE);
                        if (completedAiCallLogId != null && !completedAiCallLogId.isEmpty()) {
                            if (status != null) {
                                String statusForUpsert;
                                // Map input status to upsert status
                                switch (status.toLowerCase()) {
                                case "incomplete": 
                                    statusForUpsert = "rejected";
                                    log.info("Mapping \'incomplete\' to \'rejected\' for aiCallLogId={}", aiCallLogId);
                                    break;
                                case "failed": 
                                case "busy": 
                                    statusForUpsert = "busy";
                                    log.info("Mapping \'{}\' to \'busy\' for aiCallLogId={}", status, aiCallLogId);
                                    break;
                                case "no-answer": 
                                    statusForUpsert = "no-answer";
                                    log.info("Mapping \'{}\' to \'no-answer\' for aiCallLogId={}", status, aiCallLogId);
                                    break;
                                default: 
                                    statusForUpsert = status.toLowerCase();
                                    log.info("Using original status \'{}\' for aiCallLogId={}", statusForUpsert, aiCallLogId);
                                    break;
                                }
                                // Always call upsert
                                if ("rejected".equalsIgnoreCase(statusForUpsert) || "busy".equalsIgnoreCase(statusForUpsert) || "no-answer".equalsIgnoreCase(statusForUpsert)) {
                                    aiCallLogRepository.upsertStatus(aiCallLogId, timestamp, Boolean.TRUE, technicianId, statusForUpsert);
                                    Set<DeviceConditionsDTO> deleteDeviceConditions = deviceConditionsService.getDeviceConditionsForAiCall("", "", "", device_id);
                                    if (deleteDeviceConditions != null && !deleteDeviceConditions.isEmpty()) {
                                        log.info("Deleting device conditions for device_id={} and aiCallLogId={}", device_id, aiCallLogId);
                                        deviceConditionsService.deleteDeviceConditions("", "", deleteDeviceConditions);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            // Notify socket for inserted history records
            for (String id : historyIds) {
                try {
                    socketService.socketAiCallLogHistoryUpdate(id);
                } catch (Exception e) {
                    log.error("Socket update failed for id={} : {}", id, e.getMessage(), e);
                }
            }
        } catch (Exception e) {
            log.error("Failed to parse call response JSON: {}", e.getMessage(), e);
        }
        return "Call response inserted successfully";
    }

    public AiCallLogHistoryDTO getAiCallLogHistoryById(String aiCallLogHistoryId) {
        AiCallLogHistoryDTO aiCallLogHistoryDTO = aiCallLogHistoryRepository.getAiCallLogHistoryById(aiCallLogHistoryId);
        String technicianName = technicianService.getTechnicianNameById(aiCallLogHistoryDTO.getTechnicianId());
        aiCallLogHistoryDTO.setTechnicianName(technicianName);
        if (aiCallLogHistoryDTO != null) {
            log.info("Retrieved AiCallLogHistoryDTO: {} ", aiCallLogHistoryDTO.getAiCallLogId());
            return aiCallLogHistoryDTO;
        }
        log.info("No AiCallLogHistory found for ID: {} ", aiCallLogHistoryId);
        return null;
    }

    private String formatLastSeen(String lastSeen, String timezone) {
        if (lastSeen == null || lastSeen.isBlank()) {
            return "Last seen time not available";
        }
        try {
            String cleanedLastSeen = lastSeen.split("\\.")[0];
            long epochMillis = Long.parseLong(cleanedLastSeen);
            Instant instant = Instant.ofEpochMilli(epochMillis);
            ZonedDateTime zdt = instant.atZone(ZoneId.of(timezone));
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MMMM d, yyyy, h:mm a z");
            return zdt.format(formatter);
        } catch (NumberFormatException | ArrayIndexOutOfBoundsException | DateTimeException e) {
            log.error("Error formatting last seen time: " + lastSeen + ", timezone: " + timezone + ": " + e.getMessage());
            return "Invalid";
        }
    }

    private Set<DeviceConditionsDTO> createDeviceConditionsDTO(DeviceDTO deviceDTO) {
        Set<DeviceConditionsDTO> deviceConditions = new HashSet<>();
        DeviceConditionsDTO condition = new DeviceConditionsDTO();
        condition.setDevice_id(deviceDTO.getId());
        condition.setAlert_condition("device_offline_ai_call_alert");
        condition.setTrigger_time(1800); // 30 - 1800 minutes in seconds
        condition.setPriority("High");
        condition.setStart_time("00:00");
        condition.setEnd_time("23:59");
        condition.setMax_alert_count(3);
        condition.setAlert_message("Device is offline");
        condition.setAlert_count_enabled(1);
        deviceConditions.add(condition);
        return deviceConditions;
    }

    public void updateDeviceOnlineStatus(String id, Integer status, String deviceConditionId) {
        System.out.println("*************Updating device online status for device ID: " + id + " with status: " + status);
        String aiCallLogId = aiCallLogRepository.getAiCallLogIdByDeviceId(id);
        String aiCallLogHistoryId = Generators.timeBasedGenerator().generate().toString();
        Integer alertCount = deviceConditionsService.getAlertCount(id);
        BigInteger createdAt = BigInteger.valueOf(System.currentTimeMillis());
        if (deviceConditionId != null && !deviceConditionId.isEmpty()) {
            if (aiCallLogId != null) {
                log.info("Updating device online status for aiCallLogId: {} with status: {}", aiCallLogId, status);
                aiCallLogHistoryRepository.insertAiCallLogHistoryState(aiCallLogHistoryId, createdAt, "Device online", null, aiCallLogId, "Scheduler terminated");
                socketService.socketAiCallLogOngoingHistoryUpdate(aiCallLogHistoryId);
                String callFlowByDeviceId = callFlowRuleRepository.checkCallFlowByDeviceid(id);
                if (alertCount != 3 || callFlowByDeviceId.isEmpty()) {
                    aiCallLogRepository.upsertStatus(aiCallLogId, null, Boolean.TRUE, null, "Scheduler terminated");
                }
                deviceService.getDeviceDndAndSystemDndStatus(id, true);
                Set<DeviceConditionsDTO> deleteDeviceConditions = deviceConditionsService.getDeviceConditionsForAiCall("", "", "", id);
                deviceConditionsService.deleteDeviceConditions("", "", deleteDeviceConditions);
            } else {
                log.info("No aiCallLogId found for device ID: {}. Creating new call log.", id);
            }
        } else {
            // If deviceConditionId is null or empty, we assume the device is online and update the status accordingly
            if (aiCallLogId != null) {
                int historyCount = aiCallLogHistoryRepository.countByAiCallLogId(aiCallLogId);
                if (historyCount == 0) {
                    aiCallLogRepository.upsertStatus(aiCallLogId, null, Boolean.TRUE, null, "Device Online");
                    deviceService.getDeviceDndAndSystemDndStatus(id, true);
                }
                aiCallLogHistoryRepository.insertAiCallLogHistoryState(aiCallLogHistoryId, createdAt, "Device online", null, aiCallLogId, "Device Online");
                socketService.socketAiCallLogOngoingHistoryUpdate(aiCallLogHistoryId);
            }
        }
    }

    public AiCallLogHistoryDTO fetchAiCallLogHistoryById(String aiCallLogHistoryId) {
        AiCallLogHistoryDTO aiCallLogHistoryDTO = aiCallLogHistoryRepository.getAiCallLogHistoryById(aiCallLogHistoryId);
        if (aiCallLogHistoryDTO != null) {
            log.info("Retrieved AiCallLogHistoryDTO: {} ", aiCallLogHistoryDTO.getAiCallLogId());
            return aiCallLogHistoryDTO;
        }
        log.info("No AiCallLogHistory found for ID: {} ", aiCallLogHistoryId);
        return null;
    }

    //httpCall insert method
//    public String insertCallResponse(org.json.JSONObject json) {
//
//        try {
//            List<String> historyIds = new ArrayList<>();
//            String aiCallLogId = json.optString("ai_call_log_id");
//            String technicianId = json.optString("technician_id", null);
//            String technicianName = json.optString("technician_name");
//            if (technicianId == null || technicianId.trim().isEmpty()) {
//                technicianId = null;
//            }
//
//            if (json.has("events")) {
//                org.json.JSONArray events = json.getJSONArray("events");
//                for (int i = 0; i < events.length(); i++) {
//                    org.json.JSONObject event = events.getJSONObject(i);
//                    String id = Generators.timeBasedGenerator().generate().toString();
//                    String status = event.optString("status");
//                    String description = event.optString("description");
//                    long createdAtMillis = event.optLong("created_at");
//                    BigInteger timestamp = BigInteger.valueOf(createdAtMillis);
//
//                    aiCallLogHistoryRepository.insertAiCallLogHistoryState(id, timestamp, description, technicianId, aiCallLogId, status);
//                    historyIds.add(id);
//
//                    // Call upsertStatus only for "accepted" AND "incomplete" status only for technicians other than manager
//                    if(!technicianName.equalsIgnoreCase("manager")) {
//                        System.out.println("Technicina call");
//                        if (status.equalsIgnoreCase("accepted")) {
//                            log.info("Updating status to: {} for aiCallLogId={} with technicianId={}",
//                                    status, aiCallLogId, technicianId);
//                            aiCallLogRepository.upsertStatus(aiCallLogId, timestamp, Boolean.TRUE, technicianId, status);
//                        }
//                    }
//
//
//                }
//            }
//            for (String id : historyIds) {
//                try {
//                    socketService.socketAiCallLogHistoryUpdate(id);
//                } catch (Exception e) {
//                    log.error("Socket update failed for id={} : {}", id, e.getMessage(), e);
//                }
//            }
//            return "Call response inserted successfully";
//        } catch (Exception e) {
//            throw new RuntimeException("Failed to parse call response JSON", e);
//        }
//    }
    /**
     * *************************************************************  CALL STATUS  ********************************************************************
     */
    public List<CallFlowRuleDTO> getCallFlow(String username, String vdmsid, Integer pageno, Integer pagesize, String searchkey) {
        Integer offset = pagesize * (pageno - 1);
        List<CallFlowRuleDTO> callFlowRuleDTOS = callFlowRuleRepository.getAllCallFlowRules(offset, pagesize, searchkey);
        for (CallFlowRuleDTO callFlowRuleDTO : callFlowRuleDTOS) {
            List<CallFlowRuleConditionDTO> conditionDTOList = getCallFlowRuleConditionsByCallFlowRuleId(callFlowRuleDTO.getId());
            callFlowRuleDTO.setCallFlowRuleConditions(conditionDTOList);
        }
        return callFlowRuleDTOS;
    }

    public void deleteCallFlowById(String username, String vdmsid, Set<String> callFlowRuleIds) {
        for (String callFlowRuleId : callFlowRuleIds) {
            callFlowRuleRepository.deleteById(callFlowRuleId);
        }
    }

    public ResponseEntity<ResponseDTO> upsertCallFlow(CallFlowRuleDTO callFlowRuleDTO, String username, String vdmsid) {
        BigInteger timestamp = BigInteger.valueOf(System.currentTimeMillis());
        log.info("Processing DTO: {}", callFlowRuleDTO);
        List<String> newCallFlowRuleConditionIds = new ArrayList<>();
        List<CallFlowRuleConditionDTO> existingCallFlowRuleConditionDTOList = new ArrayList<>();
        List<String> callFlowRuleConditionToBeDeleted = new ArrayList<>();
        Set<String> requestCriteriaSet = new HashSet<>();
        if (callFlowRuleDTO != null) {
            if (callFlowRuleDTO.getId() == null) {
                callFlowRuleDTO.setId(Generators.timeBasedGenerator().generate().toString());
            } else {
                existingCallFlowRuleConditionDTOList = getCallFlowRuleConditionsByCallFlowRuleId(callFlowRuleDTO.getId());
            }
            List<CallFlowRuleConditionDTO> callFlowRuleConditionDTOList = callFlowRuleDTO.getCallFlowRuleConditions();
            if (!callFlowRuleConditionDTOList.isEmpty()) {
                for (CallFlowRuleConditionDTO conditionDTO : callFlowRuleConditionDTOList) {
                    String criteria = conditionDTO.getCriteria();
                    if (criteria == null) continue;
                    if (!requestCriteriaSet.add(criteria)) {
                        ResponseDTO error = new ResponseDTO("Conflict: Duplicate criteria detected in the request - \'" + criteria + "\' already exists.", 409, null, false, timestamp);
                        return ResponseEntity.status(HttpStatus.CONFLICT).body(error);
                    }
                    if (conditionDTO.getId() != null) {
                        newCallFlowRuleConditionIds.add(conditionDTO.getId());
                    }
                }
            }
            for (CallFlowRuleConditionDTO callFlowRuleCondition : existingCallFlowRuleConditionDTOList) {
                if (callFlowRuleCondition.getId() != null && !newCallFlowRuleConditionIds.contains(callFlowRuleCondition.getId())) {
                    callFlowRuleConditionToBeDeleted.add(callFlowRuleCondition.getId());
                }
            }
            callFlowRuleRepository.upsertAiCallFlow(callFlowRuleDTO.getId(), callFlowRuleDTO.getName(), username, timestamp, username, timestamp, callFlowRuleDTO.getDeviceId());
            deleteCallFlowConditions(callFlowRuleDTO, callFlowRuleConditionToBeDeleted);
            upsertCallFlowConditions(callFlowRuleDTO, callFlowRuleConditionDTOList);
            ResponseDTO success = new ResponseDTO("Call flow rule and conditions updated successfully.", 200, true, timestamp);
            return ResponseEntity.ok(success);
        }
        ResponseDTO error = new ResponseDTO("Invalid request: Call flow data must not be null", 400, false, timestamp);
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(error);
    }

    public Set<String> browseDockers(String email, String vdmsid, String searchkey) {
        return deviceService.listAiEnabledDockers(email, vdmsid, searchkey);
    }

    public List<CallFlowRuleDTO> browseCallFlowDevicesWithSearch(String username, String vdmsid, String dockername, Integer pageno, Integer pagesize, String searchkey) {
        List<CallFlowRuleDTO> aiCallEnabledDevices = new ArrayList<>();
        List<DeviceDTO> devices = deviceService.browseAiCallFlowDevicesWithSearch(username, vdmsid, dockername, pageno, pagesize, searchkey);
        for (DeviceDTO device : devices) {
            CallFlowRuleDTO aiCallEnabledDevice = new CallFlowRuleDTO();
            aiCallEnabledDevice.setDeviceId(device.getId());
            aiCallEnabledDevice.setDeviceName(device.getName());
            aiCallEnabledDevice.setIsAdded(device.getIs_added());
            aiCallEnabledDevices.add(aiCallEnabledDevice);
        }
        return aiCallEnabledDevices;
    }

    public void upsertCallFlowConditions(CallFlowRuleDTO callFlowRuleDTO, List<CallFlowRuleConditionDTO> callFlowRuleConditionDTOs) {
        if (callFlowRuleDTO != null && callFlowRuleConditionDTOs != null && !callFlowRuleConditionDTOs.isEmpty()) {
            for (CallFlowRuleConditionDTO callFlowRuleConditionDTO : callFlowRuleConditionDTOs) {
                if (callFlowRuleConditionDTO.getId() == null) {
                    callFlowRuleConditionDTO.setId(Generators.timeBasedGenerator().generate().toString());
                }
                callFlowRuleConditionRepository.upsertCallFlowRuleCondition(callFlowRuleConditionDTO.getId(), callFlowRuleConditionDTO.getCriteria(), callFlowRuleConditionDTO.getActionType(), callFlowRuleConditionDTO.getActionValue(), callFlowRuleConditionDTO.getActionMessage(), callFlowRuleDTO.getId());
            }
        }
    }

    public List<CallFlowRuleConditionDTO> getCallFlowRuleConditionsByCallFlowRuleId(String callFlowRuleId) {
        return callFlowRuleConditionRepository.getCallFlowRuleConditionsByCallFlowRuleId(callFlowRuleId);
    }

    public List<CallFlowRuleConditionDTO> getCallFlowRuleConditionByRuleIdAndCriteria(String callFlowRuleId, String criteria) {
        return callFlowRuleConditionRepository.getCallFlowRuleConditionByRuleIdAndCriteria(callFlowRuleId, criteria);
    }

    public void deleteCallFlowConditions(CallFlowRuleDTO callFlowRuleDTO, List<String> callFlowRuleConditionIds) {
        if (callFlowRuleDTO != null && callFlowRuleConditionIds != null && !callFlowRuleConditionIds.isEmpty()) {
            callFlowRuleConditionRepository.deleteCallFlowRuleConditionById(callFlowRuleConditionIds);
        }
    }

    public List<CallFlowRuleDTO> getCallFlowByDeviceId(String deviceId) {
        List<CallFlowRuleDTO> callFlowRuleDTOS = new ArrayList<>();
        try {
            if (deviceId != null && !deviceId.trim().isEmpty()) {
                List<CallFlowRuleDTO> fetchedRules = callFlowRuleRepository.getCallFlowByDeviceId(deviceId);
                if (fetchedRules != null) {
                    for (CallFlowRuleDTO fetchedRule : fetchedRules) {
                        if (fetchedRule != null && fetchedRule.getId() != null) {
                            try {
                                List<CallFlowRuleConditionDTO> conditions = getCallFlowRuleConditionsByCallFlowRuleId(fetchedRule.getId());
                                fetchedRule.setCallFlowRuleConditions(conditions != null ? conditions : Collections.emptyList());
                            } catch (Exception e) {
                                log.error("Error fetching conditions for rule ID: {}", fetchedRule.getId(), e);
                                fetchedRule.setCallFlowRuleConditions(Collections.emptyList());
                            }
                        }
                        callFlowRuleDTOS.add(fetchedRule);
                    }
                }
            } else {
                log.warn("Device ID is null or empty.");
            }
        } catch (Exception e) {
            log.error("Unexpected error in getCallFlowByDeviceId for device ID: {}", deviceId, e);
        }
        return callFlowRuleDTOS;
    }

    public List<CallFlowRuleDTO> getCallFlowByDeviceIdAndCriteria(String deviceId, String criteria) {
        if (deviceId == null || deviceId.trim().isEmpty()) {
            log.warn("Device ID is null or empty.");
            return Collections.emptyList();
        }
        List<CallFlowRuleDTO> fetchedRules;
        try {
            fetchedRules = callFlowRuleRepository.getCallFlowByDeviceId(deviceId);
        } catch (Exception e) {
            log.error("Error fetching call flow rules for device ID: {}", deviceId, e);
            return Collections.emptyList();
        }
        if (fetchedRules == null || fetchedRules.isEmpty()) {
            return Collections.emptyList();
        }
        for (CallFlowRuleDTO rule : fetchedRules) {
            if (rule != null && rule.getId() != null) {
                try {
                    List<CallFlowRuleConditionDTO> conditions = getCallFlowRuleConditionByRuleIdAndCriteria(rule.getId(), criteria);
                    rule.setCallFlowRuleConditions(conditions != null ? conditions : Collections.emptyList());
                } catch (Exception e) {
                    log.error("Error fetching conditions for rule ID: {}", rule.getId(), e);
                    rule.setCallFlowRuleConditions(Collections.emptyList());
                }
            }
        }
        return fetchedRules;
    }

    public void triggerCallFlow(String deviceId, String criteria, String callLogId) {
        List<CallFlowRuleDTO> callFlowRuleDTOS = getCallFlowByDeviceIdAndCriteria(deviceId, criteria);
        String date = "";
        String time = "";
        VdmsDTO vdms = new VdmsDTO();
        vdms.setId("VDMS400");
        DeviceDTO deviceDTO = this.getDeviceInfoFromDb(deviceId);
        String formattedDateTime = formatLastSeen(deviceDTO.getLast_seen_on(), vdms.getTimezone());
        String[] parts = formattedDateTime.split(",\\s+");
        if (parts.length >= 3) {
            date = parts[0] + ", " + parts[1]; // "June 16, 2025"
            time = parts[2]; // "4:30 PM IST"
        } else {
            log.error("Could not split date and time correctly.");
        }
        if (callFlowRuleDTOS != null && !callFlowRuleDTOS.isEmpty()) {
            for (CallFlowRuleDTO callFlowRuleDTO : callFlowRuleDTOS) {
                if (callFlowRuleDTO.getCallFlowRuleConditions() != null && !callFlowRuleDTO.getCallFlowRuleConditions().isEmpty()) {
                    for (CallFlowRuleConditionDTO condition : callFlowRuleDTO.getCallFlowRuleConditions()) {
                        log.info("Processing condition: {} for device: {}", condition.getCriteria(), callFlowRuleDTO.getDeviceName());
                        switch (condition.getActionType()) {
                        case "Re-route": 
                            log.info("Re-routing call for device: {} with action value: {}", callFlowRuleDTO.getDeviceName(), condition.getActionValue());
                            String phone = condition.getActionValue();
                            if (phone != null && !phone.startsWith("+")) {
                                phone = "+" + phone;
                            }
                            // String response = makeManagerCall(deviceId, condition.getActionValue(), callLogId);
                            // log.info("Re-routing {}",response);
                            makeManagerCall(deviceId, phone, callLogId).subscribe(response -> log.info("Re-routing {}", response), error -> log.error("Error in manager call: {}", error.getMessage(), error));
                            break;
                        case "Email": 
                            com.alibaba.fastjson.JSONObject emailRequestBody = new com.alibaba.fastjson.JSONObject();
                            emailRequestBody.put("date", date);
                            emailRequestBody.put("asset_name", callFlowRuleDTO.getDeviceName());
                            emailRequestBody.put("time", time);
                            emailRequestBody.put("email", condition.getActionValue());
                            emailRequestBody.put("message", condition.getActionMessage());
                            emailRequestBody.put("property_name", vdms.getProperty_name());
                            emailRequestBody.put("vdms_id", vdms.getId());
                            emailRequestBody.put("alert_type", "email");
                            log.info("Sending email request body: {}", emailRequestBody);
                            ResponseEntity<String> emailResponse = apiCallService.sendCallFlowMail(emailRequestBody);
                            if (emailResponse != null && emailResponse.getStatusCodeValue() == 200) {
                                log.info("Email sent successfully");
                                insertCallFlowResponse("Email sent to " + condition.getActionValue(), "Email sent to " + condition.getActionValue(), callLogId);
                            } else {
                                log.error("Failed to send email {}", emailResponse);
                            }
                            break;
                        case "SMS": 
                            log.info("Sending SMS for device: {} to {} with message: {}", callFlowRuleDTO.getDeviceName(), condition.getActionValue(), condition.getActionMessage());
                            String phoneNo = condition.getActionValue();
                            if (phoneNo != null && !phoneNo.startsWith("+")) {
                                phoneNo = "+" + phoneNo;
                            }
                            com.alibaba.fastjson.JSONObject messageBody = new com.alibaba.fastjson.JSONObject();
                            messageBody.put("date", date);
                            messageBody.put("asset_name", callFlowRuleDTO.getDeviceName());
                            messageBody.put("time", time);
                            messageBody.put("email", condition.getActionValue());
                            messageBody.put("phone", phoneNo);
                            messageBody.put("message", condition.getActionMessage());
                            messageBody.put("property_name", vdms.getProperty_name());
                            messageBody.put("vdms_id", vdms.getId());
                            messageBody.put("alert_type", "sms");
                            log.info("Sending SMS request body: {}", messageBody);
                            ResponseEntity<String> smsResponse = apiCallService.sendCallFlowMessage(messageBody);
                            if (smsResponse != null && smsResponse.getStatusCodeValue() == 200) {
                                log.info("SMS sent successfully");
                                insertCallFlowResponse("SMS sent to " + phoneNo, "SMS sent to " + phoneNo, callLogId);
                            } else {
                                log.error("Failed to send SMS: {}", smsResponse);
                            }
                            break;
                        default: 
                            log.warn("Unknown action type: {} for device: {}", condition.getActionType(), callFlowRuleDTO.getDeviceName());
                        }
                    }
                } else {
                    log.warn("No call flow rules found for device ID: {} with criteria: {}", deviceId, criteria);
                }
            }
        } else {
            log.warn("No call flow rules found for device ID: {} with criteria: {}", deviceId, criteria);
        }
    }

    public void insertCallFlowResponse(String description, String state, String aiCallLogId) {
        String id = Generators.timeBasedGenerator().generate().toString();
        aiCallLogHistoryRepository.insertAiCallLogHistoryState(id, BigInteger.valueOf(System.currentTimeMillis()), description, null, aiCallLogId, state);
        try {
            socketService.socketAiCallLogHistoryUpdate(id);
        } catch (Exception e) {
            log.error("Socket update failed for id={} : {}", id, e.getMessage(), e);
        }
    }

    public Mono<String> makeManagerCall(String deviceId, String phoneNo, String aiCallLogId) {
        try {
            VdmsDTO vdmsDTO = new VdmsDTO();
            vdmsDTO.setId("VDMS400");
            DeviceDTO deviceDTO = this.getDeviceInfoFromDb(deviceId);
            String issueType = aiCallLogRepository.getAiCallLogIssueTypeByAiCallLogId(aiCallLogId);
            JSONObject requestBody = createDeviceRequestBody(deviceDTO, issueType);
            String formattedDateTime = formatLastSeen(deviceDTO.getLast_seen_on(), vdmsDTO.getTimezone());
            log.info("Sending request to Twilio: {} vdms id :{} contact number : {} ai CallLogId :{} ", requestBody.toString(), vdmsDTO.getId(), phoneNo, aiCallLogId);
            return apiCallService.sendDescription(requestBody, vdmsDTO.getId(), null, "manager", phoneNo, formattedDateTime, aiCallLogId).collectList().flatMap(responses -> {
                try {
                    if (responses == null || responses.isEmpty()) {
                        log.warn("No response received from manager call.");
                        return Mono.just("failed");
                    }
                    for (JSONObject json : responses) {
                        log.info("Received response manager call: {}", json.toString());
                        String result = insertCallResponse(json);
                        log.info(result);
                        if (json.has("events")) {
                            JSONArray events = json.getJSONArray("events");
                            for (int i = 0; i < events.length(); i++) {
                                JSONObject event = events.getJSONObject(i);
                                String status = event.optString("status");
                                log.info("Manager call {} for deviceId={} with aiCallLogId={}", status, deviceId, aiCallLogId);
                            }
                        }
                    }
                    return Mono.just("success");
                } catch (JSONException e) {
                    log.error("JSON parsing error during manager call: {}", e.getMessage(), e);
                    return Mono.just("failed");
                }
            }).onErrorResume(e -> {
                log.error("Error occurred during manager call (reactive pipeline): {}", e.getMessage(), e);
                return Mono.just("failed");
            });
        } catch (Exception e) {
            log.error("Error occurred during manager call (outer catch): {}", e.getMessage(), e);
            return Mono.just("failed");
        }
    }
}
