// Generated by delombok at Wed May 13 12:29:10 IST 2026
package io.sclera.service;
import io.sclera.client.APICallClient;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import io.sclera.Repository.AssetRepository;
import io.sclera.Repository.VdmsRepository;
import io.sclera.client.CorrigoClient;
import io.sclera.dto.CorrigoConfigurationDTO;
import io.sclera.dto.DeviceDTO;
import io.sclera.dto.DeviceOnboardStatusDTO;
import io.sclera.dto.SpecificationsDTO;
import io.sclera.dto.touchscreen.settings.VdmsDTO;
import io.sclera.interfaces.AssetOnboardServiceInterface;
import io.sclera.models.Asset;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Service;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.EntityManager;
import jakarta.servlet.http.HttpServletRequest;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * Coordinates onboarding of assets and virtual devices into the platform.
 *
 * <p>Translates temporary product data into {@link DeviceDTO} instances, persists onboarded
 * assets, and tracks onboarding status. Long-running work is dispatched to single-thread
 * executors so callers are not blocked.
 *
 * <p>Key collaborators: {@link APICallClient} for temporary product retrieval and cleanup,
 * {@link DeviceService} for device persistence and onboard status updates,
 * {@link LocationService} for location lookups, {@link CorrigoClient} for Corrigo asset
 * synchronization, {@link AssetRepository} for asset upsert/delete operations, and
 * {@link VdmsRepository} for VDMS property details.
 */
@Service
@ConfigurationProperties(prefix = "sclera")
public class AssetOnboardService implements AssetOnboardServiceInterface {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(AssetOnboardService.class);
    @Autowired
    APICallClient apiCallService;
    @Autowired
    DeviceService deviceService;
    @Autowired
    LocationService locationService;
    @Autowired
    AssetRepository assetRepository;
    @Autowired
    CorrigoClient corrigoService;
    @Autowired
    VdmsRepository vdmsRepository;

    @PersistenceContext
    private EntityManager entityManager;

    /**
     * Builds devices from temporary product data and onboards them asynchronously.
     *
     * @param username   the requesting user
     * @param vdmsid     the VDMS identifier
     * @param asset_data the onboarding payload, including docker name, location id, and temporary asset ids
     */
    public void addAssetOnboardedData(String username, String vdmsid, JSONObject asset_data) {
        String docker_name = asset_data.getString("docker_name");
        String location_id = asset_data.getString("location_id");
        JSONArray temp_asset_ids = JSON.parseArray(asset_data.getJSONArray("temp_asset_ids").toJSONString());
        List<DeviceDTO> deviceDTOList = new ArrayList<>();
        try {
            JSONArray final_asset_data = apiCallService.getTemporaryProductByIds(temp_asset_ids);
            if (final_asset_data.size() > 0) {
                for (int i = 0; i < final_asset_data.size(); i++) {
                    JSONObject asset_data_object = final_asset_data.getJSONObject(i);
                    List<SpecificationsDTO> specifications = this.updateDeviceSpecificationDetails(JSON.parseArray(asset_data_object.getString("specifications")));
                    DeviceDTO deviceDTO = new DeviceDTO();
                    deviceDTO.setDocker_name(docker_name);
                    if (location_id == null) {
                        location_id = asset_data_object.getString("location_id");
                        int count = locationService.getLocationId(location_id);
                        if (count == 0) {
                            location_id = null;
                        }
                    }
                    deviceDTO.setLocation_id(location_id);
                    deviceDTO.setModel(asset_data_object.getString("model"));
                    deviceDTO.setVendor(asset_data_object.getString("vendor"));
                    deviceDTO.setVirtual_device_type(2);
                    deviceDTO.setDescription(asset_data_object.getString("description"));
                    deviceDTO.setSpecifications(specifications);
                    deviceDTO.setAsset_group("generic");
                    deviceDTO.setAsset_image_url(asset_data_object.getString("image_url"));
                    deviceDTO.setUser_data_name(asset_data_object.getString("name"));
                    deviceDTO.setMonitor(1);
                    deviceDTOList.add(deviceDTO);
                }
            }
        } catch (Exception e) {
            log.debug("{}", e);
        }
        if (deviceDTOList.size() > 0) {
            ExecutorService executorService = Executors.newSingleThreadExecutor();
            executorService.execute(() -> {
                deviceService.addAssetOnboardedDevices(username, vdmsid, deviceDTOList);
                apiCallService.deleteTemporaryProductByIds(temp_asset_ids);
            });
            executorService.shutdown();
        }
    }

    /**
     * Converts raw specification entries into specification DTOs.
     *
     * @param specifications the raw specification array with key/value pairs
     * @return the parsed list of {@link SpecificationsDTO}
     */
    public List<SpecificationsDTO> updateDeviceSpecificationDetails(JSONArray specifications) {
        List<SpecificationsDTO> final_specifications = new ArrayList<>();
        try {
            if (specifications.size() > 0) {
                for (int i = 0; i < specifications.size(); i++) {
                    JSONObject specification_object = specifications.getJSONObject(i);
                    SpecificationsDTO specificationsDTO = new SpecificationsDTO();
                    specificationsDTO.setKey_name(specification_object.getString("key"));
                    specificationsDTO.setKey_value(specification_object.getString("value"));
                    final_specifications.add(specificationsDTO);
                }
            }
        } catch (Exception e) {
            log.debug("{}", e);
        }
        return final_specifications;
    }

    /**
     * Inserts or updates an asset record for the given device.
     *
     * @param device          the device whose asset is upserted
     * @param vdmsid          the VDMS identifier
     * @param assetImportType the asset import type
     * @param username        the requesting user
     */
    @org.springframework.transaction.annotation.Transactional
    public void assetUpsert(DeviceDTO device, String vdmsid, String assetImportType, String username) {
        Asset asset = assetRepository.findById(device.getId()).orElse(null);
        if (asset != null) {
            // CONFLICT path: original ON CONFLICT updated ONLY these three columns
            asset.setDisplay_name(device.getUser_data_name());
            asset.setDescription(device.getDescription());
            asset.setType(device.getType());
        } else {
            // INSERT path: full row as the original VALUES(...) supplied
            asset = new Asset();
            asset.setId(device.getId());
            asset.setDisplay_name(device.getUser_data_name());
            asset.setDescription(device.getDescription());
            asset.setType(device.getType());
            asset.setNetwork_layer(7);
            asset.setOriginalKeys("");
            asset.setCustomFields(device.getCustom_fields());
            asset.setIsMatched(false);
            asset.setSubsystem_count(0);
            asset.setImport_type(assetImportType);
            if (vdmsid != null) {
                asset.setVdms(entityManager.getReference(io.sclera.models.Vdms.class, vdmsid));
            }
        }
        assetRepository.save(asset);
//        deviceService.updateVirtualDeviceOnboardStatusByAssetMapper(device,username);
    }

    /**
     * Deletes all asset records.
     */
    public void deleteAllRecords() {
        assetRepository.deleteAllRecords();
    }

    /**
     * Synchronizes Corrigo assets asynchronously.
     *
     * @param username              the requesting user
     * @param vdmsid                the VDMS identifier
     * @param pageNo                the page number to fetch
     * @param pageSize              the page size
     * @param searchKey             the search key used to filter assets
     * @param corrigo_configuration the Corrigo connection configuration
     */
    public void updateCorrigoAssets(String username, String vdmsid, Integer pageNo, Integer pageSize, String searchKey, CorrigoConfigurationDTO corrigo_configuration) {
        ExecutorService executorService = Executors.newSingleThreadExecutor();
        executorService.execute(() -> {
            corrigoService.updateCorrigoAssets(username, vdmsid, pageNo, pageSize, searchKey, corrigo_configuration);
        });
        executorService.shutdown();
    }

    /**
     * Inserts or updates onboard assets.
     *
     * @param username           the requesting user
     * @param vdmsid             the VDMS identifier
     * @param onboard_asset_data the onboard asset payload
     * @param httpServletRequest the originating HTTP request, used for logging
     */
    public void upsertOnboardAssets(String username, String vdmsid, JSONObject onboard_asset_data, HttpServletRequest httpServletRequest) {
        log.info("endpoint: {}, upsertOnboardAssets, description: Updating onboard assets, params: onboard_asset_data: {}", httpServletRequest.getRequestURI(), onboard_asset_data);
        deviceService.upsertOnboardAssets(username, vdmsid, onboard_asset_data);
    }

    /**
     * Updates the onboard status of assets.
     *
     * @param username           the requesting user
     * @param vdmsid             the VDMS identifier
     * @param onboard_asset_data the onboard status payload
     * @param httpServletRequest the originating HTTP request, used for logging
     */
    public void updateAssetOnboardStatus(String username, String vdmsid, JSONObject onboard_asset_data, HttpServletRequest httpServletRequest) {
        log.info("endpoint: {}, updateAssetOnboardStatus, description: Updating onboard status, params: onboard_asset_data: {}", httpServletRequest.getRequestURI(), onboard_asset_data);
        deviceService.updateAssetOnboardStatus(username, vdmsid, onboard_asset_data);
    }

    /**
     * Updates onboard data for a specific device.
     *
     * @param username               the requesting user
     * @param vdmsid                 the VDMS identifier
     * @param device_id              the device identifier
     * @param deviceOnboardStatusDTO the onboard status details to apply
     * @param onboard_status         the onboard status code
     * @param httpServletRequest     the originating HTTP request, used for logging
     */
    public void updateAssetOnboardData(String username, String vdmsid, String device_id, DeviceOnboardStatusDTO deviceOnboardStatusDTO, Integer onboard_status, HttpServletRequest httpServletRequest) {
        log.info("endpoint: {}, updateAssetOnboardData, description: Updating onboard data, params: deviceOnboardStatusDTO: {}", httpServletRequest.getRequestURI(), deviceOnboardStatusDTO);
        deviceService.updateAssetOnboardData(username, vdmsid, device_id, deviceOnboardStatusDTO, onboard_status);
    }

//    public Map<String, Integer> getAssetOnboardCount(String username, String vdmsid, String dockername) {
//        return deviceService.getAssetOnboardCount(username, vdmsid, dockername);
//    }
    /**
     * Returns onboarding counts grouped by status.
     *
     * @param username                   the requesting user
     * @param vdmsid                     the VDMS identifier
     * @param dockername                 the docker name to scope the counts
     * @param search_sort_filter_details the search, sort, and filter criteria
     * @return a map of onboarding status to count
     */
    public Map<String, Integer> getAssetOnboardCount(String username, String vdmsid, String dockername, JSONObject search_sort_filter_details) {
        return deviceService.getAssetOnboardCount(username, vdmsid, dockername, search_sort_filter_details);
    }

    /**
     * Returns the set of assignees for onboarded assets.
     *
     * @param username the requesting user
     * @param vdms_id  the VDMS identifier
     * @return the set of assignee identifiers
     */
    public Set<String> getAssetOnboardAssignees(String username, String vdms_id) {
        return deviceService.getAssetOnboardAssignees(username, vdms_id);
    }

    /**
     * Returns VDMS property and sync details.
     *
     * @param username the requesting user
     * @param vdmsId   the VDMS identifier
     * @return the VDMS property details as a {@link VdmsDTO}
     */
    public VdmsDTO getPropertyDetails(String username, String vdmsId) {
        return vdmsRepository.getSyncDetailsForADC();
    }
}
