// Generated by delombok at Wed May 13 12:29:16 IST 2026
package io.sclera.service;

import java.math.BigInteger;
import java.util.*;
import java.util.stream.Collectors;
import com.alibaba.fastjson.JSONObject;
import com.fasterxml.jackson.core.JsonProcessingException;
import io.sclera.Repository.VdmsRepository;
import io.sclera.dto.FloorDTO;
import io.sclera.dto.LocationDTO;
import io.sclera.dto.RecordChecklistDTO;
import io.sclera.dto.touchscreen.settings.VdmsDTO;
import io.sclera.integration.dto.ResponseDTO;
//import io.sclera.service.touchscreen.VdmsService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.fasterxml.uuid.Generators;
import io.sclera.Repository.BuildingRepository;
import io.sclera.dto.BuildingDTO;
import javax.servlet.http.HttpServletRequest;

@Service
public class BuildingService {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(BuildingService.class);
    @Autowired
    BuildingRepository buildingRepository;
    @Autowired
    FloorService floorservice;
    @Autowired
    APICallService apiCallService;
    @Autowired
    LocationService locationService;
//    @Autowired
//    VdmsService vdmsService;
    @Autowired
    WebClientService webClientService;
    @Autowired
    RecordChecklistService recordChecklistService;
    @Autowired
    UserActionLogService userActionLogService;
    @Autowired
    VdmsRepository vdmsRepository;
    @Autowired
    APICallService apicallService;

    public void upsertBuildingByVdmsId(BuildingDTO buildingdto, String vdms_id) {
        Set<String> building_ids = buildingRepository.getBuildingIdsByVdmsId(vdms_id);
        if (building_ids != null && building_ids.size() > 0) {
            if (compareIds(building_ids, buildingdto.getBuilding_id())) {
                System.out.println("#############################################");
                log.info("Building IDs: {}", building_ids);
                log.info("Building DTO ID: {}", buildingdto.getBuilding_id());
                updateBuildingByBuildingId(buildingdto);
            } else {
                System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
                log.info("Building IDs: {}", building_ids);
                log.info("Building DTO ID: {}", buildingdto.getBuilding_id());
                addBuildingByVdmsId(buildingdto, vdms_id);
            }
        } else {
            addBuildingByVdmsId(buildingdto, vdms_id);
        }
    }

    public void updateBuildingByBuildingId(BuildingDTO buildingdto) {
        BigInteger timestamp = BigInteger.valueOf(System.currentTimeMillis());
        int rowsAffected = buildingRepository.updateBuildingByBuildingId(buildingdto.getName(), buildingdto.getBuilding_id(), timestamp);
        if (rowsAffected > 0) {
            syncBuildingToADCServer(buildingdto);
        }
        floorservice.upsertFloorsByBuildingId(buildingdto.getFloors(), buildingdto.getBuilding_id());
    }

    public void syncBuildingToADCServer(BuildingDTO buildingDTO) {
        try {
            VdmsDTO vdmsDetails = vdmsRepository.getSyncDetailsForADC();
            if (buildingDTO.getBuilding_id() != null && !buildingDTO.getBuilding_id().isEmpty()) buildingDTO.setId(buildingDTO.getBuilding_id());
            Boolean status = apiCallService.syncBuildingToADC(buildingDTO, vdmsDetails.getCustomer_org_id(), vdmsDetails.getAdc_configuration_id());
            log.info("Building synced to ADC with status: {}", status);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public String addBuildingByVdmsId(BuildingDTO buildingdto, String vdms_id) {
        if (buildingdto.getBuilding_id() == null) {
            String id = Generators.timeBasedGenerator().generate().toString();
            buildingdto.setBuilding_id(id);
        }
        BigInteger timestamp = BigInteger.valueOf(System.currentTimeMillis());
        int rowsAffected = buildingRepository.addBuildingByVdmsId(buildingdto.getBuilding_id(), buildingdto.getName(), vdms_id, timestamp);
        if (rowsAffected > 0) {
            syncBuildingToADCServer(buildingdto);
        }
        floorservice.upsertFloorsByBuildingId(buildingdto.getFloors(), buildingdto.getBuilding_id());
        return buildingdto.getBuilding_id();
    }

    public boolean compareIds(Set<String> building_ids, String building_id) {
        return building_ids.stream().anyMatch(b -> b.equals(building_id));
    }

    //delete building not tagged to a floor
    public void deleteUnlinkedBuildings() {
        Set<String> unlinkedBuildingIds = buildingRepository.getUnlinkedBuildingIds();
        for (String buildingId : unlinkedBuildingIds) {
            buildingRepository.deleteById(buildingId);
        }
    }

    public void synclocationbyId(String location_id, String vdms_id) {
        BuildingDTO Building = null;
        try {
            Building = apiCallService.addSingleBuildingObject(location_id, vdms_id);
        } catch (Exception e) {
        }
        // TODO: handle exception
        if (Building != null) {
            this.upsertBuildingByVdmsId(Building, vdms_id);
        }
    }

    /**
     * ********************************************************************** new Building changes *******************************************************************
     */
    public Set<BuildingDTO> upsertBuildingsByVdmsId(String username, String vdms_id, Set<BuildingDTO> buildings, HttpServletRequest httpServletRequest) {
        String action;
        for (BuildingDTO building : buildings) {
            action = "UPDATE";
            if (building.getBuilding_id() == null) {
                building.setBuilding_id(Generators.timeBasedGenerator().generate().toString());
                action = "ADD";
            }
            this.upsertBuildingById(building, vdms_id, username, action, httpServletRequest);
            if (building.getFloors() != null) {
                Set<FloorDTO> floors = floorservice.upsertFloorsByBuildingId(username, vdms_id, building.getBuilding_id(), building.getFloors(), httpServletRequest);
                building.setFloors(floors);
            }
        }
        return buildings;
    }

    private void upsertBuildingById(BuildingDTO building, String vdms_id, String username, String action, HttpServletRequest httpServletRequest) {
        try {
            BigInteger timestamp = BigInteger.valueOf(System.currentTimeMillis());
            int rowsAffected = buildingRepository.upsertBuildingsByVdmsId(building.getBuilding_id(), building.getName(), vdms_id, building.getCode(), timestamp);
            if (rowsAffected > 0) {
                syncBuildingToADCServer(building);
            }
            if (action.equals("ADD")) {
                userActionLogService.addUserAction(username, "maps", action, "A Building with name : " + building.getName() + " and id: " + building.getBuilding_id() + " is added", "success", "building", building.getBuilding_id());
                log.info("endpoint: {},upsertBuildingById, description: A new building is added,  params: building: {}", httpServletRequest.getRequestURI(), building);
            } else {
                userActionLogService.addUserAction(username, "maps", action, "A Building with name : " + building.getName() + " and id: " + building.getBuilding_id() + " is updated", "success", "building", building.getBuilding_id());
                log.info("endpoint: {},upsertBuildingById, description: A building is updated, params: building: {}", httpServletRequest.getRequestURI(), building);
            }
        } catch (Exception e) {
            log.error("Error : ", e);
            if (action.equals("ADD")) {
                userActionLogService.addUserAction(username, "maps", action, " Unable to add building with name: " + building.getName() + " and id: " + building.getBuilding_id(), "failed", "building", building.getBuilding_id());
                log.error("Exception in ADD building, endpoint: {} ,  Error message : ", httpServletRequest.getRequestURI(), e);
            } else {
                userActionLogService.addUserAction(username, "maps", action, " Unable to update building with name: " + building.getName() + " and id: " + building.getBuilding_id(), "failed", "building", building.getBuilding_id());
                log.error("Exception in UPDATE building, endpoint: {} ,  Error message : ", httpServletRequest.getRequestURI(), e);
            }
        }
    }

    public BuildingDTO getBuildingByLocationId(String username, String vdms_id, String location_id) {
        FloorDTO floor = floorservice.getFloorByLocationId(location_id);
        if (floor != null) {
            BuildingDTO building = buildingRepository.getBuildingByFloorId(floor.getFloor_id());
            if (building != null) {
                Set<FloorDTO> floors = new HashSet<>();
                floors.add(floor);
                building.setFloors(floors);
            }
            return building;
        }
        return null;
    }

    public Set<BuildingDTO> getBuildingsByVdmsId(String vdms_id, String field, String field_id) {
        Set<BuildingDTO> buildings = buildingRepository.getBuildingsByVdmsId(vdms_id);
        List<String> building_ids = buildings.stream().map(BuildingDTO::getBuilding_id).collect(Collectors.toList());
        Set<RecordChecklistDTO> allRecordChecklist = recordChecklistService.getAllRecordChecklistByBuildings(Collections.singletonList("all"), Collections.singletonList("all"), building_ids);
        for (BuildingDTO buildingDTO : buildings) {
            if (field != null) {
                Map<String, Long> defaultCounts = new HashMap<>();
                defaultCounts.put("tagged", 0L);
                defaultCounts.put("inspection", 0L);
                defaultCounts.put("scheduled_services", 0L);
                defaultCounts.put("reactive_services", 0L);
                Map<String, Long> computedCounts = allRecordChecklist.stream().filter(recordChecklistDTO -> recordChecklistDTO.getBuilding_id().equals(buildingDTO.getBuilding_id())).collect(Collectors.groupingBy(record -> {
                    String type = record.getRecord_type();
                    boolean hasInspectionId = record.getInspection_record_id() != null;
                    if ((field.equals("all_task") || field.equals("tagged")) && "checklist".equals(type) && !hasInspectionId) return "tagged";
                    if ((field.equals("all_task") || field.equals("inspection")) && "checklist".equals(type) && hasInspectionId) return "inspection";
                    if ((field.equals("all_task") || field.equals("scheduled_services")) && "service".equals(type) && hasInspectionId) return "scheduled_services";
                    if ((field.equals("all_task") || field.equals("reactive_services")) && "service".equals(type) && !hasInspectionId) return "reactive_services";
                    return "unknown"; // Exclude unmatched records
                }, Collectors.counting()));
                defaultCounts.putAll(computedCounts);
                JSONObject counts = new JSONObject();
                if (field.equals("all_task") || field.equals("tagged")) {
                    JSONObject tagged_count = new JSONObject();
                    tagged_count.put("all_count", defaultCounts.get("tagged"));
                    counts.put("tagged_procedure", tagged_count);
                }
                if (field.equals("all_task") || field.equals("reactive_services")) {
                    JSONObject reactive_service_count = new JSONObject();
                    reactive_service_count.put("all_count", defaultCounts.get("reactive_services"));
                    counts.put("service_requests", reactive_service_count);
                }
                if (field.equals("all_task") || field.equals("scheduled_services")) {
                    JSONObject scheduled_service_count = new JSONObject();
                    scheduled_service_count.put("all_count", defaultCounts.get("scheduled_services"));
                    counts.put("service_checklist", scheduled_service_count);
                }
                if (field.equals("all_task") || field.equals("inspection")) {
                    JSONObject inspection_count = new JSONObject();
                    inspection_count.put("all_count", defaultCounts.get("inspection"));
                    counts.put("inspection_checklist", inspection_count);
                }
                buildingDTO.setCounts(counts);
            }
        }
//        System.out.println(bulidingCount);
//        for (BuildingDTO buildingDTO : buildings) {
//            if (field != null) {
//                buildingDTO.setCounts(recordChecklistService.getAllMapCounts(field, field_id, "all", "all", buildingDTO.getBuilding_id()));
//                buildingDTO.setCounts(bulidingCount.get(buildingDTO.getBuilding_id()));
//            }
//        }
        return buildings;
    }

    public void deleteBuildingsByIdsSync(String username, String vdmsid, Set<String> buildingIds) {
        log.info("deleteBuildingsByIds method called with buildingIds: {}", buildingIds);
        List<BuildingDTO> buildings = getBatchBuildingsByPagination(buildingIds);
        if (buildings == null || buildings.isEmpty()) {
            return;
        }
        log.info("Getting floors by building ids");
        List<FloorDTO> floors = floorservice.getFloorsByBuildingIds(buildingIds);
        log.info("Processing floor deletions for floors: {}", floors.size());
        floorservice.processFloorDeletions(username, vdmsid, floors);
        buildingRepository.deleteAllById(buildingIds);
    }

    public List<BuildingDTO> getBatchBuildingsByPagination(Set<String> buildingIds) {
        List<BuildingDTO> buildings = new ArrayList<>();
        int pageNo = 1;
        int pageSize = 500;
        while (true) {
            int offset = pageSize * (pageNo - 1);
            List<BuildingDTO> batchResults = buildingRepository.getBatchBuildingsByPagination(buildingIds, pageSize, offset);
            if (batchResults == null || batchResults.isEmpty()) {
                break;
            }
            buildings.addAll(batchResults);
            if (batchResults.size() < pageSize) {
                break;
            }
            pageNo++;
        }
        return buildings;
    }

    public void deleteBuildingsByIds(String username, String vdmsid, Set<String> building_ids, HttpServletRequest httpServletRequest) {
        for (String id : building_ids) {
            deleteBuildingById(username, vdmsid, id, httpServletRequest);
        }
    }

    private void deleteBuildingById(String username, String vdmsid, String building_id, HttpServletRequest httpServletRequest) {
        String endpoint = httpServletRequest != null ? httpServletRequest.getRequestURI() : "SOCKET CALL";
        Set<FloorDTO> floors = floorservice.getFloorsDetailsByBuildingId(building_id);
        List<FloorDTO> floorDetails = new ArrayList<>(floors);
        String data = webClientService.deleteFloorMapsByImageUrl(vdmsid, floorDetails);
        if (data != null) {
            floorservice.deleteFloorsByBuildingId(vdmsid, building_id, username, httpServletRequest);
            BuildingDTO buildingDTO = this.getBuildingDetailsByBuildingId(building_id);
            try {
                buildingRepository.deleteById(buildingDTO.getBuilding_id());
                //ADC sync for delete
                syncDeleteBuildingToADC(building_id);
                userActionLogService.addUserAction(username, "maps", "DELETE", "A Building with name : " + buildingDTO.getName() + " and id: " + building_id + " is deleted.", "success", "building", building_id);
                log.info("endpoint: {}, deleteBuildingById,  params: buildingDTO: {} ", endpoint, buildingDTO);
            } catch (Exception e) {
                userActionLogService.addUserAction(username, "maps", "DELETE", "Unable to delete building with name : " + buildingDTO.getName() + " and id: " + building_id, "failed", "building", building_id);
                log.error("Exception in Deleting Building By Id, endpoint: {}, Error message: ", endpoint, e);
            }
        }
    }

    public void syncDeleteBuildingToADC(String buildingId) {
        try {
            VdmsDTO vdmsDetails = vdmsRepository.getSyncDetailsForADC();
            List<String> buildingIds = Collections.singletonList(buildingId);
            Boolean status = apicallService.deleteBuildingFromADC(vdmsDetails.getCustomer_org_id(), vdmsDetails.getAdc_configuration_id(),  // make sure propertyId is correct
            buildingIds);
            log.info("Building DELETE synced to ADC successfully, Building ID: {}, Status: {}", buildingId, status);
        } catch (Exception e) {
            log.error("Exception while syncing deleted building to ADC, Building ID: {}", buildingId, e);
        }
    }

    //  syncLocationsFromBackend to be deleted after sync
    public Map<String, Object> syncLocationsFromBackend(HttpServletRequest httpServletRequest) {
        System.out.println("********************SYNC LOCATIONS FROM CLOUD************************************");
        //getting vdmsid of the sclera box
        String vdmsIdScleraBox = "VDMS400";
        // getting all buildings from location server..
        List<BuildingDTO> all_buildings = apiCallService.getAllLocations(vdmsIdScleraBox);
        log.info("\n***********************All Locations from CLOUD****************************\n{}", all_buildings);
        //Get all buildings from vdms server, before sync
        Set<BuildingDTO> vdms_buildings = this.getAllBuildingsBackendSync(vdmsIdScleraBox);
        log.info("\n***********************All Locations from VDMS BOX****************************\n{}", vdms_buildings);
        Set<String> building_ids = new HashSet<>();
        Set<String> floor_ids = new HashSet<>();
        Set<String> location_ids = new HashSet<>();
        for (BuildingDTO building : all_buildings) {
            building_ids.add(building.getBuilding_id());
            this.upsertBuildingById(building, vdmsIdScleraBox, "", "", httpServletRequest);
            //floor loop
            for (FloorDTO floor : building.getFloors()) {
                floor_ids.add(floor.getFloor_id());
                String image_url = floorservice.upsertFloorImageByBuildingFromBackend(floor);
                floor.setImage_url(image_url);
                floorservice.upsertFloorByBuildingIdsFromBackend(building.getBuilding_id(), floor);
                //Update floor path
                String path = apiCallService.getFloorPathByFloorId(null, vdmsIdScleraBox, building.getBuilding_id(), floor.getFloor_id());
                floorservice.updatePathByFloorId(null, floor.getFloor_id(), path, httpServletRequest);
                // for location
                for (LocationDTO location : floor.getLocations()) {
                    location_ids.add(location.getLocation_id());
                    // update  locations
                    locationService.upsertLocationByFloorIdBackendSync(floor.getFloor_id(), location);
                }
            }
        }
        if (vdms_buildings != null && vdms_buildings.size() > 0) {
            // delete building, floor and locations , which are deleted from server.
            return this.getMismatchedLocationsFromVdmsBackendSync(building_ids, floor_ids, location_ids, vdms_buildings, vdmsIdScleraBox);
        }
        return null;
    }

    private Map<String, Object> getMismatchedLocationsFromVdmsBackendSync(Set<String> building_ids, Set<String> floor_ids, Set<String> location_ids, Set<BuildingDTO> vdms_buildings, String vdms_id) {
        Map<String, Object> mismatched_locations = new HashMap();
        Set<Map<String, Object>> delete_buildings = new HashSet<>();
        Set<Map<String, Object>> delete_floors = new HashSet<>();
        Set<Map<String, Object>> delete_locations = new HashSet<>();
        Map<String, Object> location_object;
        for (BuildingDTO building : vdms_buildings) {
            if (compareIds(building_ids, building.getBuilding_id())) {
                if (building.getFloors() != null) {
                    for (FloorDTO floor : building.getFloors()) {
                        if (compareIds(floor_ids, floor.getFloor_id())) {
                            if (floor.getLocations() != null) {
                                for (LocationDTO location : floor.getLocations()) {
                                    if (!compareIds(location_ids, location.getLocation_id())) {
                                        location_object = new HashMap<>();
                                        location_object.put("building_id", building.getBuilding_id());
                                        location_object.put("building_name", building.getName());
                                        location_object.put("floor_id", floor.getFloor_id());
                                        location_object.put("floor_name", floor.getName());
                                        location_object.put("location_id", location.getLocation_id());
                                        location_object.put("location_name", location.getName());
                                        delete_locations.add(location_object);
                                    }
                                }
                            }
                        } else {
                            location_object = new HashMap<>();
                            location_object.put("building_id", building.getBuilding_id());
                            location_object.put("building_name", building.getName());
                            location_object.put("floor_id", floor.getFloor_id());
                            location_object.put("floor_name", floor.getName());
                            delete_floors.add(location_object);
                        }
                    }
                }
            } else {
                location_object = new HashMap<>();
                location_object.put("building_id", building.getBuilding_id());
                location_object.put("building_name", building.getName());
                delete_buildings.add(location_object);
            }
        }
        mismatched_locations.put("vdms_id", vdms_id);
        mismatched_locations.put("buildings", delete_buildings);
        mismatched_locations.put("floors", delete_floors);
        mismatched_locations.put("locations", delete_locations);
        return mismatched_locations;
    }

    private Set<BuildingDTO> getAllBuildingsBackendSync(String vdms_id) {
        Set<BuildingDTO> buildings = this.getBuildingsByVdmsId(vdms_id, null, null);
        for (BuildingDTO building : buildings) {
            Set<FloorDTO> floors = floorservice.getFloorsByBuildingId(null, null, building.getBuilding_id(), null, null);
            for (FloorDTO floor : floors) {
                floor.setLocations(locationService.getLocationsByFloorId(floor.getFloor_id(), vdms_id));
            }
            building.setFloors(floors);
        }
        return buildings;
    }

    //  syncLocationsFromBackend to be deleted after sync
    public Set<FloorDTO> syncFloorMaps(String vdms_id) {
        Set<BuildingDTO> buildings = this.getBuildingsByVdmsId(vdms_id, null, null);
        Set<FloorDTO> floors_response = new HashSet<>();
        for (BuildingDTO building : buildings) {
            Set<FloorDTO> floors = floorservice.getFloorsDetailsByBuildingId(building.getBuilding_id());
            for (FloorDTO floordto : floors) {
                FloorDTO floor = new FloorDTO();
                if (floordto.getImage_url() != null) {
                    floor.setFloor_id(floordto.getFloor_id());
                    floor.setImage_url(floordto.getImage_url());
                    if (floordto.getLocal_image_url() != null) {
                        floor.setLocal_image_url(floordto.getLocal_image_url());
                    } else {
                        floor.setLocal_image_url(floordto.getImage_url());
                    }
                    floors_response.add(floor);
                }
            }
        }
        return floors_response;
    }

    //  syncLocationsFromBackend to be deleted after sync
    public List<FloorDTO> updateFloorMaps(String vdms_id, List<FloorDTO> floorDTOS) {
        return floorservice.updateFloorImages(vdms_id, floorDTOS);
    }

    //  syncFloorMapsTiles to be deleted after sync
    public List<FloorDTO> syncFloorMapsTiles() {
        String vdmsIdScleraBox = "VDMS400";
        Set<BuildingDTO> buildings = this.getBuildingsByVdmsId(vdmsIdScleraBox, null, null);
        List<FloorDTO> syncFailedFloors = new ArrayList<>();
        for (BuildingDTO building : buildings) {
            Set<FloorDTO> floors = floorservice.getFloorsDetailsByBuildingId(building.getBuilding_id());
            if (floors != null && floors.size() > 0) {
                for (FloorDTO floordto : floors) {
                    List<FloorDTO> floors_response = new ArrayList<>();
                    if (floordto.getImage_url() != null) {
                        FloorDTO floor = floorservice.mapInitialPositionToCoordinates(floordto.getInitial_position(), floordto.getFloor_id());
                        floor.setImage_url(floordto.getImage_url());
                        floors_response.add(floor);
                        syncFailedFloors.addAll(floorservice.syncFloorMapsTiles(vdmsIdScleraBox, floors_response));
                    }
                }
            }
        }
        return syncFailedFloors;
    }

    private BuildingDTO getBuildingDetailsByBuildingId(String building_id) {
        return buildingRepository.getBuildingDetailsByBuildingId(building_id);
    }
    /************************************************************************* new Building changes ********************************************************************/
}
