// Generated by delombok at Wed May 13 12:29:22 IST 2026
package io.sclera.service;

import com.alibaba.fastjson.JSONArray;
import io.sclera.Repository.ClientBarCodeRepository;
import io.sclera.dto.ClientBarCodeDTO;
import io.sclera.queryrepository.ClientBarCodeQueryRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.HashSet;
import java.util.Set;

@Service
public class ClientBarCodeService {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(ClientBarCodeService.class);
    @Autowired
    APICallService apiCallService;
    @Autowired
    DataSource dataSource;
    @Autowired
    ClientBarCodeQueryRepository clientBarCodeQueryRepository;
    @Autowired
    ClientBarCodeRepository clientBarCodeRepository;

    public Integer getClientBarCodeCountByDeviceId(String deviceId) {
        log.info("getClientBarCodeCountByDeviceId");
        return clientBarCodeRepository.getClientBarCodeCountByDeviceId(deviceId);
    }

    public void syncAllClientBarCode(String vdmsId) {
        log.info("Syncing syncAllClientBarCode");
        Set<ClientBarCodeDTO> clientBarCodeInCloud = new HashSet<>();
        int pageNumber = 1;
        int pageSize = 100;
        while (true) {
            Set<ClientBarCodeDTO> clientBarCodeDtos = apiCallService.getAllClientBarCodeByVdmsId(vdmsId, pageNumber, pageSize);
            clientBarCodeInCloud.addAll(clientBarCodeDtos);
            if (clientBarCodeDtos.size() < pageSize) {
                break;
            } else {
                pageNumber++;
            }
        }
        log.info("BarCode size: {} ", clientBarCodeInCloud.size());
        this.updateIsDeletedForAllClientBarCode();
        this.upsertClientBarCodeInBatch(clientBarCodeInCloud);
        this.deleteOldClientBarCode();
    }

    private void deleteOldClientBarCode() {
        log.info("deleteOldClientBarCode");
        clientBarCodeRepository.deleteOldClientBarCode();
    }

    private void updateIsDeletedForAllClientBarCode() {
        log.info("updateIsDeletedForAllBarCode");
        clientBarCodeRepository.updateIsDeletedForAllClientBarCode();
    }

    public void upsertClientBarCodeInBatch(Set<ClientBarCodeDTO> clientBarCodeDTOS) {
        log.info("upsertBarCodeInBatch");
        try (Connection connection = dataSource.getConnection()) {
            PreparedStatement preparedStatementUpdate = connection.prepareStatement(clientBarCodeQueryRepository.getQueryForUpsertClientBarCode());
            int batchCounter = 0;
            int maxBatchLimit = 100;
            for (ClientBarCodeDTO clientBarCodeDTO : clientBarCodeDTOS) {
                try {
                    preparedStatementUpdate.setString(1, clientBarCodeDTO.getId());
                    preparedStatementUpdate.setString(2, clientBarCodeDTO.getAddedAt());
                    preparedStatementUpdate.setString(3, clientBarCodeDTO.getAddedBy());
                    preparedStatementUpdate.setString(4, clientBarCodeDTO.getClientBarCodeId());
                    preparedStatementUpdate.setString(5, clientBarCodeDTO.getDeviceId());
                    preparedStatementUpdate.setString(6, clientBarCodeDTO.getLocationId());
                    preparedStatementUpdate.setString(7, clientBarCodeDTO.getUpdatedTime() == null ? null : String.valueOf(clientBarCodeDTO.getUpdatedTime()));
                    preparedStatementUpdate.setString(8, clientBarCodeDTO.getUpdatedBy());
                    preparedStatementUpdate.setString(9, clientBarCodeDTO.getVdmsId());
                    preparedStatementUpdate.setString(10, clientBarCodeDTO.getBatchId());
                    preparedStatementUpdate.addBatch();
                    batchCounter++;
                    if (batchCounter == maxBatchLimit) {
                        preparedStatementUpdate.executeBatch();
                        log.info("added 100 barcode in a batch");
                        preparedStatementUpdate.clearBatch();
                        batchCounter = 0;
                    }
                } catch (Exception e) {
                    log.error("Exception in batch update of barcode", e);
                }
            }
            if (batchCounter > 0) {
                preparedStatementUpdate.executeBatch();
                log.info("Excecuted batch update of: {} barcode ", batchCounter);
            }
            preparedStatementUpdate.close();
        } catch (Exception e) {
            log.error("Exception in batch update of barcode", e);
        }
    }

    public JSONArray getLocationIdsTaggedToClientBarCode(String vdmsid) {
        log.info("getLocationIdsTaggedToClientBarCode");
        return clientBarCodeRepository.getLocationIdsTaggedToClientBarCode(vdmsid);
    }

    public JSONArray getDeviceIdsTaggedToClientBarCode(String vdmsid) {
        log.info("getDeviceIdsTaggedToClientBarCode");
        return clientBarCodeRepository.getDeviceIdsTaggedToClientBarCode(vdmsid);
    }

    public void syncClientBarCode(String vdmsId) {
        log.info("syncClientBarCode");
        Set<ClientBarCodeDTO> clientBarCodeInCloud = new HashSet<>();
        int pageNumber = 1;
        int pageSize = 100;
        while (true) {
            Set<ClientBarCodeDTO> clientBarCodeDtos = apiCallService.getSyncedClientBarCodeByVdmsId(vdmsId, pageNumber, pageSize);
            clientBarCodeInCloud.addAll(clientBarCodeDtos);
            if (clientBarCodeDtos.size() < pageSize) {
                break;
            } else {
                pageNumber++;
            }
        }
        log.info("BarCode size: {} ", clientBarCodeInCloud.size());
        this.upsertClientBarCodeInBatch(clientBarCodeInCloud);
    }

    public Set<ClientBarCodeDTO> getBarCodesByLocationIds(Set<String> locationIds) {
        log.info("getBarCodesByLocationIds");
        return clientBarCodeRepository.getBarCodesByLocationIds(locationIds);
    }

    public Set<ClientBarCodeDTO> getBarCodesByDeviceIds(Set<String> deviceIds) {
        log.info("getBarCodesByDeviceIds");
        return clientBarCodeRepository.getBarCodesByDeviceIds(deviceIds);
    }
}
