package io.sclera.service;

import java.io.IOException;
import java.math.BigInteger;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.itextpdf.text.pdf.PdfPCell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.json.JSONException;
import org.springframework.web.multipart.MultipartFile;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import io.sclera.dto.*;
import io.sclera.dto.touchscreen.*;
import io.sclera.dto.touchscreen.assetmapper.AssetDTO;
import io.sclera.integration.dto.ResponseDTO;
import io.sclera.models.*;

/** Service contract for {@link io.sclera.service.DeviceService}. */
public interface DeviceService {
    String getServer_asset_images_absolute_path();
    void setServer_asset_images_absolute_path(String server_asset_images_absolute_path);
    String getServer_asset_images_url();
    void setServer_asset_images_url(String server_asset_images_url);
    String getServer_asset_ocr_images_absolute_path();
    void setServer_asset_ocr_images_absolute_path(String server_asset_ocr_images_absolute_path);
    String getServer_asset_ocr_images_url();
    void setServer_asset_ocr_images_url(String server_asset_ocr_images_url);
    Set<DeviceDTO> listAllDevicebyVdmsidAndDockerName(String username, String vdmsid, String dockername);
    Set<DeviceDTO> getfilterdevices(String username, String vdmsid, String dockername, String condition, String searchKey, Integer pageNo, Integer pageSize);
    void upsertDeviceListByVdmsIdAndDockerName(List<DeviceDTO> deviceList, String username, String vdmsid, String dockername, String assignee);
    DeviceDTO editDeviceByDeviceID(String username, String vdmsid, String dockername, String device_id, DeviceDTO devicedto, HttpServletRequest httpServletRequest, String assignee) throws JSONException, IOException;
    void tagProductImages(ProductDTO productdto) throws IOException;
    void retagProductImages(ProductDTO productdto) throws IOException;
    String addImageByUrl(String link, byte[] image, String directory, String id) throws IOException;
    String getImageExtensionByImageUrl(String image_url);
    String addFileToServer(byte[] image, String directory, String file_name, String file_extension) throws IOException;
    void removeFileFromServer(String absolute_path, String file_name, String file_extension);
    String linkVendorByVendorIdAndDeviceId(String username, String vdmsid, String dockername, String device_id, PhonebookAddressDto phonebookaddressdto, String vendor_type, HttpServletRequest httpServletRequest);
    void unlinkVendorByVendorIdAndDeviceId(String username, String dockername, String phoneaccount, String device_id, String vendor_type, HttpServletRequest httpServletRequest);
    void multiDeviceUpdate(String username, String vdmsid, String dockername, Set<MultiDeviceDTO> multidevicedtos, HttpServletRequest httpServletRequest, String assignee) throws JSONException, IOException;
    Set<DeviceDTO> quickUpdate(String username, String vdmsid, String dockername, TagDeviceOrLocationDTO tagDeviceOrLocationDTO, HttpServletRequest httpServletRequest, String assignee) throws IOException;
    Set<DeviceDTO> getAllSubsystemDevices(String username, String vdmsid, String dockername, String device_id, String condition);
    Set<DeviceDTO> updateDeviceDetailsByIds(String username, String vdmsid, String dockername, Set<String> deviceIds);
    Set<DeviceDTO> getDeviceNamesByVdmsIdAndDockerName(String username, String vdmsid, String dockername);
    void addVirtualDeviceByVdmsIdAndDockerName(String username, String vdmsid, String dockername, String virtualDevicesDTO, List<MultipartFile> asset_images, HttpServletRequest httpServletRequest, String assignee);
    Integer getVirtualDeviceStatus(String dockername, String ip_address);
    void editVirtualDeviceByVirtualDeviceId(String username, String vdmsid, String dockername, Set<DeviceDTO> virtualDevices, HttpServletRequest httpServletRequest) throws IOException;
    void deleteVirtualDeviceByVirtualDeviceId(String username, String vdmsid, String dockername, String virtual_device_id, String assignee);
    void softDeleteDevicesById(String username, String vdmsid, String dockername, Set<String> deviceIds, HttpServletRequest httpServletRequest, String assignee);
    void deleteDevicesById(String username, String vdmsid, String dockername, Set<String> deviceIds, HttpServletRequest httpServletRequest, String assignee);
    DeviceDTO updateVirtualDeviceStatusByVirtualDeviceId(String username, String vdmsid, String dockername, String virtual_device_id, DeviceDTO virtualdevicedto);
    void updateAllVirtualDeviceStatus();
    void updateDeviceSnmpCount(String device_id);
    void updateDeviceSnmpStatus(String snmp_device_id);
    void updateDeviceSnmpStatusByDeviceId(String device_id);
    void updateDeviceInterfaceCount(String device_id);
    void updateDeviceNotesCount(String device_id);
    void updateDeviceTicketCount(String device_id);
    void updateDeviceTicketStatus(String device_id);
    void updateDeviceBacnetCount(String bacnet_device_id, String bacnet_object_id);
    void updateDeviceBacnetCountByDeviceId(String device_id);
    void updateDeviceBacnetStatus(String bacnet_device_id, String bacnet_object_id);
    void updateDeviceBacnetStatusByDeviceId(String device_id);
    void updateDeviceLorawanCount(String lorawan_sensor_id);
    void updateDeviceLorawanCountByDeviceId(String device_id);
    void updateDeviceLorawanStatus(String lorawan_sensor_id);
    void updateDeviceLorawanStatusByDeviceId(String device_id);
    void updateDeviceDisruptiveCount(String disruptive_sensor_id);
    void updateDeviceDisruptiveCountByDeviceId(String device_id);
    void updateDeviceDisruptiveStatus(String disruptive_sensor_id);
    void updateDeviceDisruptiveStatusByDeviceId(String device_id);
    void updateDeviceMyDevicesCount(String my_devices_sensor_id);
    void updateDeviceMyDevicesCountByDeviceId(String device_id);
    void updateDeviceMyDevicesStatus(String my_devices_sensor_id);
    void updateDeviceMyDevicesStatusByDeviceId(String device_id);
    void updateDeviceMonnitCount(String monnit_sensor_id);
    void updateDeviceMonnitCountByDeviceId(String device_id);
    void updateDeviceMonnitStatus(String monnit_sensor_id);
    void updateDeviceMonnitStatusByDeviceId(String device_id);
    void updateDevicePelicanCount(String pelican_sensor_id);
    void updateDevicePelicanCountByDeviceId(String device_id);
    void updateDevicePelicanStatus(String pelican_sensor_id);
    void updateDevicePelicanStatusByDeviceId(String device_id);
    void updateDeviceKNXCount(String knx_device_address, String knx_group_address);
    void updateDeviceKNXCountByDeviceId(String device_id);
    void updateDeviceKNXStatus(String knx_device_address, String knx_group_address);
    void updateDeviceKNXStatusByDeviceId(String device_id);
    void updateDeviceMeasureCountByDeviceId(String device_id);
    void updateDeviceDocumentsCountByDeviceId(String device_id);
    void updateDeviceMediaCountByDeviceId(String device_id);
    void updateDeviceCheckListsCountByDeviceId(String device_id);
    void updateDeviceSnmpObjectCountByDeviceId(String device_id);
    void updateDeviceSnmpObjectStatus(String snmp_device_configuration_id, String snmp_object_oid);
    void updateDeviceSnmpObjectStatusByDeviceId(String device_id);
    AllSensorsDTO getDeviceSensors(String username, String vdmsid, String dockername, String device_id);
    Set<DeviceListDTO> listDevicesTs(String networkname, String buildingid, String floorid, String locationid, Integer devicestatus);
    Set<DeviceListDTO> listDevicesByPaginationTs(String networkname, String buildingid, String floorid, String locationid, Integer status, Integer pagesize, Integer offset, Integer virtual_device_type);
    DeviceDetailsDTO getDeviceInfoById(String deviceid);
    Map<String, Integer> onlineOfflineCount();
    void deviceUpsertbyId(String dockername, List<DeviceMonitorDTO> deviceMonitors, String assignee);
    void updateVendorByMacAddress(String device_id, String mac_address);
    void getDeviceHostNameByIP(String dockername, String device_id, String ip_address);
    List<DeviceIPAddressDTO> getDeviceIPAddressByDeviceId(String device_id);
    void insertDevicesHistory(String dockername, List<DeviceHistoryDTO> devicesHistory);
    void updateOnlineStatus(DeviceMonitorDTO device);
    void updateofflineStatus(DeviceMonitorDTO device);
    Integer getDeviceStatus(String DeviceId);
    List<DeviceMonitorDTO> getDeviceListMonitor(String dockername);
    List<DeviceMonitorDTO> getDeviceListMonitorIp(String dockername);
    List<SnmpValuesDTO> getDeviceListSnmp(String dockername);
    SnmpValuesDTO getDeviceSnmpByDeviceId(String dockername, String device_id);
    void updateSnmpParent(String dockername, SnmpValuesDTO device);
    void updateTopology(String username, String vdmsid, String dockername, List<DeviceTopologyDTO> devices, HttpServletRequest httpServletRequest);
    String getGatewayId(String dockername);
    Set<DeviceListDTO> listofflinedeviceByParentTs();
    Set<DeviceListDTO> listofflinedeviceByParentByPaginationTs(Integer pagesize, Integer offset);
    DeviceListDTO DeviceInfoById(String deviceId);
    void unLinkVendorByVendorIdAndVdmsId(String phoneaccountid, String vdmsid);
    List<DeviceDTO> listAlldevices();
    void updateDevicesDisplayNameById(String id, String display_name);
    void updateDeviceVendorById(String id, String vendor);
    AlertDTO getDeviceAlertInfoByDeviceId(String device_id);
    Integer getDeviceCountForIOC(String username, String vdmsid, String dockername);
    Map<String, Integer> getDeviceCount(String username, String vdmsid, String dockername,String assignee);
    DeviceTopologyDTO getDeviceObjectbyId(List<DeviceTopologyDTO> devices, String id);
    List<DeviceTopologyDTO> listFormatedDevicesForAllNetwork(List<DeviceTopologyDTO> devices);
    List<DeviceTopologyDTO> listTopologyDevicesByDockerName(String username, String vdmsid, String dockername);
    void resetTopologyByDockername(String username, String vdmsid, String dockername, HttpServletRequest httpServletRequest);
    Set<DevicedataDTO> getAllDevices();
    List<String> getUniqueDeviceTypes(String network_name, String floor_id);
    List<String> getUniqueAssetGroups(String network_name);
    List<String> getUniqueCategory(String network_name);
    List<String> getUniqueAssignedUserEmail(String vdms_id,String network_name);
    List<String> getUniqueSubCategory(String network_name, String category);
    String getDevicesByTypeCount(String network_name, String floor_id, Set<String> types);
    void updateDeviceLocation(String location_id, String username);
    void updateDevicePosition(List<DeviceDTO> devicePositions, String vdmsid, String username, HttpServletRequest httpServletRequest);
    List<DeviceDTO> listDevicebyDockerIntegration(String dockername);
    Set<DeviceDTO> getParentDeviceByPagination(String username, String vdmsid, String searchKey, Integer pageno, Integer pagesize, Set<String> dockernames, Set<String> types, Set<String> virtual_device_types);
    Set<DeviceDTO> getParentDeviceById(String username, String vdmsid, String dockername, Set<DeviceDTO> parent_devices, HttpServletRequest httpServletRequest);
    Set<DeviceDTO> getSubsystemParentDevicesByPagination(String username, String vdmsid, String dockername, String condition, Integer pageno, Integer pagesize, String assignee);
    Set<DeviceDTO> getSubsystemDevicesByPagination(String username, String vdmsid, String dockername, String device_id, String condition, Integer pageno, Integer pagesize, String assignee);
    Set<DeviceDTO> getAllSubsystemDevicesByPagination(String username, String vdmsid, String dockername, String device_id, String condition, Integer pageno, Integer pagesize, String assignee);
    void updateParentSubsystemCount(String device_id);
    DeviceDTO getSubsystemParentDeviceInfo(String username, String vdmsid, String dockername, String device_id, String parent_id);
    void archiveDevices(String username, String vdmsid, String dockername, Integer archive, Set<String> deviceIds, HttpServletRequest httpServletRequest, String assignee);
    void upsertVirtualDeviceByAssetMapper(DeviceDTO virtual_device, String username);
    void upsertProductDetailsForVirtualDevice(String username, String vdmsid, String dockername, DeviceDTO virtual_device);
    List<AssetDTO> getUntaggedProductDevicesByPagination(Integer pageNo, Integer pageSize);
    Integer getUntaggedProductDevicesCount();
    void updateDeviceMatchedProductIds(String device_id, String matched_product_ids);
    List<AssetDTO> getAssetMapperDevicesByIdList(List<String> device_ids);
    AssetDTO getAssetMapperDevicesById(String device_id);
    List<AssetDTO> getAssetMapperSubSystemDevicesById(String device_id);
    void updateMatchedDeviceProduct(String username, String vdmsid, String dockername, DeviceDTO device, HttpServletRequest httpServletRequest);
    void updateDeviceProductDetails(DeviceDTO device);
    List<DeviceDTO> getAllDeviceByVdmsIdAndDockerName(String username, String vdmsid, String dockername, Integer pagesize, Integer offset);
    Map<String, Integer> getDeviceStatusCountTS(String networkname, String buildingid, String floorid, String locationid);
    void updateDeviceProductPortStatus(String vdms_id, Set<String> device_ids);
    void updateMultipleDevicesProductPortStatus(String vdms_id, Set<DeviceDTO> devices);
    Optional<Device> findById(String id);
    List<String> getDevicesBySubSystemParentId(String device_id);
    void updateSubsystemParentDevice(String device_id, String subsystem_parent_id);
    void updateDeviceMeasuringInstrumentStatus(String measuring_instrument_id);
    void updateDeviceMeasuringInstrumentStatusByDeviceId(String device_id);
    void updateDeviceProductModel(String device_id, String mac_by_vendor, String model);
    MultiDeviceDTO setProductVendorsForDevices(MultiDeviceDTO multidevicedto, String previous_product_id);
    void getProductDetails(String username, String vdmsid, String dockername, String device_id, String product_id, String previous_product_id);
    void deleteDeviceGlobalProductDetails(String device_id);
    void getProductDetailsByProductId(String username, String vdmsid, String dockername, String product_id, String device_id);
    MultiDeviceDTO updateVendorPhoneBookDetails(String username, String vdmsid, String dockername, MultiDeviceDTO multiDeviceDTO);
    void addPhoneBookAddressDetailsById(String username, String vdmsid, String dockername, PhonebookAddressDto phonebook);
    MultiDeviceDTO mapProductVendorsToMultideviceDTO(DevicesDTO devicesDTO);
    DeviceDTO getDeviceDetails(String checklist_id);
    void updateDeviceRecordChecklistStatusByDeviceId(String device_id, String record_type);
    void updateDeviceRecordChecklistCount(String device_id, String record_type);
    void updateDeviceRecordChecklistStatusById(String device_id, String record_type);
    void updateDeviceDaintreeCountByDeviceId(String device_id);
    void updateDeviceQrcodeCountByDeviceId(String device_id);
    List<ConditionsDTO> getDeviceAlertMessages(String username, String vdmsid, String dockername);
    void updateDeviceDainTreeStatus(String daintree_device_id);
    void updateDeviceDaintreeStatusByDeviceId(String device_id);
    void modelResetbyDockerName(String docker_name);
    DeviceAlertDTO getDeviceAlertInfoById(String device_id);
    RoomStatusDTO getRoomStatusByDeviceId(String deviceid);
    List<DeviceMonitorSpaceDTO> getRoomStatusByLocationId(String deviceid);
    void upsertAssetImages(String username, String vdms_id, List<String> device_ids, List<MultipartFile> asset_images, HttpServletRequest httpServletRequest);
    void deleteAssetImages(String username, String vdms_id, List<DeviceDTO> deviceDTOS, HttpServletRequest httpServletRequest);
    void deleteDeviceImages(String username, String vdms_id, List<DeviceDTO> deviceDTOS, String category, HttpServletRequest httpServletRequest);
    String getAssetImageUrls(String username, String vdms_id, String device_id);
    String getAssetImageUrlsCategory(String username, String vdms_id, String device_id);
    Set<DeviceDTO> getAllDevicesPagination(String username, String vdmsid, String group, String searchkey, Integer pageno, Integer pagesize, JSONObject filterObject);
    void getDeviceConditionStatus(String deviceId, Integer status);
    void scheduleDeviceAlertJob(String job_type, DeviceConditionsDTO deviceCondition);
    void replaceDeviceAlertJob(String job_type, DeviceConditionsDTO deviceCondition, String job_key);
    void deleteDeviceAlertJob(String conditionId);
    void sendDeviceEmailAlerts(DeviceConditionsDTO deviceConditionsDTO, DeviceAlertDTO deviceAlert, AlertProfileDTO alertProfile, BigInteger current_timestamp, Integer status);
    DeviceAlertDTO getDeviceConditionAlertInfoById(String device_id);
    Set<DeviceDTO> listAllDeviceByVdmsId(String vdms_id);
    void updateDeviceEcobeeCountByDeviceId(String device_id);
    void updateDeviceEcobeeStatusByDeviceId(String device_id);
    void updateDeviceEcobeeStatus(String ecobee_sensor_id);
    List<DeviceSensorsDTO> getDeviceSensorsWithQrCodeDetails(String vdms_id, List<DeviceSensorsDTO> deviceSensors);
    List<DeviceSensorsDTO> getDevicesByType(String vdms_id, String network_name, String floor_id, Set<String> types);
    List<DeviceSensorsDTO> getDevicesByTypePagination(String vdms_id, String network_name, String floor_id, Set<String> types, Integer pagesize, Integer pageno);
    Set<DeviceDTO> getDevicesWithQrCodeCount(String vdms_id, Set<DeviceDTO> devices);
    DeviceDTO getDeviceByDeviceId(String username, String vdmsid, String dockername, String device_id);
    Set<DeviceDTO> getDevicesByIdList(String vdms_id, Set<String> device_ids);
    Set<DeviceDTO> getFilterVirtualDevicesByPagination(String username, String vdmsid, String searchKey, Integer pageNo, Integer pageSize, Set<String> dockernames, Set<String> types, Set<String> virtual_device_types);
    List<DeviceDTO> getDeviceDetailsByDeviceIdList(Set<String> device_ids);
    DeviceDTO updateCustomFields(String device_id, JSONArray newCustomFields);
    Integer getPowerSourceTopologyConnectionsCount(String username, String vdmsid);
    PowerSourceTopologyDTO getPowerSourceTopologyByPagination(String username, String vdmsid, Integer pageno, Integer pagesize);
    Set<DeviceDTO> getDevicesByIds(Set<String> device_ids);
    JSONObject getDeviceQrNfcCountFromCloud(String vdms_id);
    void updateDeviceModbusStatus(String modbus_register_id);
    void updateDeviceModbusStatusByDeviceId(String device_id);
    void updateDeviceModbusCount(String modbus_register_id);
    void updateDeviceModbusCountByDeviceId(String device_id);
    DeviceDTO getDeviceDetailsByDeviceId(String device_id);
    Set<DeviceDTO> getAssetsByLocationId(String username, String vdmsid, String location_id, Integer pageno, Integer pagesize);
    String getDeviceRebootStatus(String username, String vdmsid, String deviceid);
    void updateDeviceRebootStatus(String device_id, String status);
    Set<DeviceDTO> getAllDevicesByGroup(String username, String vdmsid, JSONObject filterObject, String global_checklist_id, String global_inspection_record_id, String group);
    List<String> getDeviceIdsByFilter(String vdms_id, List<String> dockerNames, List<String> types, String searchKey, List<String> virtual_device_types, Boolean isTaggedToQrCode, Boolean isTaggedToNfc, List<String> locationIds);
    List<DeviceDTO> getDevicesByFilter(String vdms_id, List<String> dockerNames, List<String> types, String searchKey, List<String> virtual_device_types, Boolean isTaggedToQrCode, Boolean isTaggedToNfc, List<String> locationIds, List<String> deviceIds);
    void addAssetOnboardedDevices(String username, String vdmsid, List<DeviceDTO> deviceDTOS);
    void upsertOnboardedAssetImages(String username, String vdms_id, String device_id, List<String> asset_image_urls);
    void upsertOnboardAssets(String username, String vdmsid, JSONObject onboard_asset_data);
    void updateAssetOnboardStatus(String username, String vdmsid, JSONObject onboard_asset_data);
    void updateAssetOnboardData(String username, String vdmsid, String device_id, DeviceOnboardStatusDTO deviceOnboardStatusDTO, Integer onboard_status);
    Map<String, Integer> getAssetOnboardCount(String username, String vdmsid, String dockername, JSONObject search_sort_filter_details);
    void upsertAssetOcrImages(String username, String vdms_id, List<String> device_ids, List<MultipartFile> asset_ocr_images, HttpServletRequest httpServletRequest);
    void deleteAssetOcrImages(String username, String vdms_id, List<DeviceDTO> deviceDTOS, HttpServletRequest httpServletRequest);
    String getAssetOcrImageUrls(String username, String vdms_id, String device_id);
    Set<String> getAssetOnboardAssignees(String username, String vdms_id);
    DeviceDTO addDevice(String username, String vdmsid, String dockername, DeviceDTO deviceDto, HttpServletRequest httpServletRequest);
    void exportFilteredDevices(HttpServletResponse response, String username, String vdmsid, String dockername, String condition, JSONObject searchSortFilterDetails, Integer onboardStatus, String template_name, String email, HttpServletRequest httpServletRequest, String file_type);
    void sendAssetExportEmail(String email, String reportName, String filename, byte[] bytes, String vdmsid);
    byte[] generateSimpleAssetExportReportExcel(Set<DeviceDTO> devices, Boolean includeImages, HttpServletResponse response, String email, String modified_filename, String currentDateTime) throws IOException;
    byte[] generateSimpleAssetExportReportExcelData(List<Map<String, String>> excelData, Map<String, Integer> headerMap, String timeZoneId, String propertyName, Map<String, String> modifiedHeaderNames, HttpServletResponse response, String email, String modified_filename, String currentDateTime) throws IOException;
    byte[] generateExcelForMeasuringInstrumentsEmail(String username, String vdmsid, Set<DeviceDTO> devices);
    void createAttributeCells(MeasuringInstrumentAttributesDTO attribute, Row row, CellStyle style);
    void createBacnetCellsWithIndex(Row row, CellStyle style, List<BacnetAdvanceExportExcelDTO> bacnetDataList, int bacnetIndex);
    void createSiemensCellsWithIndex(Row row, CellStyle style, List<SiemensAdvanceExportExcelDTO> siemensDataList, int siemensIndex);
    void createConditionCellsWithIndex(Row row, CellStyle style, List<ConditionsAdvanceExportExcelDto> conditionsDataList, int conditionIndex);
    String daysCleaned(String input);
    String removeUnderscores(String input);
    DeviceDTO getDeviceAndOnboardStatusByDeviceId(String device_id);
    void syncDeviceOnboardStatus(String vdmsid);
    void syncAllDeviceOnboardStatusForQrSync(String vdmsid);
    void syncSingleDeviceOnboardStatus(String vdmsid, String device_id);
    void syncSingleDeviceOnboardStatusForQrSync(String vdmsid, String device_id);
    DeviceDTO getDeviceByDeviceIdNew(String username, String vdmsid, String dockername, String device_id);
    void updateVirtualDeviceOnboardStatus(Set<DeviceDTO> virtual_devices, String username);
    void updateVirtualDeviceOnboardStatusByAssetMapper(DeviceDTO deviceDTO, String username);
    DeviceDTO updateAssetMatchDetails(String username, String vdmsid, String dockername, JSONObject deviceObject, HttpServletRequest httpServletRequest,String assignee);
    void updateSiemensDeviceId(String primaryDeviceId, String existingDeviceId);
    void updateProcedureDeviceId(String primaryDeviceId, String existingDeviceId, Set<String> retainDevices);
    void updateIntegrationsDeviceId(String primaryDeviceId, String existingDeviceId, Set<String> retainDevices);
    void updateSensorsDeviceId(String primaryDeviceId, String existingDeviceId, Set<String> retainDevices);
    void upsertAssetImagesFromUrl(String username, String vdms_id, List<String> device_ids, List<String> asset_images);
    void updateMediaDeviceId(String primaryDeviceId, String existingDeviceId, Set<String> retainDevices);
    void updateDocumentsDeviceId(String primaryDeviceId, String existingDeviceId, Set<String> retainDevices);
    List<DeviceDTO> getAllDeviceByVdmsIdAndDockerNameWithoutPagination(String username, String vdmsid, String dockername);
    void upsertDigitalTwin(String username, String vdmsid, TagDeviceOrLocationDTO filterObject, HttpServletRequest httpServletRequest);
    void updateDigitalTwinImageUrlByIds(Set<DeviceDTO> deviceDTOS);
    void deleteDigitalTwin(String username, String vdmsid, String device_id, HttpServletRequest httpServletRequest);
    void multiEditDigitalTwin(String username, String vdmsid, String data, String image_url, MultipartFile multipartFile, HttpServletRequest httpServletRequest);
    void exportFilteredMeasuringInstrument(HttpServletResponse response, String username, String vdmsid, String dockername, String condition, Integer pageno, Integer pagesize, JSONObject search_sort_filter_details, Integer onboard_status);
    void generateExcelForMeasuringInstruments(String username, String vdmsid, Set<DeviceDTO> devices, HttpServletResponse response) throws IOException;
    void updateDevicePolyLensCountByDeviceId(String deviceId);
    void updateDeviceMqttDeviceCountByDeviceId(String deviceId);
    void simpleAssetExportReport(HttpServletResponse response, String file_type, Set<DeviceDTO> devices, Boolean includeImages, String email, String modified_filename, String currentDateTime, String vdmsid) throws IOException;
    byte[] generateSimpleAssetExportReportPDF(Set<DeviceDTO> devices, Boolean includeImages, HttpServletResponse response, String email, String modified_filename, String currentDateTime) throws IOException;
    byte[] generateSimpleAssetExportReportPDFData(List<List<HashMap<String, String>>> mainList, String propertyName, Boolean includeImages, String vdmsId, HttpServletResponse response, String email, String modified_filename, String currentDateTime) throws IOException;
    String getValueOrDefault(String value);
    PdfPCell createCenteredCell(String text, com.itextpdf.text.Font font);
    String convertUnderscoresToSpaces(String input);
    void sendAssetPDFExportEmail(String email, String reportName, String filename, byte[] bytes, String vdmsid);
    void updateAllRecordChecklistStatusInBatchForDevice(List<DeviceDTO> updatedDeviceStatus);
    Set<DeviceDTO> getDeviceDetailsByIdList(Set<String> device_ids);
    void syncDeviceOnboardStatusForQrSync(String vdmsId, Set<QrCodeDTO> existingQrCodes, Set<QrCodeDTO> updatedQrCodes, Set<QrCodeDTO> existingClientQrCodes, Set<QrCodeDTO> updatedClientQrCodes);
    DeviceDTO getDeviceDetailsForOnboard(String deviceId);
    Integer getAssetCount();
    ResponseDTO updateDeviceTypeForAll(String vdmsId);
    void updateDeviceType(String type, DeviceDTO deviceDTO);
    DeviceDTO getDeviceByMeasuringInstrumentId(String measuringInstrumentId);
    List<DeviceDTO> browseAiCallFlowDevicesWithSearch(String username, String vdmsid, String dockername, Integer pageno, Integer pagesize, String searchkey);
    void toggleDndStatus(String device_id, Boolean is_dnd_enabled, HttpServletRequest httpServletRequest);
    String getDeviceNameById(String device_id);
    DeviceDTO getDeviceById(String deviceId);
    DeviceDTO getDeviceInfoFromDb(String deviceId);
    Set<DeviceDTO> upsertInventoryDevices(Set<DeviceDTO> deviceDTOS, String vdmsId, String email);
    void archiveDevicesForInventoryDevice(String username, String vdmsid, Integer archive, Set<String> deviceIds);
    Set<String> listAiEnabledDockers(String email, String vdmsid, String searchkey);
    void UpdateDeviceDndEnabledAndTimestamp(String id,BigInteger dndTimestamp);
    void getAiCallDeviceOfflineConditionStatus(String deviceId, Integer status);
    List<DeviceDTO> getAiCallAndDeviceStatus(String deviceId);
    void dndCheckAndUpdate();
    void updateDeviceDndAndSystemDndStatus(String deviceId, Boolean isDndEnabled);
    void getDeviceDndAndSystemDndStatus(String deviceId, Boolean isDndEnabled);
    void getAllDeviceDetails(HttpServletResponse response, String username, String vdmsid, Integer pageno, Integer pagesize, String searchKey, JSONObject filterObject);
    List<DeviceDTO> getAllDeviceCustomDetails(String username, String vdmsid, String docker_name, Integer page_no, Integer page_size, String search_key, String profile_type);
    List<DeviceDTO> getDeviceCustomDetails(String docker_name, Integer page_no, Integer page_size, String search_key, List<String> device_ids);
    List<DeviceDTO> getDeviceCustomDetailsByIds( String username, String vdms_id, String docker_name, Integer has_pagination, Integer page_no, Integer page_size, String search_key, JSONObject requestBody);
    List<String> getList(JSONObject obj, String key);
    List<String> getAllDeviceIds(String docker_name, Integer page_no, Integer page_size, String search_key, String is_select_all);
    long getSubsystemParentDevicesCount(String username, String vdmsid, String dockername, String condition, String assignee);
    void setAssetImage(String deviceId, String imageUrl);
    java.util.Map<String, Object> importAssetsFromExcel(org.springframework.web.multipart.MultipartFile file, String vdmsid, String docker) throws java.io.IOException;
    java.util.Map<String, Object> multiUpdateAssets(java.util.List<String> ids, java.util.Map<String, Object> changes);

    /** Subset of the given device ids whose {@code monitor} flag is set. */
    Set<String> getMonitoredDeviceIds(java.util.Collection<String> deviceIds);
}
