server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOriginPatterns:
                  - "http://localhost:3000"
                  - "http://localhost:8080"
                  - "http://127.0.0.1:3000"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                  - PATCH
                allowedHeaders:
                  - "*"
                exposedHeaders:
                  - "*"
                allowCredentials: false
                maxAge: 3600
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
          routes:
            - id: asset-route
              uri: http://sclera-cloud-device-asset:8085
              predicates:
                - Path=/asset/**
              filters:
                - StripPrefix=1
            - id: vdms-route
              uri: http://vdms-service:8089
              predicates:
                - Path=/vdms/**
            - id: audit-route
              uri: http://sclera-audit:8090
              predicates:
                - Path=/audit/**
              filters:
                - StripPrefix=1
            - id: integrations-route
              uri: http://sclera-integrations:8096
              predicates:
                - Path=/integrations/**
              filters:
                - StripPrefix=1
            - id: inspection-route
              uri: http://sclera-inspection:8095
              predicates:
                - Path=/inspection/**
              filters:
                - StripPrefix=1
            - id: dapr-route
              uri: http://sclera-cloud-device-asset:3500
              predicates:
                - Path=/dapr/**
              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health
