apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: binding-corrigo
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: "http://httpbin:80/anything/corrigo"
    - name: method
      value: POST
    - name: responseTimeout
      value: "10s"
auth:
  secretStore: secretstore
