package io.sclera.workorder.service.impl;

import io.sclera.workorder.service.TicketHistoryService;
import io.sclera.workorder.service.TicketService;
import io.sclera.workorder.service.UserActionLogService;

import com.fasterxml.uuid.Generators;
import io.sclera.workorder.client.DeviceAssetClient;
import io.sclera.workorder.dto.TicketDTO;
import io.sclera.workorder.dto.TicketDetailsDTO;
import io.sclera.workorder.dto.TicketFilterDTO;
import io.sclera.workorder.enums.TicketType;
import io.sclera.workorder.repository.TicketRepository;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigInteger;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Random;
import java.util.Set;


/** Default {@link TicketService} implementation (native ticket CRUD, history, and alerts). */
@Slf4j
@Service
public class TicketServiceImpl implements TicketService {

    private final TicketRepository ticketRepository;
    private final DeviceAssetClient deviceAssetClient;
    private final TicketHistoryService ticketHistoryService;
    private final UserActionLogService userActionLogService;

    public TicketServiceImpl(TicketRepository ticketRepository,
                         DeviceAssetClient deviceAssetClient,
                         TicketHistoryService ticketHistoryService,
                         UserActionLogService userActionLogService) {
        this.ticketRepository = ticketRepository;
        this.deviceAssetClient = deviceAssetClient;
        this.ticketHistoryService = ticketHistoryService;
        this.userActionLogService = userActionLogService;
    }

    /**
     * {@inheritDoc} Derives the transition type (create vs. update), persists via the native upsert, writes history, and emits an audit event; each side-step guards its own errors.
     *
     * <p>Intentionally <strong>not</strong> {@code @Transactional}: this method relies on the
     * primary ticket write committing in its own (repository-level) transaction <em>before</em> the
     * best-effort side-effects run. Wrapping it in a single transaction would (a) let a swallowed
     * history-write failure mark the shared transaction rollback-only → {@code UnexpectedRollbackException}
     * at commit, and (b) break the foreign key for new tickets, whose history row would reference a
     * ticket that has not been committed yet. The per-step commit design is deliberate.
     */
    @Override
    public void upsertTicket(String username, String vdmsId, TicketDTO ticketDTO) {
        try {
            TicketType ticket_type = TicketType.NO_CHANGES;
            BigInteger timestamp = BigInteger.valueOf(System.currentTimeMillis());

            // Case 1: Creating a new ticket
            if (ticketDTO.getId() == null) {
                String newId = Generators.timeBasedGenerator().generate().toString();
                ticketDTO.setId(newId);
                ticketDTO.setCreated_at(timestamp);
                ticketDTO.setCreated_by(username);
                ticketDTO.setNumber(getNextTicketNumberByCategory(ticketDTO.getCategory(), vdmsId));
                ticketDTO.setName(getTicketNameByCategory(ticketDTO));
                ticketDTO.setDescription(ticketDTO.getUser_message());
                ticket_type = TicketType.GENERATED_BY_CUSTOMER; // Ticket Generated by Customer and is new ticket
                ticketDTO.setType(String.valueOf(ticket_type.getValue()));
                if (ticketDTO.getStatus() == null) {
                    ticketDTO.setStatus("new");
                }

            }

            // Case 2: Updating an existing ticket
            if (ticket_type == TicketType.NO_CHANGES) {
                try {
                    TicketDTO ticketDataOld = ticketRepository.getNativeTicketById(ticketDTO.getId());
                    String oldTicketStatus = ticketDataOld.getStatus();
                    String newTicketStatus = ticketDTO.getStatus();
                    String oldTicketUserMessage = ticketDataOld.getUser_message();
                    String newTicketUserMessage = ticketDTO.getUser_message();
                    String oldAssigneeUserEmail = ticketDataOld.getAssignee_user_email();
                    String newAssigneeUserEmail = ticketDTO.getAssignee_user_email();


                    ticket_type = determineTicketType(oldTicketStatus, newTicketStatus, oldTicketUserMessage, newTicketUserMessage, oldAssigneeUserEmail, newAssigneeUserEmail);


                    if (ticket_type == TicketType.CLOSED) { // Ticket Closed
                        ticketDTO.setClosed_at(timestamp);
                        ticketDTO.setClosed_by(username);
                    }

                    ticketDTO.setType(String.valueOf(ticket_type.getValue()));
                    ticketDTO.setUpdated_at(timestamp);
                    ticketDTO.setUpdated_by(username);
                    ticketDTO.setNumber(ticketDataOld.getNumber());
                    ticketDTO.setName(ticketDataOld.getName());
                    ticketDTO.setDescription(ticketDataOld.getDescription());
                    ticketDTO.setCreated_by(ticketDataOld.getCreated_by());


                } catch (Exception e) {
                    log.error("Error updating ticket type for ticket ID: {}: {}", ticketDTO.getId(), e.getMessage(), e);
                }

            }

            log.debug("Ticket Type: {} for Ticket ID: {}", ticket_type, ticketDTO.getId());
            ticketRepository.upsertTicketNative(
                    ticketDTO.getId(), ticketDTO.getNumber(), ticketDTO.getStatus(), ticketDTO.getUser_message(),
                    ticketDTO.getType(), ticketDTO.getDescription(), ticketDTO.getCategory(), ticketDTO.getRequest_type(),
                    ticketDTO.getCreated_by(), ticketDTO.getCreated_at(), ticketDTO.getUpdated_by(), ticketDTO.getUpdated_at(),
                    ticketDTO.getClosed_by(), ticketDTO.getClosed_at(), ticketDTO.getDevice_id(),
                    ticketDTO.getAssignee_user_email(), ticketDTO.getName()
            );
            log.info("Successfully added ticket ID: {} to database : {}", ticketDTO.getId(), ticketDTO);

            // ✅ Add user action log
            String action = ticket_type == TicketType.GENERATED_BY_CUSTOMER ? "ADD" : "UPDATE";

            try {
                String message = ticket_type == TicketType.GENERATED_BY_CUSTOMER ? "Ticket added successfully" : "Ticket updated successfully";

                userActionLogService.addUserAction(
                        username, vdmsId, "tickets", action, message, "success", "native_tickets", ticketDTO.getId()
                );
                log.info("User action logged for ticket ID: {}", ticketDTO.getId());
            } catch (Exception e) {
                userActionLogService.addUserAction(
                        username, vdmsId, "tickets", action, "Failed to " + action.toLowerCase() + " ticket", "failed", "native_tickets", ticketDTO.getId()
                );
                log.error("Error logging user action for ticket ID: {}: {}", ticketDTO.getId(), e.getMessage(), e);
            }


            // Insert ticket update into history
            try {
                if (ticket_type != TicketType.NO_CHANGES) {
                    String actionMessage = getTicketHistoryMessage(ticket_type, ticketDTO.getNumber(), username,
                            ticketDTO.getStatus(), ticketDTO.getAssignee_user_email());


                    //check if user_message is changed, if its changed then add user message to history or else  set user_message as null
                    String historyMessage;
                    if (ticket_type == TicketType.GENERATED_BY_CUSTOMER ||
                            ticket_type == TicketType.MESSAGE_UPDATED_BY_CUSTOMER ||
                            ticket_type == TicketType.STATUS_AND_MESSAGE_UPDATED_BY_CUSTOMER ||
                            ticket_type == TicketType.MESSAGE_UPDATED_AND_ASSIGNED ||
                            ticket_type == TicketType.STATUS_AND_MESSAGE_UPDATED_AND_ASSIGNED ||
                            ticket_type == TicketType.MESSAGE_UPDATED_AND_UNASSIGNED ||
                            ticket_type == TicketType.STATUS_AND_MESSAGE_UPDATED_AND_UNASSIGNED) {
                        historyMessage = ticketDTO.getUser_message();
                    } else {
                        historyMessage = null;
                    }

                    ticketHistoryService.addNativeTicketHistory(historyMessage, timestamp, ticketDTO.getStatus(), actionMessage, ticketDTO.getNumber(), username, ticketDTO.getId());
                    log.info("Successfully inserted ticket history for ticket ID: {}", ticketDTO.getId());
                }
            } catch (Exception e) {

                log.error("Error inserting ticket history for ticket ID: {}: {}", ticketDTO.getId(), e.getMessage(), e);
            }

            // Send ticket alert
            try {
                ticketDTO.setTimestamp(timestamp);
                this.sendNativeTicketAlertInfo(ticketDTO, ticket_type);
                log.info("Successfully sent ticket alert for ticket ID: {}", ticketDTO.getId());
            } catch (Exception e) {
                log.error("Error sending ticket alert for ticket ID: {}: {}", ticketDTO.getId(), e.getMessage(), e);
            }

            // Update ticket count and status (side effect — failure must not undo the DB write)
            try {
                deviceAssetClient.syncTicketStats(ticketDTO.getDevice_id());
                log.info("Successfully updated device ticket count and status for device ID: {}", ticketDTO.getDevice_id());
            } catch (Exception syncEx) {
                log.warn("Failed to sync ticket stats for device ID: {}: {}", ticketDTO.getDevice_id(), syncEx.getMessage());
            }
        } catch (RuntimeException e) {
            log.error("Error in upsertTicket for username: {}, ticketDTO: {}: {}", username, ticketDTO, e.getMessage(), e);
            throw e;
        }
    }

    /** {@inheritDoc} Computes the next sequential ticket number for the category from the latest existing number. */
    @Override
    @Transactional(readOnly = true)
    public String getNextTicketNumberByCategory(String category, String vdmsId) {
        String prefix = "";

        // Strip a leading "VDMS" prefix case-insensitively (VDMS000 / vdms000 → 000).
        String numericId = vdmsId.regionMatches(true, 0, "VDMS", 0, 4) ? vdmsId.substring(4) : vdmsId;

        if (category.equalsIgnoreCase("incident_request")) {
            prefix = "INC-" + numericId;
        } else if (category.equalsIgnoreCase("service_request")) {
            prefix = "SRN-" + numericId;
        }
        Integer maxNum = ticketRepository.findMaxTicketNumberByPrefix(prefix);
        int nextNumber = (maxNum == null ? 0 : maxNum) + 1;
        return prefix + String.format("%06d", nextNumber);
    }

    /** {@inheritDoc} Derives the display name from the ticket's category. */
    @Override
    public String getTicketNameByCategory(TicketDTO ticketDTO) {
        String name = "";
        if (ticketDTO.getCategory().equalsIgnoreCase("incident_request")) {
//            name = deviceService.getDeviceNameById(ticketDTO.getDevice_id());
        } else if (ticketDTO.getCategory().equalsIgnoreCase("service_request")) {
            name = ticketDTO.getRequest_type();
        }
        return name;
    }

    /**
     * Determines the ticket type based on changes in status, user message and assignment
     */
    private TicketType determineTicketType(String oldStatus, String newStatus, String oldUserMessage,
                                           String newUserMessage, String oldAssigneeUserEmail,
                                           String newAssigneeUserEmail) {
        TicketType ticketType = TicketType.NO_CHANGES;

        // Determine ticketType using if-else
        if (newStatus != null && newStatus.equalsIgnoreCase("closed")) {
            ticketType = TicketType.CLOSED; // Ticket Closed (highest priority)

        } else if (oldStatus != null && newStatus != null && oldStatus.equals("closed") && !newStatus.equals("closed")) {
            ticketType = TicketType.REOPENED_BY_CUSTOMER; // Re-Opened by Customer

        } else if (oldStatus != null && newStatus != null && !oldStatus.equals(newStatus) &&
                oldUserMessage != null && newUserMessage != null && !oldUserMessage.equals(newUserMessage) &&
                ((oldAssigneeUserEmail == null || oldAssigneeUserEmail.trim().isEmpty()) && newAssigneeUserEmail != null && !newAssigneeUserEmail.trim().isEmpty() ||
                        !(oldAssigneeUserEmail == null || oldAssigneeUserEmail.trim().isEmpty()) && newAssigneeUserEmail != null && !newAssigneeUserEmail.trim().isEmpty() && !oldAssigneeUserEmail.equals(newAssigneeUserEmail))) {
            ticketType = TicketType.STATUS_AND_MESSAGE_UPDATED_AND_ASSIGNED; // Status Updated + User Message Updated + Assignment Changed

        } else if (oldStatus != null && newStatus != null && !oldStatus.equals(newStatus) &&
                oldUserMessage != null && newUserMessage != null && !oldUserMessage.equals(newUserMessage) &&
                !(oldAssigneeUserEmail == null || oldAssigneeUserEmail.trim().isEmpty()) && (newAssigneeUserEmail == null || newAssigneeUserEmail.trim().isEmpty())) {
            ticketType = TicketType.STATUS_AND_MESSAGE_UPDATED_AND_UNASSIGNED; // Status Updated + User Message Updated + Unassigned

        } else if (oldStatus != null && newStatus != null && !oldStatus.equals(newStatus) &&
                ((oldAssigneeUserEmail == null || oldAssigneeUserEmail.trim().isEmpty()) && newAssigneeUserEmail != null && !newAssigneeUserEmail.trim().isEmpty() ||
                        !(oldAssigneeUserEmail == null || oldAssigneeUserEmail.trim().isEmpty()) && newAssigneeUserEmail != null && !newAssigneeUserEmail.trim().isEmpty() && !oldAssigneeUserEmail.equals(newAssigneeUserEmail))) {
            ticketType = TicketType.STATUS_UPDATED_AND_ASSIGNED; // Status Updated + Assignment Changed

        } else if (oldStatus != null && newStatus != null && !oldStatus.equals(newStatus) &&
                !(oldAssigneeUserEmail == null || oldAssigneeUserEmail.trim().isEmpty()) && (newAssigneeUserEmail == null || newAssigneeUserEmail.trim().isEmpty())) {
            ticketType = TicketType.STATUS_UPDATED_AND_UNASSIGNED; // Status Updated + Unassigned

        } else if (oldUserMessage != null && newUserMessage != null && !oldUserMessage.equals(newUserMessage) &&
                ((oldAssigneeUserEmail == null || oldAssigneeUserEmail.trim().isEmpty()) && newAssigneeUserEmail != null && !newAssigneeUserEmail.trim().isEmpty() ||
                        !(oldAssigneeUserEmail == null || oldAssigneeUserEmail.trim().isEmpty()) && newAssigneeUserEmail != null && !newAssigneeUserEmail.trim().isEmpty() && !oldAssigneeUserEmail.equals(newAssigneeUserEmail))) {
            ticketType = TicketType.MESSAGE_UPDATED_AND_ASSIGNED; // User Message Updated + Assignment Changed

        } else if (oldUserMessage != null && newUserMessage != null && !oldUserMessage.equals(newUserMessage) &&
                !(oldAssigneeUserEmail == null || oldAssigneeUserEmail.trim().isEmpty()) && (newAssigneeUserEmail == null || newAssigneeUserEmail.trim().isEmpty())) {
            ticketType = TicketType.MESSAGE_UPDATED_AND_UNASSIGNED; // User Message Updated + Unassigned

        } else if (oldStatus != null && newStatus != null && !oldStatus.equals(newStatus) &&
                oldUserMessage != null && newUserMessage != null && !oldUserMessage.equals(newUserMessage)) {
            ticketType = TicketType.STATUS_AND_MESSAGE_UPDATED_BY_CUSTOMER; // Status Updated + User Message Updated

        } else if (oldStatus != null && newStatus != null && !oldStatus.equals(newStatus)) {
            ticketType = TicketType.STATUS_UPDATED_BY_CUSTOMER; // Status Updated by Customer

        } else if (oldUserMessage != null && newUserMessage != null && !oldUserMessage.equals(newUserMessage)) {
            ticketType = TicketType.MESSAGE_UPDATED_BY_CUSTOMER; // User Message Updated by Customer

        } else if ((oldAssigneeUserEmail == null || oldAssigneeUserEmail.trim().isEmpty()) && newAssigneeUserEmail != null && !newAssigneeUserEmail.trim().isEmpty() ||
                !(oldAssigneeUserEmail == null || oldAssigneeUserEmail.trim().isEmpty()) && newAssigneeUserEmail != null && !newAssigneeUserEmail.trim().isEmpty() && !oldAssigneeUserEmail.equals(newAssigneeUserEmail)) {
            ticketType = TicketType.ASSIGNED; // Assignment Changed

        } else if (!(oldAssigneeUserEmail == null || oldAssigneeUserEmail.trim().isEmpty()) && (newAssigneeUserEmail == null || newAssigneeUserEmail.trim().isEmpty())) {
            ticketType = TicketType.UNASSIGNED; // Unassigned

        } else {
            ticketType = TicketType.NO_CHANGES; // No changes
        }

        return ticketType;
    }


    /** {@inheritDoc} Sanitizes the search key and runs the filtered, paged query (LIMIT/OFFSET via Pageable). */
    @Override
    @Transactional(readOnly = true)
    public Set<TicketDTO> getAllTickets(String username, String searchkey, TicketFilterDTO ticketFilterDTO, Integer pagesize, Integer pageno) {
        Set<String> statusSet = ticketFilterDTO.getStatus();
        String status = (statusSet == null || statusSet.isEmpty() || statusSet.contains("all")) ? "all"
                : statusSet.iterator().next();
        return new LinkedHashSet<>(ticketRepository.getAllNativeTickets(searchkey, ticketFilterDTO.getCategory(), status,
                ticketFilterDTO.getAssignee_user_email(), ticketFilterDTO.getDevice_id(), username,
                PageRequest.of(pageno - 1, pagesize)));
    }


    /** {@inheritDoc} Filtered, paged query scoped to a single device (LIMIT/OFFSET via Pageable). */
    @Override
    @Transactional(readOnly = true)
    public Set<TicketDTO> getAllTicketsByDeviceId(String username, String device_id, Integer pagesize, Integer pageno, TicketFilterDTO ticketFilterDTO) {
        return new LinkedHashSet<>(ticketRepository.getAllNativeTicketsByDeviceId(device_id,
                ticketFilterDTO.getAssignee_user_email(), username, PageRequest.of(pageno - 1, pagesize)));
    }

    /** {@inheritDoc} Soft-deletes the ticket and records the audit action; rethrows on failure (after a failed-audit entry). */
    @Override
    @Transactional
    public void deleteTicketById(String username, String vdmsId, String ticket_id) {
        try {
            TicketDTO ticketDTO = ticketRepository.getNativeTicketById(ticket_id);

            // Delete ticket
            ticketRepository.deleteTicketById(ticket_id);

            // Update device ticket status/count
            deviceAssetClient.syncTicketStats(ticketDTO.getDevice_id());
            // Log deletion in user action
            userActionLogService.addUserAction(username, vdmsId, "tickets", "DELETE", "Ticket deleted successfully", "success", "native_tickets", ticket_id);
            log.info("Deleted ticket ID: {} by user: {}", ticket_id, username);
        } catch (RuntimeException e) {
            userActionLogService.addUserAction(username, vdmsId, "tickets", "DELETE", "Failed to delete ticket", "failed", "native_tickets", ticket_id);
            log.error("Unable to delete ticket ID: {} by user: {}", ticket_id, username);
            throw e;
        }
    }

    /** {@inheritDoc} Returns per-status counts plus an {@code "all"} aggregate for the assignee/filter. */
    @Override
    @Transactional(readOnly = true)
    public Map<String, Integer> getTicketStatusCountByAssignee(String username, TicketFilterDTO ticketFilterDTO) {
        Map<String, Integer> count = new HashMap<>();
        String assignee = ticketFilterDTO.getAssignee_user_email();
        count.put("all",     ticketRepository.getTicketCountByStatusAndUser("all",     assignee, username));
        count.put("new",     ticketRepository.getTicketCountByStatusAndUser("new",     assignee, username));
        count.put("open",    ticketRepository.getTicketCountByStatusAndUser("open",    assignee, username));
        count.put("on_hold", ticketRepository.getTicketCountByStatusAndUser("on_hold", assignee, username));
        count.put("closed",  ticketRepository.getTicketCountByStatusAndUser("closed",  assignee, username));
        return count;
    }

    /** {@inheritDoc} Emits history/alerts only for qualifying transition types (created, status change, assignment, closed). */
    @Override
    public void sendNativeTicketAlertInfo(TicketDTO ticket, TicketType ticket_type) {
        try {
            if (ticket_type != null && ticket_type != TicketType.NO_CHANGES) {
                // Insert ticket update into history only if its created or status gets updated or closed
                if (ticket_type == TicketType.GENERATED_BY_CUSTOMER || ticket_type == TicketType.STATUS_UPDATED_BY_CUSTOMER || ticket_type == TicketType.STATUS_AND_MESSAGE_UPDATED_BY_CUSTOMER || ticket_type == TicketType.REOPENED_BY_CUSTOMER ||
                        ticket_type == TicketType.STATUS_UPDATED_AND_ASSIGNED || ticket_type == TicketType.STATUS_AND_MESSAGE_UPDATED_AND_ASSIGNED || ticket_type == TicketType.STATUS_UPDATED_AND_UNASSIGNED || ticket_type == TicketType.STATUS_AND_MESSAGE_UPDATED_AND_UNASSIGNED ||
                        ticket_type == TicketType.CLOSED) {
//                    historyService.insertTicketHistory(ticket_type, ticket);
                    log.info("Inserted ticket history for ticket ID: {}", ticket.getId());
                }

                // Send ticket created, closed, and assignment changed
                if (ticket_type == TicketType.GENERATED_BY_CUSTOMER || ticket_type == TicketType.ASSIGNED || ticket_type == TicketType.STATUS_UPDATED_AND_ASSIGNED || ticket_type == TicketType.MESSAGE_UPDATED_AND_ASSIGNED ||
                        ticket_type == TicketType.STATUS_AND_MESSAGE_UPDATED_AND_ASSIGNED || ticket_type == TicketType.CLOSED) {
//                    alertService.sendNativeTicketAlerts(ticket_type, ticket);

                }
                //send ticket update to rabbitmq
//                rabbitmqService.rabbitmqTicketData(ticket_type, ticketDetails);
            }

        } catch (Exception e) {
            log.error("Error sending ticket alert info", e);
        }
    }

    /** {@inheritDoc} Returns the full native detail projection for the ticket. */
    @Override
    @Transactional(readOnly = true)
    public TicketDTO getNativeTicketDetailsById(String ticket_id) {
        TicketDTO ticketDTO = ticketRepository.getNativeTicketById(ticket_id);

        if (ticketDTO != null && ticketDTO.getAssignee_user_email() != null) {
//            ticketDTO.setAssignee(userService.getUserByEmail(ticketDTO.getAssignee_user_email()));
        }
        if (ticketDTO != null && ticketDTO.getDevice_id() != null) {
//            DeviceDTO device = deviceService.getDeviceById(ticketDTO.getDevice_id());
//            ticketDTO.setDevice(device);
        }
        return ticketDTO;
    }


    private String getTicketHistoryMessage(TicketType ticketType, String ticketNumber, String username,
                                           String newStatus, String newAssigneeUserEmail) {
        String historyMessage;

        switch (ticketType) {
            case NO_CHANGES:
                historyMessage = "Ticket #" + ticketNumber + " remains unchanged by " + username;
                break;
            case GENERATED_BY_CUSTOMER:
                historyMessage = "Ticket #" + ticketNumber + " was created by " + username;
                break;
            case STATUS_UPDATED_BY_CUSTOMER:
                historyMessage = "Ticket #" + ticketNumber + " status changed to " + newStatus + " by " + username;
                break;
            case MESSAGE_UPDATED_BY_CUSTOMER:
                historyMessage = "Ticket #" + ticketNumber + " message updated by customer " + username;
                break;
            case STATUS_AND_MESSAGE_UPDATED_BY_CUSTOMER:
                historyMessage = "Ticket #" + ticketNumber + " status changed to " + newStatus + " and message updated by " + username;
                break;
            case STATUS_UPDATED_BY_VENDOR:
                historyMessage = "Ticket #" + ticketNumber + " status changed to " + newStatus + " by vendor " + username;
                break;
            case MESSAGE_UPDATED_BY_VENDOR:
                historyMessage = "Ticket #" + ticketNumber + " vendor message updated by " + username;
                break;
            case STATUS_AND_MESSAGE_UPDATED_BY_VENDOR:
                historyMessage = "Ticket #" + ticketNumber + " status changed to " + newStatus + " with vendor message updated by " + username;
                break;
            case REOPENED_BY_CUSTOMER:
                historyMessage = "Ticket #" + ticketNumber + " has been re-opened by " + username;
                break;
            case ASSIGNED:
                historyMessage = "Ticket #" + ticketNumber + " assigned to " + newAssigneeUserEmail + " by " + username;
                break;
            case STATUS_UPDATED_AND_ASSIGNED:
                historyMessage = "Ticket #" + ticketNumber + " status updated to " + newStatus + " and assigned to " + newAssigneeUserEmail + " by " + username;
                break;
            case MESSAGE_UPDATED_AND_ASSIGNED:
                historyMessage = "Ticket #" + ticketNumber + " message updated and assigned to " + newAssigneeUserEmail + " by " + username;
                break;
            case STATUS_AND_MESSAGE_UPDATED_AND_ASSIGNED:
                historyMessage = "Ticket #" + ticketNumber + " status changed to " + newStatus + ", message updated, and assigned to " + newAssigneeUserEmail + " by " + username;
                break;
            case UNASSIGNED:
                historyMessage = "Ticket #" + ticketNumber + " unassigned by " + username;
                break;
            case STATUS_UPDATED_AND_UNASSIGNED:
                historyMessage = "Ticket #" + ticketNumber + " status changed to " + newStatus + " and unassigned by " + username;
                break;
            case MESSAGE_UPDATED_AND_UNASSIGNED:
                historyMessage = "Ticket #" + ticketNumber + " message updated and unassigned by " + username;
                break;
            case STATUS_AND_MESSAGE_UPDATED_AND_UNASSIGNED:
                historyMessage = "Ticket #" + ticketNumber + " status changed to " + newStatus + ", message updated, and unassigned by " + username;
                break;
            case CLOSED:
                historyMessage = "Ticket #" + ticketNumber + " was closed by " + username;
                break;
            default:
                historyMessage = "Ticket #" + ticketNumber + " performed an unknown action by " + username;
                break;
        }
        return historyMessage;
    }

    /** {@inheritDoc} Clears the assignee on all tickets currently assigned to the e-mail (e.g. when that user is deleted). */
    @Override
    @Transactional
    public void updateTicketAssigneeByUserEmail(String assignee_user_email) {
        ticketRepository.updateTicketAssigneeByUserEmail(assignee_user_email);

    }
}

