// Generated by delombok at Wed May 13 12:25:13 IST 2026
package io.sclera.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import javax.persistence.Id;
import java.math.BigDecimal;
import java.math.BigInteger;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class ClientQrCodeDTO {
    @Id
    private String id;
    private String addedAt;
    private String addedBy;
    private String clientQrCodeId;
    private String deviceId;
    private String locationId;
    private BigDecimal updatedTime;
    private String updatedBy;
    private String vdmsId;
    private String batchId;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAddedAt() {
        return this.addedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAddedBy() {
        return this.addedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getClientQrCodeId() {
        return this.clientQrCodeId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeviceId() {
        return this.deviceId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLocationId() {
        return this.locationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getUpdatedTime() {
        return this.updatedTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVdmsId() {
        return this.vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBatchId() {
        return this.batchId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAddedAt(final String addedAt) {
        this.addedAt = addedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAddedBy(final String addedBy) {
        this.addedBy = addedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setClientQrCodeId(final String clientQrCodeId) {
        this.clientQrCodeId = clientQrCodeId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeviceId(final String deviceId) {
        this.deviceId = deviceId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLocationId(final String locationId) {
        this.locationId = locationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedTime(final BigDecimal updatedTime) {
        this.updatedTime = updatedTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedBy(final String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVdmsId(final String vdmsId) {
        this.vdmsId = vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBatchId(final String batchId) {
        this.batchId = batchId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ClientQrCodeDTO)) return false;
        final ClientQrCodeDTO other = (ClientQrCodeDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$addedAt = this.getAddedAt();
        final java.lang.Object other$addedAt = other.getAddedAt();
        if (this$addedAt == null ? other$addedAt != null : !this$addedAt.equals(other$addedAt)) return false;
        final java.lang.Object this$addedBy = this.getAddedBy();
        final java.lang.Object other$addedBy = other.getAddedBy();
        if (this$addedBy == null ? other$addedBy != null : !this$addedBy.equals(other$addedBy)) return false;
        final java.lang.Object this$clientQrCodeId = this.getClientQrCodeId();
        final java.lang.Object other$clientQrCodeId = other.getClientQrCodeId();
        if (this$clientQrCodeId == null ? other$clientQrCodeId != null : !this$clientQrCodeId.equals(other$clientQrCodeId)) return false;
        final java.lang.Object this$deviceId = this.getDeviceId();
        final java.lang.Object other$deviceId = other.getDeviceId();
        if (this$deviceId == null ? other$deviceId != null : !this$deviceId.equals(other$deviceId)) return false;
        final java.lang.Object this$locationId = this.getLocationId();
        final java.lang.Object other$locationId = other.getLocationId();
        if (this$locationId == null ? other$locationId != null : !this$locationId.equals(other$locationId)) return false;
        final java.lang.Object this$updatedTime = this.getUpdatedTime();
        final java.lang.Object other$updatedTime = other.getUpdatedTime();
        if (this$updatedTime == null ? other$updatedTime != null : !this$updatedTime.equals(other$updatedTime)) return false;
        final java.lang.Object this$updatedBy = this.getUpdatedBy();
        final java.lang.Object other$updatedBy = other.getUpdatedBy();
        if (this$updatedBy == null ? other$updatedBy != null : !this$updatedBy.equals(other$updatedBy)) return false;
        final java.lang.Object this$vdmsId = this.getVdmsId();
        final java.lang.Object other$vdmsId = other.getVdmsId();
        if (this$vdmsId == null ? other$vdmsId != null : !this$vdmsId.equals(other$vdmsId)) return false;
        final java.lang.Object this$batchId = this.getBatchId();
        final java.lang.Object other$batchId = other.getBatchId();
        if (this$batchId == null ? other$batchId != null : !this$batchId.equals(other$batchId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ClientQrCodeDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $addedAt = this.getAddedAt();
        result = result * PRIME + ($addedAt == null ? 43 : $addedAt.hashCode());
        final java.lang.Object $addedBy = this.getAddedBy();
        result = result * PRIME + ($addedBy == null ? 43 : $addedBy.hashCode());
        final java.lang.Object $clientQrCodeId = this.getClientQrCodeId();
        result = result * PRIME + ($clientQrCodeId == null ? 43 : $clientQrCodeId.hashCode());
        final java.lang.Object $deviceId = this.getDeviceId();
        result = result * PRIME + ($deviceId == null ? 43 : $deviceId.hashCode());
        final java.lang.Object $locationId = this.getLocationId();
        result = result * PRIME + ($locationId == null ? 43 : $locationId.hashCode());
        final java.lang.Object $updatedTime = this.getUpdatedTime();
        result = result * PRIME + ($updatedTime == null ? 43 : $updatedTime.hashCode());
        final java.lang.Object $updatedBy = this.getUpdatedBy();
        result = result * PRIME + ($updatedBy == null ? 43 : $updatedBy.hashCode());
        final java.lang.Object $vdmsId = this.getVdmsId();
        result = result * PRIME + ($vdmsId == null ? 43 : $vdmsId.hashCode());
        final java.lang.Object $batchId = this.getBatchId();
        result = result * PRIME + ($batchId == null ? 43 : $batchId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ClientQrCodeDTO(id=" + this.getId() + ", addedAt=" + this.getAddedAt() + ", addedBy=" + this.getAddedBy() + ", clientQrCodeId=" + this.getClientQrCodeId() + ", deviceId=" + this.getDeviceId() + ", locationId=" + this.getLocationId() + ", updatedTime=" + this.getUpdatedTime() + ", updatedBy=" + this.getUpdatedBy() + ", vdmsId=" + this.getVdmsId() + ", batchId=" + this.getBatchId() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ClientQrCodeDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ClientQrCodeDTO(final String id, final String addedAt, final String addedBy, final String clientQrCodeId, final String deviceId, final String locationId, final BigDecimal updatedTime, final String updatedBy, final String vdmsId, final String batchId) {
        this.id = id;
        this.addedAt = addedAt;
        this.addedBy = addedBy;
        this.clientQrCodeId = clientQrCodeId;
        this.deviceId = deviceId;
        this.locationId = locationId;
        this.updatedTime = updatedTime;
        this.updatedBy = updatedBy;
        this.vdmsId = vdmsId;
        this.batchId = batchId;
    }
}
