// Generated by delombok at Wed May 13 12:25:05 IST 2026
package io.sclera.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.math.BigInteger;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class ClientBarCodeDTO {
    private String id;
    private String addedAt;
    private String addedBy;
    private String clientBarCodeId;
    private String deviceId;
    private String locationId;
    private BigInteger updatedTime;
    private String updatedBy;
    private String vdmsId;
    private String batchId;

    //barcodedetails
    public ClientBarCodeDTO(String id, String deviceId, String locationId) {
        this.id = id;
        this.deviceId = deviceId;
        this.locationId = locationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAddedAt() {
        return this.addedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAddedBy() {
        return this.addedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getClientBarCodeId() {
        return this.clientBarCodeId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeviceId() {
        return this.deviceId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLocationId() {
        return this.locationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigInteger getUpdatedTime() {
        return this.updatedTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVdmsId() {
        return this.vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBatchId() {
        return this.batchId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAddedAt(final String addedAt) {
        this.addedAt = addedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAddedBy(final String addedBy) {
        this.addedBy = addedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setClientBarCodeId(final String clientBarCodeId) {
        this.clientBarCodeId = clientBarCodeId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeviceId(final String deviceId) {
        this.deviceId = deviceId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLocationId(final String locationId) {
        this.locationId = locationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedTime(final BigInteger updatedTime) {
        this.updatedTime = updatedTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedBy(final String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVdmsId(final String vdmsId) {
        this.vdmsId = vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBatchId(final String batchId) {
        this.batchId = batchId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ClientBarCodeDTO)) return false;
        final ClientBarCodeDTO other = (ClientBarCodeDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$addedAt = this.getAddedAt();
        final java.lang.Object other$addedAt = other.getAddedAt();
        if (this$addedAt == null ? other$addedAt != null : !this$addedAt.equals(other$addedAt)) return false;
        final java.lang.Object this$addedBy = this.getAddedBy();
        final java.lang.Object other$addedBy = other.getAddedBy();
        if (this$addedBy == null ? other$addedBy != null : !this$addedBy.equals(other$addedBy)) return false;
        final java.lang.Object this$clientBarCodeId = this.getClientBarCodeId();
        final java.lang.Object other$clientBarCodeId = other.getClientBarCodeId();
        if (this$clientBarCodeId == null ? other$clientBarCodeId != null : !this$clientBarCodeId.equals(other$clientBarCodeId)) return false;
        final java.lang.Object this$deviceId = this.getDeviceId();
        final java.lang.Object other$deviceId = other.getDeviceId();
        if (this$deviceId == null ? other$deviceId != null : !this$deviceId.equals(other$deviceId)) return false;
        final java.lang.Object this$locationId = this.getLocationId();
        final java.lang.Object other$locationId = other.getLocationId();
        if (this$locationId == null ? other$locationId != null : !this$locationId.equals(other$locationId)) return false;
        final java.lang.Object this$updatedTime = this.getUpdatedTime();
        final java.lang.Object other$updatedTime = other.getUpdatedTime();
        if (this$updatedTime == null ? other$updatedTime != null : !this$updatedTime.equals(other$updatedTime)) return false;
        final java.lang.Object this$updatedBy = this.getUpdatedBy();
        final java.lang.Object other$updatedBy = other.getUpdatedBy();
        if (this$updatedBy == null ? other$updatedBy != null : !this$updatedBy.equals(other$updatedBy)) return false;
        final java.lang.Object this$vdmsId = this.getVdmsId();
        final java.lang.Object other$vdmsId = other.getVdmsId();
        if (this$vdmsId == null ? other$vdmsId != null : !this$vdmsId.equals(other$vdmsId)) return false;
        final java.lang.Object this$batchId = this.getBatchId();
        final java.lang.Object other$batchId = other.getBatchId();
        if (this$batchId == null ? other$batchId != null : !this$batchId.equals(other$batchId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ClientBarCodeDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $addedAt = this.getAddedAt();
        result = result * PRIME + ($addedAt == null ? 43 : $addedAt.hashCode());
        final java.lang.Object $addedBy = this.getAddedBy();
        result = result * PRIME + ($addedBy == null ? 43 : $addedBy.hashCode());
        final java.lang.Object $clientBarCodeId = this.getClientBarCodeId();
        result = result * PRIME + ($clientBarCodeId == null ? 43 : $clientBarCodeId.hashCode());
        final java.lang.Object $deviceId = this.getDeviceId();
        result = result * PRIME + ($deviceId == null ? 43 : $deviceId.hashCode());
        final java.lang.Object $locationId = this.getLocationId();
        result = result * PRIME + ($locationId == null ? 43 : $locationId.hashCode());
        final java.lang.Object $updatedTime = this.getUpdatedTime();
        result = result * PRIME + ($updatedTime == null ? 43 : $updatedTime.hashCode());
        final java.lang.Object $updatedBy = this.getUpdatedBy();
        result = result * PRIME + ($updatedBy == null ? 43 : $updatedBy.hashCode());
        final java.lang.Object $vdmsId = this.getVdmsId();
        result = result * PRIME + ($vdmsId == null ? 43 : $vdmsId.hashCode());
        final java.lang.Object $batchId = this.getBatchId();
        result = result * PRIME + ($batchId == null ? 43 : $batchId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ClientBarCodeDTO(id=" + this.getId() + ", addedAt=" + this.getAddedAt() + ", addedBy=" + this.getAddedBy() + ", clientBarCodeId=" + this.getClientBarCodeId() + ", deviceId=" + this.getDeviceId() + ", locationId=" + this.getLocationId() + ", updatedTime=" + this.getUpdatedTime() + ", updatedBy=" + this.getUpdatedBy() + ", vdmsId=" + this.getVdmsId() + ", batchId=" + this.getBatchId() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ClientBarCodeDTO(final String id, final String addedAt, final String addedBy, final String clientBarCodeId, final String deviceId, final String locationId, final BigInteger updatedTime, final String updatedBy, final String vdmsId, final String batchId) {
        this.id = id;
        this.addedAt = addedAt;
        this.addedBy = addedBy;
        this.clientBarCodeId = clientBarCodeId;
        this.deviceId = deviceId;
        this.locationId = locationId;
        this.updatedTime = updatedTime;
        this.updatedBy = updatedBy;
        this.vdmsId = vdmsId;
        this.batchId = batchId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ClientBarCodeDTO() {
    }
}
