// Generated by delombok at Wed May 13 12:25:09 IST 2026
package io.sclera.dto;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.math.BigInteger;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class ClientNfcDTO {
    private String id;
    private String batchId;
    private String createdBy;
    private BigInteger creationTime;
    private String deviceId;
    private String locationId;
    @JsonAlias("nfc_id")
    private String nfcId;
    private String uuid;
    private String vdmsId;
    private String updatedBy;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBatchId() {
        return this.batchId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigInteger getCreationTime() {
        return this.creationTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeviceId() {
        return this.deviceId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLocationId() {
        return this.locationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNfcId() {
        return this.nfcId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUuid() {
        return this.uuid;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVdmsId() {
        return this.vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBatchId(final String batchId) {
        this.batchId = batchId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedBy(final String createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreationTime(final BigInteger creationTime) {
        this.creationTime = creationTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeviceId(final String deviceId) {
        this.deviceId = deviceId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLocationId(final String locationId) {
        this.locationId = locationId;
    }

    @JsonAlias("nfc_id")
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNfcId(final String nfcId) {
        this.nfcId = nfcId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUuid(final String uuid) {
        this.uuid = uuid;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVdmsId(final String vdmsId) {
        this.vdmsId = vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedBy(final String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ClientNfcDTO)) return false;
        final ClientNfcDTO other = (ClientNfcDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$batchId = this.getBatchId();
        final java.lang.Object other$batchId = other.getBatchId();
        if (this$batchId == null ? other$batchId != null : !this$batchId.equals(other$batchId)) return false;
        final java.lang.Object this$createdBy = this.getCreatedBy();
        final java.lang.Object other$createdBy = other.getCreatedBy();
        if (this$createdBy == null ? other$createdBy != null : !this$createdBy.equals(other$createdBy)) return false;
        final java.lang.Object this$creationTime = this.getCreationTime();
        final java.lang.Object other$creationTime = other.getCreationTime();
        if (this$creationTime == null ? other$creationTime != null : !this$creationTime.equals(other$creationTime)) return false;
        final java.lang.Object this$deviceId = this.getDeviceId();
        final java.lang.Object other$deviceId = other.getDeviceId();
        if (this$deviceId == null ? other$deviceId != null : !this$deviceId.equals(other$deviceId)) return false;
        final java.lang.Object this$locationId = this.getLocationId();
        final java.lang.Object other$locationId = other.getLocationId();
        if (this$locationId == null ? other$locationId != null : !this$locationId.equals(other$locationId)) return false;
        final java.lang.Object this$nfcId = this.getNfcId();
        final java.lang.Object other$nfcId = other.getNfcId();
        if (this$nfcId == null ? other$nfcId != null : !this$nfcId.equals(other$nfcId)) return false;
        final java.lang.Object this$uuid = this.getUuid();
        final java.lang.Object other$uuid = other.getUuid();
        if (this$uuid == null ? other$uuid != null : !this$uuid.equals(other$uuid)) return false;
        final java.lang.Object this$vdmsId = this.getVdmsId();
        final java.lang.Object other$vdmsId = other.getVdmsId();
        if (this$vdmsId == null ? other$vdmsId != null : !this$vdmsId.equals(other$vdmsId)) return false;
        final java.lang.Object this$updatedBy = this.getUpdatedBy();
        final java.lang.Object other$updatedBy = other.getUpdatedBy();
        if (this$updatedBy == null ? other$updatedBy != null : !this$updatedBy.equals(other$updatedBy)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ClientNfcDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $batchId = this.getBatchId();
        result = result * PRIME + ($batchId == null ? 43 : $batchId.hashCode());
        final java.lang.Object $createdBy = this.getCreatedBy();
        result = result * PRIME + ($createdBy == null ? 43 : $createdBy.hashCode());
        final java.lang.Object $creationTime = this.getCreationTime();
        result = result * PRIME + ($creationTime == null ? 43 : $creationTime.hashCode());
        final java.lang.Object $deviceId = this.getDeviceId();
        result = result * PRIME + ($deviceId == null ? 43 : $deviceId.hashCode());
        final java.lang.Object $locationId = this.getLocationId();
        result = result * PRIME + ($locationId == null ? 43 : $locationId.hashCode());
        final java.lang.Object $nfcId = this.getNfcId();
        result = result * PRIME + ($nfcId == null ? 43 : $nfcId.hashCode());
        final java.lang.Object $uuid = this.getUuid();
        result = result * PRIME + ($uuid == null ? 43 : $uuid.hashCode());
        final java.lang.Object $vdmsId = this.getVdmsId();
        result = result * PRIME + ($vdmsId == null ? 43 : $vdmsId.hashCode());
        final java.lang.Object $updatedBy = this.getUpdatedBy();
        result = result * PRIME + ($updatedBy == null ? 43 : $updatedBy.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ClientNfcDTO(id=" + this.getId() + ", batchId=" + this.getBatchId() + ", createdBy=" + this.getCreatedBy() + ", creationTime=" + this.getCreationTime() + ", deviceId=" + this.getDeviceId() + ", locationId=" + this.getLocationId() + ", nfcId=" + this.getNfcId() + ", uuid=" + this.getUuid() + ", vdmsId=" + this.getVdmsId() + ", updatedBy=" + this.getUpdatedBy() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ClientNfcDTO(final String id, final String batchId, final String createdBy, final BigInteger creationTime, final String deviceId, final String locationId, final String nfcId, final String uuid, final String vdmsId, final String updatedBy) {
        this.id = id;
        this.batchId = batchId;
        this.createdBy = createdBy;
        this.creationTime = creationTime;
        this.deviceId = deviceId;
        this.locationId = locationId;
        this.nfcId = nfcId;
        this.uuid = uuid;
        this.vdmsId = vdmsId;
        this.updatedBy = updatedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ClientNfcDTO() {
    }
}
