// Generated by delombok at Wed May 13 12:25:31 IST 2026
package io.sclera.dto;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class DeviceTechnicianAISuggestionDTO {
    private String id;
    private String deviceType;
    private String technicians;
    private String vdmsId;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeviceType() {
        return this.deviceType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTechnicians() {
        return this.technicians;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVdmsId() {
        return this.vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeviceType(final String deviceType) {
        this.deviceType = deviceType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTechnicians(final String technicians) {
        this.technicians = technicians;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVdmsId(final String vdmsId) {
        this.vdmsId = vdmsId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "DeviceTechnicianAISuggestionDTO(id=" + this.getId() + ", deviceType=" + this.getDeviceType() + ", technicians=" + this.getTechnicians() + ", vdmsId=" + this.getVdmsId() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DeviceTechnicianAISuggestionDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DeviceTechnicianAISuggestionDTO(final String id, final String deviceType, final String technicians, final String vdmsId) {
        this.id = id;
        this.deviceType = deviceType;
        this.technicians = technicians;
        this.vdmsId = vdmsId;
    }
}
