// Generated by delombok at Wed May 13 12:25:50 IST 2026
package io.sclera.dto;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class InventoryApplicationUserDTO {
    private String id;
    private String technicianId;
    private String email;
    private String type; // Field used in getAllApplicationUsersFromInventory for type
    private String userType; // Field used in getApplicationUsersFromInventory for type
    private String applicationId;
    private Integer status;
    private Integer syncStatus;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTechnicianId() {
        return this.technicianId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUserType() {
        return this.userType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getApplicationId() {
        return this.applicationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getSyncStatus() {
        return this.syncStatus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTechnicianId(final String technicianId) {
        this.technicianId = technicianId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUserType(final String userType) {
        this.userType = userType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setApplicationId(final String applicationId) {
        this.applicationId = applicationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSyncStatus(final Integer syncStatus) {
        this.syncStatus = syncStatus;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "InventoryApplicationUserDTO(id=" + this.getId() + ", technicianId=" + this.getTechnicianId() + ", email=" + this.getEmail() + ", type=" + this.getType() + ", userType=" + this.getUserType() + ", applicationId=" + this.getApplicationId() + ", status=" + this.getStatus() + ", syncStatus=" + this.getSyncStatus() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public InventoryApplicationUserDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public InventoryApplicationUserDTO(final String id, final String technicianId, final String email, final String type, final String userType, final String applicationId, final Integer status, final Integer syncStatus) {
        this.id = id;
        this.technicianId = technicianId;
        this.email = email;
        this.type = type;
        this.userType = userType;
        this.applicationId = applicationId;
        this.status = status;
        this.syncStatus = syncStatus;
    }
}
