// Generated by delombok at Wed May 13 12:25:59 IST 2026
package io.sclera.dto;

public class ManagedSoftwareUsersDTO {
    private String username;
    private String userUUID;
    private String accountType;
    private String email;
    private Integer riskStatus;
    private String deviceName;
    private String model;
    private String osType;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ManagedSoftwareUsersDTO(final String username, final String userUUID, final String accountType, final String email, final Integer riskStatus, final String deviceName, final String model, final String osType) {
        this.username = username;
        this.userUUID = userUUID;
        this.accountType = accountType;
        this.email = email;
        this.riskStatus = riskStatus;
        this.deviceName = deviceName;
        this.model = model;
        this.osType = osType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ManagedSoftwareUsersDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUsername() {
        return this.username;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUserUUID() {
        return this.userUUID;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAccountType() {
        return this.accountType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getRiskStatus() {
        return this.riskStatus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeviceName() {
        return this.deviceName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getModel() {
        return this.model;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getOsType() {
        return this.osType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUsername(final String username) {
        this.username = username;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUserUUID(final String userUUID) {
        this.userUUID = userUUID;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAccountType(final String accountType) {
        this.accountType = accountType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRiskStatus(final Integer riskStatus) {
        this.riskStatus = riskStatus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeviceName(final String deviceName) {
        this.deviceName = deviceName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setModel(final String model) {
        this.model = model;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOsType(final String osType) {
        this.osType = osType;
    }
}
