// Generated by delombok at Wed May 13 12:26:09 IST 2026
package io.sclera.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.math.BigInteger;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class QrCodeDTO {
    private String id;
    private String imageUrl;
    private String locationId;
    private String vdmsId;
    private String deviceId;
    private String createdBy;
    private BigInteger creationTime;
    private String batchId;
    private String qrCodeLink;
    private String updatedTime;
    private String updatedBy;
    private Boolean isDeleted;

    //qrcodedetails
    public QrCodeDTO(String id, String deviceId, String locationId, String updatedBy, String updatedTime) {
        this.id = id;
        this.deviceId = deviceId;
        this.locationId = locationId;
        this.updatedBy = updatedBy;
        this.updatedTime = updatedTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLocationId() {
        return this.locationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVdmsId() {
        return this.vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeviceId() {
        return this.deviceId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigInteger getCreationTime() {
        return this.creationTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBatchId() {
        return this.batchId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getQrCodeLink() {
        return this.qrCodeLink;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUpdatedTime() {
        return this.updatedTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLocationId(final String locationId) {
        this.locationId = locationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVdmsId(final String vdmsId) {
        this.vdmsId = vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeviceId(final String deviceId) {
        this.deviceId = deviceId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedBy(final String createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreationTime(final BigInteger creationTime) {
        this.creationTime = creationTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBatchId(final String batchId) {
        this.batchId = batchId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setQrCodeLink(final String qrCodeLink) {
        this.qrCodeLink = qrCodeLink;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedTime(final String updatedTime) {
        this.updatedTime = updatedTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedBy(final String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsDeleted(final Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof QrCodeDTO)) return false;
        final QrCodeDTO other = (QrCodeDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$isDeleted = this.getIsDeleted();
        final java.lang.Object other$isDeleted = other.getIsDeleted();
        if (this$isDeleted == null ? other$isDeleted != null : !this$isDeleted.equals(other$isDeleted)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$imageUrl = this.getImageUrl();
        final java.lang.Object other$imageUrl = other.getImageUrl();
        if (this$imageUrl == null ? other$imageUrl != null : !this$imageUrl.equals(other$imageUrl)) return false;
        final java.lang.Object this$locationId = this.getLocationId();
        final java.lang.Object other$locationId = other.getLocationId();
        if (this$locationId == null ? other$locationId != null : !this$locationId.equals(other$locationId)) return false;
        final java.lang.Object this$vdmsId = this.getVdmsId();
        final java.lang.Object other$vdmsId = other.getVdmsId();
        if (this$vdmsId == null ? other$vdmsId != null : !this$vdmsId.equals(other$vdmsId)) return false;
        final java.lang.Object this$deviceId = this.getDeviceId();
        final java.lang.Object other$deviceId = other.getDeviceId();
        if (this$deviceId == null ? other$deviceId != null : !this$deviceId.equals(other$deviceId)) return false;
        final java.lang.Object this$createdBy = this.getCreatedBy();
        final java.lang.Object other$createdBy = other.getCreatedBy();
        if (this$createdBy == null ? other$createdBy != null : !this$createdBy.equals(other$createdBy)) return false;
        final java.lang.Object this$creationTime = this.getCreationTime();
        final java.lang.Object other$creationTime = other.getCreationTime();
        if (this$creationTime == null ? other$creationTime != null : !this$creationTime.equals(other$creationTime)) return false;
        final java.lang.Object this$batchId = this.getBatchId();
        final java.lang.Object other$batchId = other.getBatchId();
        if (this$batchId == null ? other$batchId != null : !this$batchId.equals(other$batchId)) return false;
        final java.lang.Object this$qrCodeLink = this.getQrCodeLink();
        final java.lang.Object other$qrCodeLink = other.getQrCodeLink();
        if (this$qrCodeLink == null ? other$qrCodeLink != null : !this$qrCodeLink.equals(other$qrCodeLink)) return false;
        final java.lang.Object this$updatedTime = this.getUpdatedTime();
        final java.lang.Object other$updatedTime = other.getUpdatedTime();
        if (this$updatedTime == null ? other$updatedTime != null : !this$updatedTime.equals(other$updatedTime)) return false;
        final java.lang.Object this$updatedBy = this.getUpdatedBy();
        final java.lang.Object other$updatedBy = other.getUpdatedBy();
        if (this$updatedBy == null ? other$updatedBy != null : !this$updatedBy.equals(other$updatedBy)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof QrCodeDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $isDeleted = this.getIsDeleted();
        result = result * PRIME + ($isDeleted == null ? 43 : $isDeleted.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $imageUrl = this.getImageUrl();
        result = result * PRIME + ($imageUrl == null ? 43 : $imageUrl.hashCode());
        final java.lang.Object $locationId = this.getLocationId();
        result = result * PRIME + ($locationId == null ? 43 : $locationId.hashCode());
        final java.lang.Object $vdmsId = this.getVdmsId();
        result = result * PRIME + ($vdmsId == null ? 43 : $vdmsId.hashCode());
        final java.lang.Object $deviceId = this.getDeviceId();
        result = result * PRIME + ($deviceId == null ? 43 : $deviceId.hashCode());
        final java.lang.Object $createdBy = this.getCreatedBy();
        result = result * PRIME + ($createdBy == null ? 43 : $createdBy.hashCode());
        final java.lang.Object $creationTime = this.getCreationTime();
        result = result * PRIME + ($creationTime == null ? 43 : $creationTime.hashCode());
        final java.lang.Object $batchId = this.getBatchId();
        result = result * PRIME + ($batchId == null ? 43 : $batchId.hashCode());
        final java.lang.Object $qrCodeLink = this.getQrCodeLink();
        result = result * PRIME + ($qrCodeLink == null ? 43 : $qrCodeLink.hashCode());
        final java.lang.Object $updatedTime = this.getUpdatedTime();
        result = result * PRIME + ($updatedTime == null ? 43 : $updatedTime.hashCode());
        final java.lang.Object $updatedBy = this.getUpdatedBy();
        result = result * PRIME + ($updatedBy == null ? 43 : $updatedBy.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "QrCodeDTO(id=" + this.getId() + ", imageUrl=" + this.getImageUrl() + ", locationId=" + this.getLocationId() + ", vdmsId=" + this.getVdmsId() + ", deviceId=" + this.getDeviceId() + ", createdBy=" + this.getCreatedBy() + ", creationTime=" + this.getCreationTime() + ", batchId=" + this.getBatchId() + ", qrCodeLink=" + this.getQrCodeLink() + ", updatedTime=" + this.getUpdatedTime() + ", updatedBy=" + this.getUpdatedBy() + ", isDeleted=" + this.getIsDeleted() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public QrCodeDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public QrCodeDTO(final String id, final String imageUrl, final String locationId, final String vdmsId, final String deviceId, final String createdBy, final BigInteger creationTime, final String batchId, final String qrCodeLink, final String updatedTime, final String updatedBy, final Boolean isDeleted) {
        this.id = id;
        this.imageUrl = imageUrl;
        this.locationId = locationId;
        this.vdmsId = vdmsId;
        this.deviceId = deviceId;
        this.createdBy = createdBy;
        this.creationTime = creationTime;
        this.batchId = batchId;
        this.qrCodeLink = qrCodeLink;
        this.updatedTime = updatedTime;
        this.updatedBy = updatedBy;
        this.isDeleted = isDeleted;
    }
}
