// Generated by delombok at Wed May 13 12:26:14 IST 2026
package io.sclera.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.List;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class RemoteAgentServerDetailsDTO {
    private String id;
    private String name;
    private Integer exposePort;
    private Integer gatewayPort;
    private Integer tunnelTcpPort;
    private Integer tunnelKcpPort;
    private Integer tunnelQuicPort;
    private Integer vhttpPort;
    private Integer webserverPort;
    private String location;
    private String latitude;
    private String longitude;
    private String timezone;
    private String publicIp;
    private String privateIp;
    private String publicDns;
    private String privateDns;
    private Integer serverType;
    private String token;
    private String password;
    private String customDomain;
    private List<RemoteDesktopSessionDTO> sessions;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class RemoteAgentServerDetailsDTOBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String name;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer exposePort;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer gatewayPort;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer tunnelTcpPort;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer tunnelKcpPort;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer tunnelQuicPort;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer vhttpPort;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer webserverPort;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String location;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String latitude;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String longitude;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String timezone;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String publicIp;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String privateIp;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String publicDns;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String privateDns;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer serverType;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String token;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String password;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String customDomain;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<RemoteDesktopSessionDTO> sessions;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        RemoteAgentServerDetailsDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder id(final String id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder exposePort(final Integer exposePort) {
            this.exposePort = exposePort;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder gatewayPort(final Integer gatewayPort) {
            this.gatewayPort = gatewayPort;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder tunnelTcpPort(final Integer tunnelTcpPort) {
            this.tunnelTcpPort = tunnelTcpPort;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder tunnelKcpPort(final Integer tunnelKcpPort) {
            this.tunnelKcpPort = tunnelKcpPort;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder tunnelQuicPort(final Integer tunnelQuicPort) {
            this.tunnelQuicPort = tunnelQuicPort;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder vhttpPort(final Integer vhttpPort) {
            this.vhttpPort = vhttpPort;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder webserverPort(final Integer webserverPort) {
            this.webserverPort = webserverPort;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder location(final String location) {
            this.location = location;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder latitude(final String latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder longitude(final String longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder timezone(final String timezone) {
            this.timezone = timezone;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder publicIp(final String publicIp) {
            this.publicIp = publicIp;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder privateIp(final String privateIp) {
            this.privateIp = privateIp;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder publicDns(final String publicDns) {
            this.publicDns = publicDns;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder privateDns(final String privateDns) {
            this.privateDns = privateDns;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder serverType(final Integer serverType) {
            this.serverType = serverType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder token(final String token) {
            this.token = token;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder password(final String password) {
            this.password = password;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder customDomain(final String customDomain) {
            this.customDomain = customDomain;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder sessions(final List<RemoteDesktopSessionDTO> sessions) {
            this.sessions = sessions;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RemoteAgentServerDetailsDTO build() {
            return new RemoteAgentServerDetailsDTO(this.id, this.name, this.exposePort, this.gatewayPort, this.tunnelTcpPort, this.tunnelKcpPort, this.tunnelQuicPort, this.vhttpPort, this.webserverPort, this.location, this.latitude, this.longitude, this.timezone, this.publicIp, this.privateIp, this.publicDns, this.privateDns, this.serverType, this.token, this.password, this.customDomain, this.sessions);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder(id=" + this.id + ", name=" + this.name + ", exposePort=" + this.exposePort + ", gatewayPort=" + this.gatewayPort + ", tunnelTcpPort=" + this.tunnelTcpPort + ", tunnelKcpPort=" + this.tunnelKcpPort + ", tunnelQuicPort=" + this.tunnelQuicPort + ", vhttpPort=" + this.vhttpPort + ", webserverPort=" + this.webserverPort + ", location=" + this.location + ", latitude=" + this.latitude + ", longitude=" + this.longitude + ", timezone=" + this.timezone + ", publicIp=" + this.publicIp + ", privateIp=" + this.privateIp + ", publicDns=" + this.publicDns + ", privateDns=" + this.privateDns + ", serverType=" + this.serverType + ", token=" + this.token + ", password=" + this.password + ", customDomain=" + this.customDomain + ", sessions=" + this.sessions + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder builder() {
        return new RemoteAgentServerDetailsDTO.RemoteAgentServerDetailsDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getExposePort() {
        return this.exposePort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getGatewayPort() {
        return this.gatewayPort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getTunnelTcpPort() {
        return this.tunnelTcpPort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getTunnelKcpPort() {
        return this.tunnelKcpPort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getTunnelQuicPort() {
        return this.tunnelQuicPort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getVhttpPort() {
        return this.vhttpPort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getWebserverPort() {
        return this.webserverPort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLocation() {
        return this.location;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTimezone() {
        return this.timezone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPublicIp() {
        return this.publicIp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrivateIp() {
        return this.privateIp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPublicDns() {
        return this.publicDns;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrivateDns() {
        return this.privateDns;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getServerType() {
        return this.serverType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getToken() {
        return this.token;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCustomDomain() {
        return this.customDomain;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<RemoteDesktopSessionDTO> getSessions() {
        return this.sessions;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExposePort(final Integer exposePort) {
        this.exposePort = exposePort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGatewayPort(final Integer gatewayPort) {
        this.gatewayPort = gatewayPort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTunnelTcpPort(final Integer tunnelTcpPort) {
        this.tunnelTcpPort = tunnelTcpPort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTunnelKcpPort(final Integer tunnelKcpPort) {
        this.tunnelKcpPort = tunnelKcpPort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTunnelQuicPort(final Integer tunnelQuicPort) {
        this.tunnelQuicPort = tunnelQuicPort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVhttpPort(final Integer vhttpPort) {
        this.vhttpPort = vhttpPort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWebserverPort(final Integer webserverPort) {
        this.webserverPort = webserverPort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLocation(final String location) {
        this.location = location;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLatitude(final String latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLongitude(final String longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTimezone(final String timezone) {
        this.timezone = timezone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPublicIp(final String publicIp) {
        this.publicIp = publicIp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrivateIp(final String privateIp) {
        this.privateIp = privateIp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPublicDns(final String publicDns) {
        this.publicDns = publicDns;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrivateDns(final String privateDns) {
        this.privateDns = privateDns;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setServerType(final Integer serverType) {
        this.serverType = serverType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setToken(final String token) {
        this.token = token;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomDomain(final String customDomain) {
        this.customDomain = customDomain;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSessions(final List<RemoteDesktopSessionDTO> sessions) {
        this.sessions = sessions;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RemoteAgentServerDetailsDTO)) return false;
        final RemoteAgentServerDetailsDTO other = (RemoteAgentServerDetailsDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$exposePort = this.getExposePort();
        final java.lang.Object other$exposePort = other.getExposePort();
        if (this$exposePort == null ? other$exposePort != null : !this$exposePort.equals(other$exposePort)) return false;
        final java.lang.Object this$gatewayPort = this.getGatewayPort();
        final java.lang.Object other$gatewayPort = other.getGatewayPort();
        if (this$gatewayPort == null ? other$gatewayPort != null : !this$gatewayPort.equals(other$gatewayPort)) return false;
        final java.lang.Object this$tunnelTcpPort = this.getTunnelTcpPort();
        final java.lang.Object other$tunnelTcpPort = other.getTunnelTcpPort();
        if (this$tunnelTcpPort == null ? other$tunnelTcpPort != null : !this$tunnelTcpPort.equals(other$tunnelTcpPort)) return false;
        final java.lang.Object this$tunnelKcpPort = this.getTunnelKcpPort();
        final java.lang.Object other$tunnelKcpPort = other.getTunnelKcpPort();
        if (this$tunnelKcpPort == null ? other$tunnelKcpPort != null : !this$tunnelKcpPort.equals(other$tunnelKcpPort)) return false;
        final java.lang.Object this$tunnelQuicPort = this.getTunnelQuicPort();
        final java.lang.Object other$tunnelQuicPort = other.getTunnelQuicPort();
        if (this$tunnelQuicPort == null ? other$tunnelQuicPort != null : !this$tunnelQuicPort.equals(other$tunnelQuicPort)) return false;
        final java.lang.Object this$vhttpPort = this.getVhttpPort();
        final java.lang.Object other$vhttpPort = other.getVhttpPort();
        if (this$vhttpPort == null ? other$vhttpPort != null : !this$vhttpPort.equals(other$vhttpPort)) return false;
        final java.lang.Object this$webserverPort = this.getWebserverPort();
        final java.lang.Object other$webserverPort = other.getWebserverPort();
        if (this$webserverPort == null ? other$webserverPort != null : !this$webserverPort.equals(other$webserverPort)) return false;
        final java.lang.Object this$serverType = this.getServerType();
        final java.lang.Object other$serverType = other.getServerType();
        if (this$serverType == null ? other$serverType != null : !this$serverType.equals(other$serverType)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$location = this.getLocation();
        final java.lang.Object other$location = other.getLocation();
        if (this$location == null ? other$location != null : !this$location.equals(other$location)) return false;
        final java.lang.Object this$latitude = this.getLatitude();
        final java.lang.Object other$latitude = other.getLatitude();
        if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
        final java.lang.Object this$longitude = this.getLongitude();
        final java.lang.Object other$longitude = other.getLongitude();
        if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
        final java.lang.Object this$timezone = this.getTimezone();
        final java.lang.Object other$timezone = other.getTimezone();
        if (this$timezone == null ? other$timezone != null : !this$timezone.equals(other$timezone)) return false;
        final java.lang.Object this$publicIp = this.getPublicIp();
        final java.lang.Object other$publicIp = other.getPublicIp();
        if (this$publicIp == null ? other$publicIp != null : !this$publicIp.equals(other$publicIp)) return false;
        final java.lang.Object this$privateIp = this.getPrivateIp();
        final java.lang.Object other$privateIp = other.getPrivateIp();
        if (this$privateIp == null ? other$privateIp != null : !this$privateIp.equals(other$privateIp)) return false;
        final java.lang.Object this$publicDns = this.getPublicDns();
        final java.lang.Object other$publicDns = other.getPublicDns();
        if (this$publicDns == null ? other$publicDns != null : !this$publicDns.equals(other$publicDns)) return false;
        final java.lang.Object this$privateDns = this.getPrivateDns();
        final java.lang.Object other$privateDns = other.getPrivateDns();
        if (this$privateDns == null ? other$privateDns != null : !this$privateDns.equals(other$privateDns)) return false;
        final java.lang.Object this$token = this.getToken();
        final java.lang.Object other$token = other.getToken();
        if (this$token == null ? other$token != null : !this$token.equals(other$token)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        final java.lang.Object this$customDomain = this.getCustomDomain();
        final java.lang.Object other$customDomain = other.getCustomDomain();
        if (this$customDomain == null ? other$customDomain != null : !this$customDomain.equals(other$customDomain)) return false;
        final java.lang.Object this$sessions = this.getSessions();
        final java.lang.Object other$sessions = other.getSessions();
        if (this$sessions == null ? other$sessions != null : !this$sessions.equals(other$sessions)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RemoteAgentServerDetailsDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $exposePort = this.getExposePort();
        result = result * PRIME + ($exposePort == null ? 43 : $exposePort.hashCode());
        final java.lang.Object $gatewayPort = this.getGatewayPort();
        result = result * PRIME + ($gatewayPort == null ? 43 : $gatewayPort.hashCode());
        final java.lang.Object $tunnelTcpPort = this.getTunnelTcpPort();
        result = result * PRIME + ($tunnelTcpPort == null ? 43 : $tunnelTcpPort.hashCode());
        final java.lang.Object $tunnelKcpPort = this.getTunnelKcpPort();
        result = result * PRIME + ($tunnelKcpPort == null ? 43 : $tunnelKcpPort.hashCode());
        final java.lang.Object $tunnelQuicPort = this.getTunnelQuicPort();
        result = result * PRIME + ($tunnelQuicPort == null ? 43 : $tunnelQuicPort.hashCode());
        final java.lang.Object $vhttpPort = this.getVhttpPort();
        result = result * PRIME + ($vhttpPort == null ? 43 : $vhttpPort.hashCode());
        final java.lang.Object $webserverPort = this.getWebserverPort();
        result = result * PRIME + ($webserverPort == null ? 43 : $webserverPort.hashCode());
        final java.lang.Object $serverType = this.getServerType();
        result = result * PRIME + ($serverType == null ? 43 : $serverType.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $location = this.getLocation();
        result = result * PRIME + ($location == null ? 43 : $location.hashCode());
        final java.lang.Object $latitude = this.getLatitude();
        result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
        final java.lang.Object $longitude = this.getLongitude();
        result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
        final java.lang.Object $timezone = this.getTimezone();
        result = result * PRIME + ($timezone == null ? 43 : $timezone.hashCode());
        final java.lang.Object $publicIp = this.getPublicIp();
        result = result * PRIME + ($publicIp == null ? 43 : $publicIp.hashCode());
        final java.lang.Object $privateIp = this.getPrivateIp();
        result = result * PRIME + ($privateIp == null ? 43 : $privateIp.hashCode());
        final java.lang.Object $publicDns = this.getPublicDns();
        result = result * PRIME + ($publicDns == null ? 43 : $publicDns.hashCode());
        final java.lang.Object $privateDns = this.getPrivateDns();
        result = result * PRIME + ($privateDns == null ? 43 : $privateDns.hashCode());
        final java.lang.Object $token = this.getToken();
        result = result * PRIME + ($token == null ? 43 : $token.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        final java.lang.Object $customDomain = this.getCustomDomain();
        result = result * PRIME + ($customDomain == null ? 43 : $customDomain.hashCode());
        final java.lang.Object $sessions = this.getSessions();
        result = result * PRIME + ($sessions == null ? 43 : $sessions.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "RemoteAgentServerDetailsDTO(id=" + this.getId() + ", name=" + this.getName() + ", exposePort=" + this.getExposePort() + ", gatewayPort=" + this.getGatewayPort() + ", tunnelTcpPort=" + this.getTunnelTcpPort() + ", tunnelKcpPort=" + this.getTunnelKcpPort() + ", tunnelQuicPort=" + this.getTunnelQuicPort() + ", vhttpPort=" + this.getVhttpPort() + ", webserverPort=" + this.getWebserverPort() + ", location=" + this.getLocation() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", timezone=" + this.getTimezone() + ", publicIp=" + this.getPublicIp() + ", privateIp=" + this.getPrivateIp() + ", publicDns=" + this.getPublicDns() + ", privateDns=" + this.getPrivateDns() + ", serverType=" + this.getServerType() + ", token=" + this.getToken() + ", password=" + this.getPassword() + ", customDomain=" + this.getCustomDomain() + ", sessions=" + this.getSessions() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RemoteAgentServerDetailsDTO(final String id, final String name, final Integer exposePort, final Integer gatewayPort, final Integer tunnelTcpPort, final Integer tunnelKcpPort, final Integer tunnelQuicPort, final Integer vhttpPort, final Integer webserverPort, final String location, final String latitude, final String longitude, final String timezone, final String publicIp, final String privateIp, final String publicDns, final String privateDns, final Integer serverType, final String token, final String password, final String customDomain, final List<RemoteDesktopSessionDTO> sessions) {
        this.id = id;
        this.name = name;
        this.exposePort = exposePort;
        this.gatewayPort = gatewayPort;
        this.tunnelTcpPort = tunnelTcpPort;
        this.tunnelKcpPort = tunnelKcpPort;
        this.tunnelQuicPort = tunnelQuicPort;
        this.vhttpPort = vhttpPort;
        this.webserverPort = webserverPort;
        this.location = location;
        this.latitude = latitude;
        this.longitude = longitude;
        this.timezone = timezone;
        this.publicIp = publicIp;
        this.privateIp = privateIp;
        this.publicDns = publicDns;
        this.privateDns = privateDns;
        this.serverType = serverType;
        this.token = token;
        this.password = password;
        this.customDomain = customDomain;
        this.sessions = sessions;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RemoteAgentServerDetailsDTO() {
    }
}
