// Generated by delombok at Wed May 13 12:26:22 IST 2026
package io.sclera.dto;

public class TechnicianAvailabilityDTO {
    private String id;
    private Long startDate;
    private Long endDate;
    private String startTime;
    private String endTime;
    private Boolean isAllDay;
    private String frequency;
    private String technicianId;
    private String condition;
    private Integer sync;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TechnicianAvailabilityDTO(final String id, final Long startDate, final Long endDate, final String startTime, final String endTime, final Boolean isAllDay, final String frequency, final String technicianId, final String condition, final Integer sync) {
        this.id = id;
        this.startDate = startDate;
        this.endDate = endDate;
        this.startTime = startTime;
        this.endTime = endTime;
        this.isAllDay = isAllDay;
        this.frequency = frequency;
        this.technicianId = technicianId;
        this.condition = condition;
        this.sync = sync;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TechnicianAvailabilityDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStartDate(final Long startDate) {
        this.startDate = startDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEndDate(final Long endDate) {
        this.endDate = endDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStartTime(final String startTime) {
        this.startTime = startTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEndTime(final String endTime) {
        this.endTime = endTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsAllDay(final Boolean isAllDay) {
        this.isAllDay = isAllDay;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFrequency(final String frequency) {
        this.frequency = frequency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTechnicianId(final String technicianId) {
        this.technicianId = technicianId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCondition(final String condition) {
        this.condition = condition;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSync(final Integer sync) {
        this.sync = sync;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getStartDate() {
        return this.startDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getEndDate() {
        return this.endDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStartTime() {
        return this.startTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEndTime() {
        return this.endTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsAllDay() {
        return this.isAllDay;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFrequency() {
        return this.frequency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTechnicianId() {
        return this.technicianId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCondition() {
        return this.condition;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getSync() {
        return this.sync;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "TechnicianAvailabilityDTO(id=" + this.getId() + ", startDate=" + this.getStartDate() + ", endDate=" + this.getEndDate() + ", startTime=" + this.getStartTime() + ", endTime=" + this.getEndTime() + ", isAllDay=" + this.getIsAllDay() + ", frequency=" + this.getFrequency() + ", technicianId=" + this.getTechnicianId() + ", condition=" + this.getCondition() + ", sync=" + this.getSync() + ")";
    }
}
