-- Seed data for ConditionsRepositoryIT
-- Row 1: matched by measuring_instrument_id (getConditions / getConditionsById)
INSERT INTO conditions (id, name, value, second_value, alert_message,
    start_time, end_time, schedule, schedule_conditions,
    max_alert_count, alert_count_enabled, alert_count,
    alert_condition, alert, show_alert, show_alert_message_as_value,
    bacnet_object_bacnet_device_id, bacnet_object_id,
    lorawan_sensor_attributes_lorawan_sensor_id, lorawan_sensor_attributes_name,
    snmp_device_id, disruptive_sensor_id,
    my_devices_sensor_attributes_my_devices_sensor_id, my_devices_sensor_attributes_name,
    monnit_sensor_id, pelican_sensor_attributes_pelican_sensor_id, pelican_sensor_attributes_name,
    knx_group_address, knx_group_knx_device_address,
    snmp_object_snmp_device_configuration_id, snmp_object_oid,
    measuring_instrument_id, last_alerted_timestamp, alert_time,
    daintree_device_id, daintree_point_id, alert_profile_id,
    ecobee_sensor_attributes_ecobee_sensor_id, ecobee_sensor_attributes_name,
    modbus_register_id, priority, last_alerted, alert_count_time,
    enable_threshold_line_onchart, color_of_threshold_line_onchart)
VALUES (
    'cond-001', 'TempHigh', '75', '80', 'Temperature too high',
    '08:00', '20:00', 1, null,
    5, 1, 2,
    'above', false, true, false,
    null, null,
    null, null,
    null, null,
    null, null,
    null, null, null,
    null, null,
    null, null,
    'mi-001', 999000000, 30,
    null, null, 'ap-001',
    null, null,
    null, 'high', false, 60,
    1, '#FF0000'
);

-- Row 2: matched by lorawan_sensor_id
INSERT INTO conditions (id, name, value, second_value, alert_message,
    start_time, end_time, schedule, schedule_conditions,
    max_alert_count, alert_count_enabled, alert_count,
    alert_condition, alert, show_alert, show_alert_message_as_value,
    bacnet_object_bacnet_device_id, bacnet_object_id,
    lorawan_sensor_attributes_lorawan_sensor_id, lorawan_sensor_attributes_name,
    snmp_device_id, disruptive_sensor_id,
    my_devices_sensor_attributes_my_devices_sensor_id, my_devices_sensor_attributes_name,
    monnit_sensor_id, pelican_sensor_attributes_pelican_sensor_id, pelican_sensor_attributes_name,
    knx_group_address, knx_group_knx_device_address,
    snmp_object_snmp_device_configuration_id, snmp_object_oid,
    measuring_instrument_id, last_alerted_timestamp, alert_time,
    daintree_device_id, daintree_point_id, alert_profile_id,
    ecobee_sensor_attributes_ecobee_sensor_id, ecobee_sensor_attributes_name,
    modbus_register_id, priority, last_alerted, alert_count_time,
    enable_threshold_line_onchart, color_of_threshold_line_onchart)
VALUES (
    'cond-002', 'Humidity', '60', null, 'Humidity alert',
    null, null, 0, null,
    3, 0, 0,
    'above', false, false, false,
    null, null,
    'lorawan-sensor-001', 'temp',
    null, null,
    null, null,
    null, null, null,
    null, null,
    null, null,
    null, null, null,
    null, null, null,
    null, null,
    null, 'low', false, null,
    0, null
);
