// Generated by delombok at Wed May 13 12:26:55 IST 2026
package io.sclera.dto.touchscreen.settings;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class DockerDTO {
    private String name;
    private String vdms_id;
    private Boolean host;
    private String gateway;
    private String external_ip_address;
    private String system_type;
    private String internal_ip_address;
    private String public_ip_address;
    private Boolean internet_required;
    private String primary_dns;
    private String secondary_dns;
    private Boolean is_static;
    private Boolean is_tagged;
    private Integer vlan_id;
    private String interface_out;
    private String macvlan_name;
    private Integer cidr;
    private String configuration_status;
    private String approval_status;
    private String email;
    private String vendor_org_id;
    private String internet_status;
    private List<ConcurrentHashMap<String, String>> extraHost;
    private Integer network_origin;

    public DockerDTO(String name, String vdms_id, Boolean host, String gateway, String external_ip_address, String system_type, String internal_ip_address, String public_ip_address, Boolean internet_required, String primary_dns, String secondary_dns, Boolean is_static, Boolean is_tagged, Integer vlan_id, String interface_out, String macvlan_name, Integer cidr, String configuration_status, String approval_status, String email, String vendor_org_id, Integer network_origin) {
        this.name = name;
        this.vdms_id = vdms_id;
        this.host = host;
        this.gateway = gateway;
        this.external_ip_address = external_ip_address;
        this.system_type = system_type;
        this.internal_ip_address = internal_ip_address;
        this.public_ip_address = public_ip_address;
        this.internet_required = internet_required;
        this.primary_dns = primary_dns;
        this.secondary_dns = secondary_dns;
        this.is_static = is_static;
        this.is_tagged = is_tagged;
        this.vlan_id = vlan_id;
        this.interface_out = interface_out;
        this.macvlan_name = macvlan_name;
        this.cidr = cidr;
        this.configuration_status = configuration_status;
        this.approval_status = approval_status;
        this.email = email;
        this.vendor_org_id = vendor_org_id;
        this.network_origin = network_origin;
    }

//    public DockerDTO(String name, String vdms_id, Boolean host, String gateway, String external_ip_address,
//			String system_type, String internal_ip_address, String public_ip_address, Boolean internet_required,
//			String primary_dns, String secondary_dns, Boolean is_static, Boolean is_tagged, Integer vlan_id,
//			String interface_out, String macvlan_name, Integer cidr, String configuration_status,
//			String approval_status, String vendor_org_id, String internet_status) {
//		super();
//		this.name = name;
//		this.vdms_id = vdms_id;
//		this.host = host;
//		this.gateway = gateway;
//		this.external_ip_address = external_ip_address;
//		this.system_type = system_type;
//		this.internal_ip_address = internal_ip_address;
//		this.public_ip_address = public_ip_address;
//		this.internet_required = internet_required;
//		this.primary_dns = primary_dns;
//		this.secondary_dns = secondary_dns;
//		this.is_static = is_static;
//		this.is_tagged = is_tagged;
//		this.vlan_id = vlan_id;
//		this.interface_out = interface_out;
//		this.macvlan_name = macvlan_name;
//		this.cidr = cidr;
//		this.configuration_status = configuration_status;
//		this.approval_status = approval_status;
//		this.vendor_org_id = vendor_org_id;
//		this.internet_status = internet_status;
//	}
    public DockerDTO(String name, String vdms_id, Boolean host, String gateway, String external_ip_address, String system_type, String internal_ip_address, String public_ip_address, Boolean internet_required, String primary_dns, String secondary_dns, Boolean is_static, Boolean is_tagged, Integer vlan_id, String interface_out, String macvlan_name, Integer cidr, String configuration_status, String approval_status, String email, String vendor_org_id, String internet_status, Integer network_origin) {
        this.name = name;
        this.vdms_id = vdms_id;
        this.host = host;
        this.gateway = gateway;
        this.external_ip_address = external_ip_address;
        this.system_type = system_type;
        this.internal_ip_address = internal_ip_address;
        this.public_ip_address = public_ip_address;
        this.internet_required = internet_required;
        this.primary_dns = primary_dns;
        this.secondary_dns = secondary_dns;
        this.is_static = is_static;
        this.is_tagged = is_tagged;
        this.vlan_id = vlan_id;
        this.interface_out = interface_out;
        this.macvlan_name = macvlan_name;
        this.cidr = cidr;
        this.configuration_status = configuration_status;
        this.approval_status = approval_status;
        this.email = email;
        this.vendor_org_id = vendor_org_id;
        this.internet_status = internet_status;
        this.network_origin = network_origin;
    }

    // checkifhostpresentbynetworkoriginmapping
    public DockerDTO(String name, Boolean host, Integer network_origin) {
        this.name = name;
        this.host = host;
        this.network_origin = network_origin;
    }

    // checkifhostnetworkspresentmapping
    public DockerDTO(Integer network_origin, Boolean host) {
        this.network_origin = network_origin;
        this.host = host;
    }

    // dockernameslistmapping
    public DockerDTO(String name, Integer network_origin) {
        this.name = name;
        this.network_origin = network_origin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVdms_id() {
        return this.vdms_id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getHost() {
        return this.host;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGateway() {
        return this.gateway;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getExternal_ip_address() {
        return this.external_ip_address;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSystem_type() {
        return this.system_type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getInternal_ip_address() {
        return this.internal_ip_address;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPublic_ip_address() {
        return this.public_ip_address;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getInternet_required() {
        return this.internet_required;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrimary_dns() {
        return this.primary_dns;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSecondary_dns() {
        return this.secondary_dns;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIs_static() {
        return this.is_static;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIs_tagged() {
        return this.is_tagged;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getVlan_id() {
        return this.vlan_id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getInterface_out() {
        return this.interface_out;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMacvlan_name() {
        return this.macvlan_name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getCidr() {
        return this.cidr;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getConfiguration_status() {
        return this.configuration_status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getApproval_status() {
        return this.approval_status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVendor_org_id() {
        return this.vendor_org_id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getInternet_status() {
        return this.internet_status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<ConcurrentHashMap<String, String>> getExtraHost() {
        return this.extraHost;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getNetwork_origin() {
        return this.network_origin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVdms_id(final String vdms_id) {
        this.vdms_id = vdms_id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHost(final Boolean host) {
        this.host = host;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGateway(final String gateway) {
        this.gateway = gateway;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExternal_ip_address(final String external_ip_address) {
        this.external_ip_address = external_ip_address;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSystem_type(final String system_type) {
        this.system_type = system_type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInternal_ip_address(final String internal_ip_address) {
        this.internal_ip_address = internal_ip_address;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPublic_ip_address(final String public_ip_address) {
        this.public_ip_address = public_ip_address;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInternet_required(final Boolean internet_required) {
        this.internet_required = internet_required;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrimary_dns(final String primary_dns) {
        this.primary_dns = primary_dns;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSecondary_dns(final String secondary_dns) {
        this.secondary_dns = secondary_dns;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIs_static(final Boolean is_static) {
        this.is_static = is_static;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIs_tagged(final Boolean is_tagged) {
        this.is_tagged = is_tagged;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVlan_id(final Integer vlan_id) {
        this.vlan_id = vlan_id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInterface_out(final String interface_out) {
        this.interface_out = interface_out;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMacvlan_name(final String macvlan_name) {
        this.macvlan_name = macvlan_name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCidr(final Integer cidr) {
        this.cidr = cidr;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setConfiguration_status(final String configuration_status) {
        this.configuration_status = configuration_status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setApproval_status(final String approval_status) {
        this.approval_status = approval_status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVendor_org_id(final String vendor_org_id) {
        this.vendor_org_id = vendor_org_id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInternet_status(final String internet_status) {
        this.internet_status = internet_status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExtraHost(final List<ConcurrentHashMap<String, String>> extraHost) {
        this.extraHost = extraHost;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNetwork_origin(final Integer network_origin) {
        this.network_origin = network_origin;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DockerDTO)) return false;
        final DockerDTO other = (DockerDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$host = this.getHost();
        final java.lang.Object other$host = other.getHost();
        if (this$host == null ? other$host != null : !this$host.equals(other$host)) return false;
        final java.lang.Object this$internet_required = this.getInternet_required();
        final java.lang.Object other$internet_required = other.getInternet_required();
        if (this$internet_required == null ? other$internet_required != null : !this$internet_required.equals(other$internet_required)) return false;
        final java.lang.Object this$is_static = this.getIs_static();
        final java.lang.Object other$is_static = other.getIs_static();
        if (this$is_static == null ? other$is_static != null : !this$is_static.equals(other$is_static)) return false;
        final java.lang.Object this$is_tagged = this.getIs_tagged();
        final java.lang.Object other$is_tagged = other.getIs_tagged();
        if (this$is_tagged == null ? other$is_tagged != null : !this$is_tagged.equals(other$is_tagged)) return false;
        final java.lang.Object this$vlan_id = this.getVlan_id();
        final java.lang.Object other$vlan_id = other.getVlan_id();
        if (this$vlan_id == null ? other$vlan_id != null : !this$vlan_id.equals(other$vlan_id)) return false;
        final java.lang.Object this$cidr = this.getCidr();
        final java.lang.Object other$cidr = other.getCidr();
        if (this$cidr == null ? other$cidr != null : !this$cidr.equals(other$cidr)) return false;
        final java.lang.Object this$network_origin = this.getNetwork_origin();
        final java.lang.Object other$network_origin = other.getNetwork_origin();
        if (this$network_origin == null ? other$network_origin != null : !this$network_origin.equals(other$network_origin)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$vdms_id = this.getVdms_id();
        final java.lang.Object other$vdms_id = other.getVdms_id();
        if (this$vdms_id == null ? other$vdms_id != null : !this$vdms_id.equals(other$vdms_id)) return false;
        final java.lang.Object this$gateway = this.getGateway();
        final java.lang.Object other$gateway = other.getGateway();
        if (this$gateway == null ? other$gateway != null : !this$gateway.equals(other$gateway)) return false;
        final java.lang.Object this$external_ip_address = this.getExternal_ip_address();
        final java.lang.Object other$external_ip_address = other.getExternal_ip_address();
        if (this$external_ip_address == null ? other$external_ip_address != null : !this$external_ip_address.equals(other$external_ip_address)) return false;
        final java.lang.Object this$system_type = this.getSystem_type();
        final java.lang.Object other$system_type = other.getSystem_type();
        if (this$system_type == null ? other$system_type != null : !this$system_type.equals(other$system_type)) return false;
        final java.lang.Object this$internal_ip_address = this.getInternal_ip_address();
        final java.lang.Object other$internal_ip_address = other.getInternal_ip_address();
        if (this$internal_ip_address == null ? other$internal_ip_address != null : !this$internal_ip_address.equals(other$internal_ip_address)) return false;
        final java.lang.Object this$public_ip_address = this.getPublic_ip_address();
        final java.lang.Object other$public_ip_address = other.getPublic_ip_address();
        if (this$public_ip_address == null ? other$public_ip_address != null : !this$public_ip_address.equals(other$public_ip_address)) return false;
        final java.lang.Object this$primary_dns = this.getPrimary_dns();
        final java.lang.Object other$primary_dns = other.getPrimary_dns();
        if (this$primary_dns == null ? other$primary_dns != null : !this$primary_dns.equals(other$primary_dns)) return false;
        final java.lang.Object this$secondary_dns = this.getSecondary_dns();
        final java.lang.Object other$secondary_dns = other.getSecondary_dns();
        if (this$secondary_dns == null ? other$secondary_dns != null : !this$secondary_dns.equals(other$secondary_dns)) return false;
        final java.lang.Object this$interface_out = this.getInterface_out();
        final java.lang.Object other$interface_out = other.getInterface_out();
        if (this$interface_out == null ? other$interface_out != null : !this$interface_out.equals(other$interface_out)) return false;
        final java.lang.Object this$macvlan_name = this.getMacvlan_name();
        final java.lang.Object other$macvlan_name = other.getMacvlan_name();
        if (this$macvlan_name == null ? other$macvlan_name != null : !this$macvlan_name.equals(other$macvlan_name)) return false;
        final java.lang.Object this$configuration_status = this.getConfiguration_status();
        final java.lang.Object other$configuration_status = other.getConfiguration_status();
        if (this$configuration_status == null ? other$configuration_status != null : !this$configuration_status.equals(other$configuration_status)) return false;
        final java.lang.Object this$approval_status = this.getApproval_status();
        final java.lang.Object other$approval_status = other.getApproval_status();
        if (this$approval_status == null ? other$approval_status != null : !this$approval_status.equals(other$approval_status)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$vendor_org_id = this.getVendor_org_id();
        final java.lang.Object other$vendor_org_id = other.getVendor_org_id();
        if (this$vendor_org_id == null ? other$vendor_org_id != null : !this$vendor_org_id.equals(other$vendor_org_id)) return false;
        final java.lang.Object this$internet_status = this.getInternet_status();
        final java.lang.Object other$internet_status = other.getInternet_status();
        if (this$internet_status == null ? other$internet_status != null : !this$internet_status.equals(other$internet_status)) return false;
        final java.lang.Object this$extraHost = this.getExtraHost();
        final java.lang.Object other$extraHost = other.getExtraHost();
        if (this$extraHost == null ? other$extraHost != null : !this$extraHost.equals(other$extraHost)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DockerDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $host = this.getHost();
        result = result * PRIME + ($host == null ? 43 : $host.hashCode());
        final java.lang.Object $internet_required = this.getInternet_required();
        result = result * PRIME + ($internet_required == null ? 43 : $internet_required.hashCode());
        final java.lang.Object $is_static = this.getIs_static();
        result = result * PRIME + ($is_static == null ? 43 : $is_static.hashCode());
        final java.lang.Object $is_tagged = this.getIs_tagged();
        result = result * PRIME + ($is_tagged == null ? 43 : $is_tagged.hashCode());
        final java.lang.Object $vlan_id = this.getVlan_id();
        result = result * PRIME + ($vlan_id == null ? 43 : $vlan_id.hashCode());
        final java.lang.Object $cidr = this.getCidr();
        result = result * PRIME + ($cidr == null ? 43 : $cidr.hashCode());
        final java.lang.Object $network_origin = this.getNetwork_origin();
        result = result * PRIME + ($network_origin == null ? 43 : $network_origin.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $vdms_id = this.getVdms_id();
        result = result * PRIME + ($vdms_id == null ? 43 : $vdms_id.hashCode());
        final java.lang.Object $gateway = this.getGateway();
        result = result * PRIME + ($gateway == null ? 43 : $gateway.hashCode());
        final java.lang.Object $external_ip_address = this.getExternal_ip_address();
        result = result * PRIME + ($external_ip_address == null ? 43 : $external_ip_address.hashCode());
        final java.lang.Object $system_type = this.getSystem_type();
        result = result * PRIME + ($system_type == null ? 43 : $system_type.hashCode());
        final java.lang.Object $internal_ip_address = this.getInternal_ip_address();
        result = result * PRIME + ($internal_ip_address == null ? 43 : $internal_ip_address.hashCode());
        final java.lang.Object $public_ip_address = this.getPublic_ip_address();
        result = result * PRIME + ($public_ip_address == null ? 43 : $public_ip_address.hashCode());
        final java.lang.Object $primary_dns = this.getPrimary_dns();
        result = result * PRIME + ($primary_dns == null ? 43 : $primary_dns.hashCode());
        final java.lang.Object $secondary_dns = this.getSecondary_dns();
        result = result * PRIME + ($secondary_dns == null ? 43 : $secondary_dns.hashCode());
        final java.lang.Object $interface_out = this.getInterface_out();
        result = result * PRIME + ($interface_out == null ? 43 : $interface_out.hashCode());
        final java.lang.Object $macvlan_name = this.getMacvlan_name();
        result = result * PRIME + ($macvlan_name == null ? 43 : $macvlan_name.hashCode());
        final java.lang.Object $configuration_status = this.getConfiguration_status();
        result = result * PRIME + ($configuration_status == null ? 43 : $configuration_status.hashCode());
        final java.lang.Object $approval_status = this.getApproval_status();
        result = result * PRIME + ($approval_status == null ? 43 : $approval_status.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $vendor_org_id = this.getVendor_org_id();
        result = result * PRIME + ($vendor_org_id == null ? 43 : $vendor_org_id.hashCode());
        final java.lang.Object $internet_status = this.getInternet_status();
        result = result * PRIME + ($internet_status == null ? 43 : $internet_status.hashCode());
        final java.lang.Object $extraHost = this.getExtraHost();
        result = result * PRIME + ($extraHost == null ? 43 : $extraHost.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "DockerDTO(name=" + this.getName() + ", vdms_id=" + this.getVdms_id() + ", host=" + this.getHost() + ", gateway=" + this.getGateway() + ", external_ip_address=" + this.getExternal_ip_address() + ", system_type=" + this.getSystem_type() + ", internal_ip_address=" + this.getInternal_ip_address() + ", public_ip_address=" + this.getPublic_ip_address() + ", internet_required=" + this.getInternet_required() + ", primary_dns=" + this.getPrimary_dns() + ", secondary_dns=" + this.getSecondary_dns() + ", is_static=" + this.getIs_static() + ", is_tagged=" + this.getIs_tagged() + ", vlan_id=" + this.getVlan_id() + ", interface_out=" + this.getInterface_out() + ", macvlan_name=" + this.getMacvlan_name() + ", cidr=" + this.getCidr() + ", configuration_status=" + this.getConfiguration_status() + ", approval_status=" + this.getApproval_status() + ", email=" + this.getEmail() + ", vendor_org_id=" + this.getVendor_org_id() + ", internet_status=" + this.getInternet_status() + ", extraHost=" + this.getExtraHost() + ", network_origin=" + this.getNetwork_origin() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DockerDTO(final String name, final String vdms_id, final Boolean host, final String gateway, final String external_ip_address, final String system_type, final String internal_ip_address, final String public_ip_address, final Boolean internet_required, final String primary_dns, final String secondary_dns, final Boolean is_static, final Boolean is_tagged, final Integer vlan_id, final String interface_out, final String macvlan_name, final Integer cidr, final String configuration_status, final String approval_status, final String email, final String vendor_org_id, final String internet_status, final List<ConcurrentHashMap<String, String>> extraHost, final Integer network_origin) {
        this.name = name;
        this.vdms_id = vdms_id;
        this.host = host;
        this.gateway = gateway;
        this.external_ip_address = external_ip_address;
        this.system_type = system_type;
        this.internal_ip_address = internal_ip_address;
        this.public_ip_address = public_ip_address;
        this.internet_required = internet_required;
        this.primary_dns = primary_dns;
        this.secondary_dns = secondary_dns;
        this.is_static = is_static;
        this.is_tagged = is_tagged;
        this.vlan_id = vlan_id;
        this.interface_out = interface_out;
        this.macvlan_name = macvlan_name;
        this.cidr = cidr;
        this.configuration_status = configuration_status;
        this.approval_status = approval_status;
        this.email = email;
        this.vendor_org_id = vendor_org_id;
        this.internet_status = internet_status;
        this.extraHost = extraHost;
        this.network_origin = network_origin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DockerDTO() {
    }
}
