// Generated by delombok at Wed May 13 12:26:59 IST 2026
package io.sclera.dto.touchscreen.settings;

public class InterfaceDTO {
    private String interface_name;
    private Boolean isActive;
    private String gateway_ip;
    private String ip;
    private String mac_address;
    private String netmask;
    private Integer interface_origin;

    public InterfaceDTO(String interface_name) {
        this.interface_name = interface_name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getInterface_name() {
        return this.interface_name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsActive() {
        return this.isActive;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGateway_ip() {
        return this.gateway_ip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getIp() {
        return this.ip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMac_address() {
        return this.mac_address;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNetmask() {
        return this.netmask;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getInterface_origin() {
        return this.interface_origin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInterface_name(final String interface_name) {
        this.interface_name = interface_name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsActive(final Boolean isActive) {
        this.isActive = isActive;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGateway_ip(final String gateway_ip) {
        this.gateway_ip = gateway_ip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIp(final String ip) {
        this.ip = ip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMac_address(final String mac_address) {
        this.mac_address = mac_address;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNetmask(final String netmask) {
        this.netmask = netmask;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInterface_origin(final Integer interface_origin) {
        this.interface_origin = interface_origin;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof InterfaceDTO)) return false;
        final InterfaceDTO other = (InterfaceDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$isActive = this.getIsActive();
        final java.lang.Object other$isActive = other.getIsActive();
        if (this$isActive == null ? other$isActive != null : !this$isActive.equals(other$isActive)) return false;
        final java.lang.Object this$interface_origin = this.getInterface_origin();
        final java.lang.Object other$interface_origin = other.getInterface_origin();
        if (this$interface_origin == null ? other$interface_origin != null : !this$interface_origin.equals(other$interface_origin)) return false;
        final java.lang.Object this$interface_name = this.getInterface_name();
        final java.lang.Object other$interface_name = other.getInterface_name();
        if (this$interface_name == null ? other$interface_name != null : !this$interface_name.equals(other$interface_name)) return false;
        final java.lang.Object this$gateway_ip = this.getGateway_ip();
        final java.lang.Object other$gateway_ip = other.getGateway_ip();
        if (this$gateway_ip == null ? other$gateway_ip != null : !this$gateway_ip.equals(other$gateway_ip)) return false;
        final java.lang.Object this$ip = this.getIp();
        final java.lang.Object other$ip = other.getIp();
        if (this$ip == null ? other$ip != null : !this$ip.equals(other$ip)) return false;
        final java.lang.Object this$mac_address = this.getMac_address();
        final java.lang.Object other$mac_address = other.getMac_address();
        if (this$mac_address == null ? other$mac_address != null : !this$mac_address.equals(other$mac_address)) return false;
        final java.lang.Object this$netmask = this.getNetmask();
        final java.lang.Object other$netmask = other.getNetmask();
        if (this$netmask == null ? other$netmask != null : !this$netmask.equals(other$netmask)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof InterfaceDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $isActive = this.getIsActive();
        result = result * PRIME + ($isActive == null ? 43 : $isActive.hashCode());
        final java.lang.Object $interface_origin = this.getInterface_origin();
        result = result * PRIME + ($interface_origin == null ? 43 : $interface_origin.hashCode());
        final java.lang.Object $interface_name = this.getInterface_name();
        result = result * PRIME + ($interface_name == null ? 43 : $interface_name.hashCode());
        final java.lang.Object $gateway_ip = this.getGateway_ip();
        result = result * PRIME + ($gateway_ip == null ? 43 : $gateway_ip.hashCode());
        final java.lang.Object $ip = this.getIp();
        result = result * PRIME + ($ip == null ? 43 : $ip.hashCode());
        final java.lang.Object $mac_address = this.getMac_address();
        result = result * PRIME + ($mac_address == null ? 43 : $mac_address.hashCode());
        final java.lang.Object $netmask = this.getNetmask();
        result = result * PRIME + ($netmask == null ? 43 : $netmask.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "InterfaceDTO(interface_name=" + this.getInterface_name() + ", isActive=" + this.getIsActive() + ", gateway_ip=" + this.getGateway_ip() + ", ip=" + this.getIp() + ", mac_address=" + this.getMac_address() + ", netmask=" + this.getNetmask() + ", interface_origin=" + this.getInterface_origin() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public InterfaceDTO(final String interface_name, final Boolean isActive, final String gateway_ip, final String ip, final String mac_address, final String netmask, final Integer interface_origin) {
        this.interface_name = interface_name;
        this.isActive = isActive;
        this.gateway_ip = gateway_ip;
        this.ip = ip;
        this.mac_address = mac_address;
        this.netmask = netmask;
        this.interface_origin = interface_origin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public InterfaceDTO() {
    }
}
