// Generated by delombok at Wed May 13 12:27:04 IST 2026
package io.sclera.dto.touchscreen.settings;

import java.math.BigInteger;

public class VdmsDTO {
    private String id;
    private String activation_status;
    private String location;
    private String timezone;
    private Boolean isConfigured;
    private String property_name;
    private String status;
    private String city;
    private String state;
    private String country;
    private String address;
    private Boolean is_block;
    private BigInteger creation_timestamp;
    private BigInteger last_seen;
    private BigInteger block_timestamp;
    private Integer zip;
    private String longitude;
    private String latitude;
    private String customer_org_id;
    private String publicKey;
    private String accessToken;
    private String refreshToken;
    private String password;
    private String image_url;
    private BigInteger activation_timestamp;
    private String deployment_type;
    private String region;
    private String adc_configuration_id;
    private Integer is_master;
    private Integer has_secondary_device;
    private String secondary_device_id;
    private String master_ip;
    private String slave_ip;

    public VdmsDTO(String id, String activation_status, String status, String location, String timezone, Boolean isConfigured) {
        this.id = id;
        this.activation_status = activation_status;
        this.status = status;
        this.location = location;
        this.timezone = timezone;
        this.isConfigured = isConfigured;
    }

    public VdmsDTO(String id, String customer_org_id, String adc_configuration_id, Integer zip) {
        this.id = id;
        this.customer_org_id = customer_org_id;
        this.adc_configuration_id = adc_configuration_id;
        this.zip = zip;
    }

    public Boolean getConfigured() {
        return isConfigured;
    }

    public void setConfigured(Boolean configured) {
        isConfigured = configured;
    }

    public VdmsDTO(String id, String activation_status, String property_name) {
        super();
        this.id = id;
        this.activation_status = activation_status;
        this.property_name = property_name;
    }

    public VdmsDTO(String id, String activation_status, Boolean isConfigured, String property_name) {
        this.id = id;
        this.activation_status = activation_status;
        this.isConfigured = isConfigured;
        this.property_name = property_name;
    }

    public VdmsDTO(String id, String activation_status, String status, String location, String timezone, String property_name, Boolean isConfigured, BigInteger activation_timestamp, String deployment_type) {
        this.id = id;
        this.activation_status = activation_status;
        this.status = status;
        this.location = location;
        this.timezone = timezone;
        this.property_name = property_name;
        this.isConfigured = isConfigured;
        this.activation_timestamp = activation_timestamp;
        this.deployment_type = deployment_type;
    }

    public VdmsDTO(String id, String property_name, String address, String city, String country, String state, Integer zip, String timezone, String image_url, String latitude, String longitude, BigInteger activation_timestamp, String deployment_type, String region) {
        super();
        this.id = id;
        this.property_name = property_name;
        this.address = address;
        this.city = city;
        this.country = country;
        this.state = state;
        this.zip = zip;
        this.timezone = timezone;
        this.image_url = image_url;
        this.latitude = latitude;
        this.longitude = longitude;
        this.activation_timestamp = activation_timestamp;
        this.deployment_type = deployment_type;
        this.region = region;
    }

    // vdmsmasterslaveinfomapping
    public VdmsDTO(String id, Integer is_master, Integer has_secondary_device, String secondary_device_id, String master_ip, String slave_ip) {
        this.id = id;
        this.is_master = is_master;
        this.has_secondary_device = has_secondary_device;
        this.secondary_device_id = secondary_device_id;
        this.master_ip = master_ip;
        this.slave_ip = slave_ip;
    }

    // vdmsgetconfigurationinfomapping
    public VdmsDTO(String id, String activation_status, String status, String location, String timezone, String property_name, Boolean isConfigured, BigInteger activation_timestamp, String deployment_type, Integer is_master) {
        this.id = id;
        this.activation_status = activation_status;
        this.status = status;
        this.location = location;
        this.timezone = timezone;
        this.property_name = property_name;
        this.isConfigured = isConfigured;
        this.activation_timestamp = activation_timestamp;
        this.deployment_type = deployment_type;
        this.is_master = is_master;
    }

    public VdmsDTO() {
        super();
        // TODO Auto-generated constructor stub
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getActivation_status() {
        return this.activation_status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLocation() {
        return this.location;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTimezone() {
        return this.timezone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsConfigured() {
        return this.isConfigured;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getProperty_name() {
        return this.property_name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCity() {
        return this.city;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getState() {
        return this.state;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCountry() {
        return this.country;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIs_block() {
        return this.is_block;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigInteger getCreation_timestamp() {
        return this.creation_timestamp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigInteger getLast_seen() {
        return this.last_seen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigInteger getBlock_timestamp() {
        return this.block_timestamp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getZip() {
        return this.zip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCustomer_org_id() {
        return this.customer_org_id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPublicKey() {
        return this.publicKey;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAccessToken() {
        return this.accessToken;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRefreshToken() {
        return this.refreshToken;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getImage_url() {
        return this.image_url;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigInteger getActivation_timestamp() {
        return this.activation_timestamp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeployment_type() {
        return this.deployment_type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRegion() {
        return this.region;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAdc_configuration_id() {
        return this.adc_configuration_id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getIs_master() {
        return this.is_master;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getHas_secondary_device() {
        return this.has_secondary_device;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSecondary_device_id() {
        return this.secondary_device_id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMaster_ip() {
        return this.master_ip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSlave_ip() {
        return this.slave_ip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setActivation_status(final String activation_status) {
        this.activation_status = activation_status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLocation(final String location) {
        this.location = location;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTimezone(final String timezone) {
        this.timezone = timezone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsConfigured(final Boolean isConfigured) {
        this.isConfigured = isConfigured;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProperty_name(final String property_name) {
        this.property_name = property_name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCity(final String city) {
        this.city = city;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setState(final String state) {
        this.state = state;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCountry(final String country) {
        this.country = country;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIs_block(final Boolean is_block) {
        this.is_block = is_block;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreation_timestamp(final BigInteger creation_timestamp) {
        this.creation_timestamp = creation_timestamp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLast_seen(final BigInteger last_seen) {
        this.last_seen = last_seen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBlock_timestamp(final BigInteger block_timestamp) {
        this.block_timestamp = block_timestamp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setZip(final Integer zip) {
        this.zip = zip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLongitude(final String longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLatitude(final String latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomer_org_id(final String customer_org_id) {
        this.customer_org_id = customer_org_id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPublicKey(final String publicKey) {
        this.publicKey = publicKey;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAccessToken(final String accessToken) {
        this.accessToken = accessToken;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRefreshToken(final String refreshToken) {
        this.refreshToken = refreshToken;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setImage_url(final String image_url) {
        this.image_url = image_url;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setActivation_timestamp(final BigInteger activation_timestamp) {
        this.activation_timestamp = activation_timestamp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeployment_type(final String deployment_type) {
        this.deployment_type = deployment_type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRegion(final String region) {
        this.region = region;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAdc_configuration_id(final String adc_configuration_id) {
        this.adc_configuration_id = adc_configuration_id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIs_master(final Integer is_master) {
        this.is_master = is_master;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHas_secondary_device(final Integer has_secondary_device) {
        this.has_secondary_device = has_secondary_device;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSecondary_device_id(final String secondary_device_id) {
        this.secondary_device_id = secondary_device_id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMaster_ip(final String master_ip) {
        this.master_ip = master_ip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSlave_ip(final String slave_ip) {
        this.slave_ip = slave_ip;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof VdmsDTO)) return false;
        final VdmsDTO other = (VdmsDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$isConfigured = this.getIsConfigured();
        final java.lang.Object other$isConfigured = other.getIsConfigured();
        if (this$isConfigured == null ? other$isConfigured != null : !this$isConfigured.equals(other$isConfigured)) return false;
        final java.lang.Object this$is_block = this.getIs_block();
        final java.lang.Object other$is_block = other.getIs_block();
        if (this$is_block == null ? other$is_block != null : !this$is_block.equals(other$is_block)) return false;
        final java.lang.Object this$zip = this.getZip();
        final java.lang.Object other$zip = other.getZip();
        if (this$zip == null ? other$zip != null : !this$zip.equals(other$zip)) return false;
        final java.lang.Object this$is_master = this.getIs_master();
        final java.lang.Object other$is_master = other.getIs_master();
        if (this$is_master == null ? other$is_master != null : !this$is_master.equals(other$is_master)) return false;
        final java.lang.Object this$has_secondary_device = this.getHas_secondary_device();
        final java.lang.Object other$has_secondary_device = other.getHas_secondary_device();
        if (this$has_secondary_device == null ? other$has_secondary_device != null : !this$has_secondary_device.equals(other$has_secondary_device)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$activation_status = this.getActivation_status();
        final java.lang.Object other$activation_status = other.getActivation_status();
        if (this$activation_status == null ? other$activation_status != null : !this$activation_status.equals(other$activation_status)) return false;
        final java.lang.Object this$location = this.getLocation();
        final java.lang.Object other$location = other.getLocation();
        if (this$location == null ? other$location != null : !this$location.equals(other$location)) return false;
        final java.lang.Object this$timezone = this.getTimezone();
        final java.lang.Object other$timezone = other.getTimezone();
        if (this$timezone == null ? other$timezone != null : !this$timezone.equals(other$timezone)) return false;
        final java.lang.Object this$property_name = this.getProperty_name();
        final java.lang.Object other$property_name = other.getProperty_name();
        if (this$property_name == null ? other$property_name != null : !this$property_name.equals(other$property_name)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$city = this.getCity();
        final java.lang.Object other$city = other.getCity();
        if (this$city == null ? other$city != null : !this$city.equals(other$city)) return false;
        final java.lang.Object this$state = this.getState();
        final java.lang.Object other$state = other.getState();
        if (this$state == null ? other$state != null : !this$state.equals(other$state)) return false;
        final java.lang.Object this$country = this.getCountry();
        final java.lang.Object other$country = other.getCountry();
        if (this$country == null ? other$country != null : !this$country.equals(other$country)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        final java.lang.Object this$creation_timestamp = this.getCreation_timestamp();
        final java.lang.Object other$creation_timestamp = other.getCreation_timestamp();
        if (this$creation_timestamp == null ? other$creation_timestamp != null : !this$creation_timestamp.equals(other$creation_timestamp)) return false;
        final java.lang.Object this$last_seen = this.getLast_seen();
        final java.lang.Object other$last_seen = other.getLast_seen();
        if (this$last_seen == null ? other$last_seen != null : !this$last_seen.equals(other$last_seen)) return false;
        final java.lang.Object this$block_timestamp = this.getBlock_timestamp();
        final java.lang.Object other$block_timestamp = other.getBlock_timestamp();
        if (this$block_timestamp == null ? other$block_timestamp != null : !this$block_timestamp.equals(other$block_timestamp)) return false;
        final java.lang.Object this$longitude = this.getLongitude();
        final java.lang.Object other$longitude = other.getLongitude();
        if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
        final java.lang.Object this$latitude = this.getLatitude();
        final java.lang.Object other$latitude = other.getLatitude();
        if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
        final java.lang.Object this$customer_org_id = this.getCustomer_org_id();
        final java.lang.Object other$customer_org_id = other.getCustomer_org_id();
        if (this$customer_org_id == null ? other$customer_org_id != null : !this$customer_org_id.equals(other$customer_org_id)) return false;
        final java.lang.Object this$publicKey = this.getPublicKey();
        final java.lang.Object other$publicKey = other.getPublicKey();
        if (this$publicKey == null ? other$publicKey != null : !this$publicKey.equals(other$publicKey)) return false;
        final java.lang.Object this$accessToken = this.getAccessToken();
        final java.lang.Object other$accessToken = other.getAccessToken();
        if (this$accessToken == null ? other$accessToken != null : !this$accessToken.equals(other$accessToken)) return false;
        final java.lang.Object this$refreshToken = this.getRefreshToken();
        final java.lang.Object other$refreshToken = other.getRefreshToken();
        if (this$refreshToken == null ? other$refreshToken != null : !this$refreshToken.equals(other$refreshToken)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        final java.lang.Object this$image_url = this.getImage_url();
        final java.lang.Object other$image_url = other.getImage_url();
        if (this$image_url == null ? other$image_url != null : !this$image_url.equals(other$image_url)) return false;
        final java.lang.Object this$activation_timestamp = this.getActivation_timestamp();
        final java.lang.Object other$activation_timestamp = other.getActivation_timestamp();
        if (this$activation_timestamp == null ? other$activation_timestamp != null : !this$activation_timestamp.equals(other$activation_timestamp)) return false;
        final java.lang.Object this$deployment_type = this.getDeployment_type();
        final java.lang.Object other$deployment_type = other.getDeployment_type();
        if (this$deployment_type == null ? other$deployment_type != null : !this$deployment_type.equals(other$deployment_type)) return false;
        final java.lang.Object this$region = this.getRegion();
        final java.lang.Object other$region = other.getRegion();
        if (this$region == null ? other$region != null : !this$region.equals(other$region)) return false;
        final java.lang.Object this$adc_configuration_id = this.getAdc_configuration_id();
        final java.lang.Object other$adc_configuration_id = other.getAdc_configuration_id();
        if (this$adc_configuration_id == null ? other$adc_configuration_id != null : !this$adc_configuration_id.equals(other$adc_configuration_id)) return false;
        final java.lang.Object this$secondary_device_id = this.getSecondary_device_id();
        final java.lang.Object other$secondary_device_id = other.getSecondary_device_id();
        if (this$secondary_device_id == null ? other$secondary_device_id != null : !this$secondary_device_id.equals(other$secondary_device_id)) return false;
        final java.lang.Object this$master_ip = this.getMaster_ip();
        final java.lang.Object other$master_ip = other.getMaster_ip();
        if (this$master_ip == null ? other$master_ip != null : !this$master_ip.equals(other$master_ip)) return false;
        final java.lang.Object this$slave_ip = this.getSlave_ip();
        final java.lang.Object other$slave_ip = other.getSlave_ip();
        if (this$slave_ip == null ? other$slave_ip != null : !this$slave_ip.equals(other$slave_ip)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof VdmsDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $isConfigured = this.getIsConfigured();
        result = result * PRIME + ($isConfigured == null ? 43 : $isConfigured.hashCode());
        final java.lang.Object $is_block = this.getIs_block();
        result = result * PRIME + ($is_block == null ? 43 : $is_block.hashCode());
        final java.lang.Object $zip = this.getZip();
        result = result * PRIME + ($zip == null ? 43 : $zip.hashCode());
        final java.lang.Object $is_master = this.getIs_master();
        result = result * PRIME + ($is_master == null ? 43 : $is_master.hashCode());
        final java.lang.Object $has_secondary_device = this.getHas_secondary_device();
        result = result * PRIME + ($has_secondary_device == null ? 43 : $has_secondary_device.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $activation_status = this.getActivation_status();
        result = result * PRIME + ($activation_status == null ? 43 : $activation_status.hashCode());
        final java.lang.Object $location = this.getLocation();
        result = result * PRIME + ($location == null ? 43 : $location.hashCode());
        final java.lang.Object $timezone = this.getTimezone();
        result = result * PRIME + ($timezone == null ? 43 : $timezone.hashCode());
        final java.lang.Object $property_name = this.getProperty_name();
        result = result * PRIME + ($property_name == null ? 43 : $property_name.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $city = this.getCity();
        result = result * PRIME + ($city == null ? 43 : $city.hashCode());
        final java.lang.Object $state = this.getState();
        result = result * PRIME + ($state == null ? 43 : $state.hashCode());
        final java.lang.Object $country = this.getCountry();
        result = result * PRIME + ($country == null ? 43 : $country.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        final java.lang.Object $creation_timestamp = this.getCreation_timestamp();
        result = result * PRIME + ($creation_timestamp == null ? 43 : $creation_timestamp.hashCode());
        final java.lang.Object $last_seen = this.getLast_seen();
        result = result * PRIME + ($last_seen == null ? 43 : $last_seen.hashCode());
        final java.lang.Object $block_timestamp = this.getBlock_timestamp();
        result = result * PRIME + ($block_timestamp == null ? 43 : $block_timestamp.hashCode());
        final java.lang.Object $longitude = this.getLongitude();
        result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
        final java.lang.Object $latitude = this.getLatitude();
        result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
        final java.lang.Object $customer_org_id = this.getCustomer_org_id();
        result = result * PRIME + ($customer_org_id == null ? 43 : $customer_org_id.hashCode());
        final java.lang.Object $publicKey = this.getPublicKey();
        result = result * PRIME + ($publicKey == null ? 43 : $publicKey.hashCode());
        final java.lang.Object $accessToken = this.getAccessToken();
        result = result * PRIME + ($accessToken == null ? 43 : $accessToken.hashCode());
        final java.lang.Object $refreshToken = this.getRefreshToken();
        result = result * PRIME + ($refreshToken == null ? 43 : $refreshToken.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        final java.lang.Object $image_url = this.getImage_url();
        result = result * PRIME + ($image_url == null ? 43 : $image_url.hashCode());
        final java.lang.Object $activation_timestamp = this.getActivation_timestamp();
        result = result * PRIME + ($activation_timestamp == null ? 43 : $activation_timestamp.hashCode());
        final java.lang.Object $deployment_type = this.getDeployment_type();
        result = result * PRIME + ($deployment_type == null ? 43 : $deployment_type.hashCode());
        final java.lang.Object $region = this.getRegion();
        result = result * PRIME + ($region == null ? 43 : $region.hashCode());
        final java.lang.Object $adc_configuration_id = this.getAdc_configuration_id();
        result = result * PRIME + ($adc_configuration_id == null ? 43 : $adc_configuration_id.hashCode());
        final java.lang.Object $secondary_device_id = this.getSecondary_device_id();
        result = result * PRIME + ($secondary_device_id == null ? 43 : $secondary_device_id.hashCode());
        final java.lang.Object $master_ip = this.getMaster_ip();
        result = result * PRIME + ($master_ip == null ? 43 : $master_ip.hashCode());
        final java.lang.Object $slave_ip = this.getSlave_ip();
        result = result * PRIME + ($slave_ip == null ? 43 : $slave_ip.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "VdmsDTO(id=" + this.getId() + ", activation_status=" + this.getActivation_status() + ", location=" + this.getLocation() + ", timezone=" + this.getTimezone() + ", isConfigured=" + this.getIsConfigured() + ", property_name=" + this.getProperty_name() + ", status=" + this.getStatus() + ", city=" + this.getCity() + ", state=" + this.getState() + ", country=" + this.getCountry() + ", address=" + this.getAddress() + ", is_block=" + this.getIs_block() + ", creation_timestamp=" + this.getCreation_timestamp() + ", last_seen=" + this.getLast_seen() + ", block_timestamp=" + this.getBlock_timestamp() + ", zip=" + this.getZip() + ", longitude=" + this.getLongitude() + ", latitude=" + this.getLatitude() + ", customer_org_id=" + this.getCustomer_org_id() + ", publicKey=" + this.getPublicKey() + ", accessToken=" + this.getAccessToken() + ", refreshToken=" + this.getRefreshToken() + ", password=" + this.getPassword() + ", image_url=" + this.getImage_url() + ", activation_timestamp=" + this.getActivation_timestamp() + ", deployment_type=" + this.getDeployment_type() + ", region=" + this.getRegion() + ", adc_configuration_id=" + this.getAdc_configuration_id() + ", is_master=" + this.getIs_master() + ", has_secondary_device=" + this.getHas_secondary_device() + ", secondary_device_id=" + this.getSecondary_device_id() + ", master_ip=" + this.getMaster_ip() + ", slave_ip=" + this.getSlave_ip() + ")";
    }
}
