// Generated by delombok at Wed May 13 12:24:53 IST 2026
package io.sclera.auth.dto;

public class TenantDTO {
    private String id;
    private String issuer;
    private String jwksUri;
    private String providerId;

    public TenantDTO(String issuer, String jwksUri) {
        this.issuer = issuer;
        this.jwksUri = jwksUri;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class TenantDTOBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String issuer;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String jwksUri;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String providerId;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        TenantDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TenantDTO.TenantDTOBuilder id(final String id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TenantDTO.TenantDTOBuilder issuer(final String issuer) {
            this.issuer = issuer;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TenantDTO.TenantDTOBuilder jwksUri(final String jwksUri) {
            this.jwksUri = jwksUri;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TenantDTO.TenantDTOBuilder providerId(final String providerId) {
            this.providerId = providerId;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TenantDTO build() {
            return new TenantDTO(this.id, this.issuer, this.jwksUri, this.providerId);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "TenantDTO.TenantDTOBuilder(id=" + this.id + ", issuer=" + this.issuer + ", jwksUri=" + this.jwksUri + ", providerId=" + this.providerId + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static TenantDTO.TenantDTOBuilder builder() {
        return new TenantDTO.TenantDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TenantDTO(final String id, final String issuer, final String jwksUri, final String providerId) {
        this.id = id;
        this.issuer = issuer;
        this.jwksUri = jwksUri;
        this.providerId = providerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TenantDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getIssuer() {
        return this.issuer;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getJwksUri() {
        return this.jwksUri;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getProviderId() {
        return this.providerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIssuer(final String issuer) {
        this.issuer = issuer;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setJwksUri(final String jwksUri) {
        this.jwksUri = jwksUri;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProviderId(final String providerId) {
        this.providerId = providerId;
    }
}
