server:
  port: 8097

spring:
  application:
    name: sclera-edge

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

dapr:
  http-port: ${DAPR_HTTP_PORT:3500}
  grpc-port: ${DAPR_GRPC_PORT:50001}

logging:
  level:
    io.sclera.edge: INFO
    io.dapr: INFO
