// Generated by delombok at Wed May 13 12:26:45 IST 2026
package io.sclera.dto.touchscreen;

import com.fasterxml.jackson.annotation.JsonAlias;

public class NetworkToolsDTO {
    private String username;
    private String vdmsId;
    private String networkName;
    private String input;
    private String privateIp;
    private String publicIp;
    private Integer privatePort;
    private Integer publicPort;
    private String dockerIp;
    private Integer network_origin;
    @JsonAlias({"isSecure"})
    private Boolean isSecure;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUsername() {
        return this.username;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVdmsId() {
        return this.vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNetworkName() {
        return this.networkName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getInput() {
        return this.input;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrivateIp() {
        return this.privateIp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPublicIp() {
        return this.publicIp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getPrivatePort() {
        return this.privatePort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getPublicPort() {
        return this.publicPort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDockerIp() {
        return this.dockerIp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getNetwork_origin() {
        return this.network_origin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsSecure() {
        return this.isSecure;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUsername(final String username) {
        this.username = username;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVdmsId(final String vdmsId) {
        this.vdmsId = vdmsId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNetworkName(final String networkName) {
        this.networkName = networkName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInput(final String input) {
        this.input = input;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrivateIp(final String privateIp) {
        this.privateIp = privateIp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPublicIp(final String publicIp) {
        this.publicIp = publicIp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrivatePort(final Integer privatePort) {
        this.privatePort = privatePort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPublicPort(final Integer publicPort) {
        this.publicPort = publicPort;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDockerIp(final String dockerIp) {
        this.dockerIp = dockerIp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNetwork_origin(final Integer network_origin) {
        this.network_origin = network_origin;
    }

    @JsonAlias({"isSecure"})
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsSecure(final Boolean isSecure) {
        this.isSecure = isSecure;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof NetworkToolsDTO)) return false;
        final NetworkToolsDTO other = (NetworkToolsDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$privatePort = this.getPrivatePort();
        final java.lang.Object other$privatePort = other.getPrivatePort();
        if (this$privatePort == null ? other$privatePort != null : !this$privatePort.equals(other$privatePort)) return false;
        final java.lang.Object this$publicPort = this.getPublicPort();
        final java.lang.Object other$publicPort = other.getPublicPort();
        if (this$publicPort == null ? other$publicPort != null : !this$publicPort.equals(other$publicPort)) return false;
        final java.lang.Object this$network_origin = this.getNetwork_origin();
        final java.lang.Object other$network_origin = other.getNetwork_origin();
        if (this$network_origin == null ? other$network_origin != null : !this$network_origin.equals(other$network_origin)) return false;
        final java.lang.Object this$isSecure = this.getIsSecure();
        final java.lang.Object other$isSecure = other.getIsSecure();
        if (this$isSecure == null ? other$isSecure != null : !this$isSecure.equals(other$isSecure)) return false;
        final java.lang.Object this$username = this.getUsername();
        final java.lang.Object other$username = other.getUsername();
        if (this$username == null ? other$username != null : !this$username.equals(other$username)) return false;
        final java.lang.Object this$vdmsId = this.getVdmsId();
        final java.lang.Object other$vdmsId = other.getVdmsId();
        if (this$vdmsId == null ? other$vdmsId != null : !this$vdmsId.equals(other$vdmsId)) return false;
        final java.lang.Object this$networkName = this.getNetworkName();
        final java.lang.Object other$networkName = other.getNetworkName();
        if (this$networkName == null ? other$networkName != null : !this$networkName.equals(other$networkName)) return false;
        final java.lang.Object this$input = this.getInput();
        final java.lang.Object other$input = other.getInput();
        if (this$input == null ? other$input != null : !this$input.equals(other$input)) return false;
        final java.lang.Object this$privateIp = this.getPrivateIp();
        final java.lang.Object other$privateIp = other.getPrivateIp();
        if (this$privateIp == null ? other$privateIp != null : !this$privateIp.equals(other$privateIp)) return false;
        final java.lang.Object this$publicIp = this.getPublicIp();
        final java.lang.Object other$publicIp = other.getPublicIp();
        if (this$publicIp == null ? other$publicIp != null : !this$publicIp.equals(other$publicIp)) return false;
        final java.lang.Object this$dockerIp = this.getDockerIp();
        final java.lang.Object other$dockerIp = other.getDockerIp();
        if (this$dockerIp == null ? other$dockerIp != null : !this$dockerIp.equals(other$dockerIp)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof NetworkToolsDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $privatePort = this.getPrivatePort();
        result = result * PRIME + ($privatePort == null ? 43 : $privatePort.hashCode());
        final java.lang.Object $publicPort = this.getPublicPort();
        result = result * PRIME + ($publicPort == null ? 43 : $publicPort.hashCode());
        final java.lang.Object $network_origin = this.getNetwork_origin();
        result = result * PRIME + ($network_origin == null ? 43 : $network_origin.hashCode());
        final java.lang.Object $isSecure = this.getIsSecure();
        result = result * PRIME + ($isSecure == null ? 43 : $isSecure.hashCode());
        final java.lang.Object $username = this.getUsername();
        result = result * PRIME + ($username == null ? 43 : $username.hashCode());
        final java.lang.Object $vdmsId = this.getVdmsId();
        result = result * PRIME + ($vdmsId == null ? 43 : $vdmsId.hashCode());
        final java.lang.Object $networkName = this.getNetworkName();
        result = result * PRIME + ($networkName == null ? 43 : $networkName.hashCode());
        final java.lang.Object $input = this.getInput();
        result = result * PRIME + ($input == null ? 43 : $input.hashCode());
        final java.lang.Object $privateIp = this.getPrivateIp();
        result = result * PRIME + ($privateIp == null ? 43 : $privateIp.hashCode());
        final java.lang.Object $publicIp = this.getPublicIp();
        result = result * PRIME + ($publicIp == null ? 43 : $publicIp.hashCode());
        final java.lang.Object $dockerIp = this.getDockerIp();
        result = result * PRIME + ($dockerIp == null ? 43 : $dockerIp.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "NetworkToolsDTO(username=" + this.getUsername() + ", vdmsId=" + this.getVdmsId() + ", networkName=" + this.getNetworkName() + ", input=" + this.getInput() + ", privateIp=" + this.getPrivateIp() + ", publicIp=" + this.getPublicIp() + ", privatePort=" + this.getPrivatePort() + ", publicPort=" + this.getPublicPort() + ", dockerIp=" + this.getDockerIp() + ", network_origin=" + this.getNetwork_origin() + ", isSecure=" + this.getIsSecure() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public NetworkToolsDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public NetworkToolsDTO(final String username, final String vdmsId, final String networkName, final String input, final String privateIp, final String publicIp, final Integer privatePort, final Integer publicPort, final String dockerIp, final Integer network_origin, final Boolean isSecure) {
        this.username = username;
        this.vdmsId = vdmsId;
        this.networkName = networkName;
        this.input = input;
        this.privateIp = privateIp;
        this.publicIp = publicIp;
        this.privatePort = privatePort;
        this.publicPort = publicPort;
        this.dockerIp = dockerIp;
        this.network_origin = network_origin;
        this.isSecure = isSecure;
    }
}
