package io.sclera.enums;

public enum TicketType {

    NO_CHANGES(0, "No changes in updated ticket"),
    GENERATED_BY_CUSTOMER(1, "Ticket Generated by Customer"),
    STATUS_UPDATED_BY_CUSTOMER(2, "Ticket Status Updated by Customer"),
    MESSAGE_UPDATED_BY_CUSTOMER(3, "Ticket User Message Updated by Customer"),
    STATUS_AND_MESSAGE_UPDATED_BY_CUSTOMER(4, "Ticket User Message and Status Updated by Customer"),
    STATUS_UPDATED_BY_VENDOR(5, "Ticket Status Updated by Vendor"),
    MESSAGE_UPDATED_BY_VENDOR(6, "Ticket Vendor Message Updated by Vendor"),
    STATUS_AND_MESSAGE_UPDATED_BY_VENDOR(7, "Ticket Vendor Message and Status Updated by Vendor"),
    REOPENED_BY_CUSTOMER(8, "Ticket Re-Opened by Customer"),
    ASSIGNED(9, "Ticket Assignment Changed"),
    STATUS_UPDATED_AND_ASSIGNED(10, "Status Updated and Assignment Changed"),
    MESSAGE_UPDATED_AND_ASSIGNED(11, "User Message Updated and Assignment Changed"),
    STATUS_AND_MESSAGE_UPDATED_AND_ASSIGNED(12, "Status Updated , User Message Updated and Assignment Changed"),
    UNASSIGNED(13, "Ticket Unassigned"),
    STATUS_UPDATED_AND_UNASSIGNED(14, "Status Updated and Unassigned"),
    MESSAGE_UPDATED_AND_UNASSIGNED(15, "User Message Updated and Unassigned"),
    STATUS_AND_MESSAGE_UPDATED_AND_UNASSIGNED(16, "Status Updated , User Message Updated and Unassigned"),
    CLOSED(17, "Ticket Closed");

    private final int value;
    private final String description;

    TicketType(int value, String description) {
        this.value = value;
        this.description = description;
    }

    // Optional: Method to get enum by value
    public static TicketType fromValue(int value) {
        for (TicketType type : TicketType.values()) {
            if (type.getValue() == value) {
                return type;
            }
        }
        throw new IllegalArgumentException("Unknown ticket type value: " + value);
    }

    public int getValue() {
        return value;
    }

    public String getDescription() {
        return description;
    }
}